### ISSUE TITLE
Problem with labels method on metrics objects

### ISSUE THREAD

**Issue by claws** [prometheus/client_python#100]
I am expecting to be able to set labels on a Counter like in the examples:

``` python
from prometheus_client import Counter
c = Counter('my_requests_total', 'HTTP Failures', ['method', 'endpoint'])
c.labels(method='get', endpoint='/').inc()
```

I am using prometheus-client (0.0.14) from PyPI.

``` console
$ python
Python 2.7.12 (v2.7.12:d33e0cf91556, Jun 26 2016, 12:10:39) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from prometheus_client import Counter, CollectorRegistry
>>> reg = CollectorRegistry()
>>> c = Counter('items_total', 'number of items total', registry=reg)
>>> c.labels(first=1, another=2).inc()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Counter' object has no attribute 'labels'
>>>
>>> type(c)
<class 'prometheus_client.core.Counter'>
>>> dir(c)
['__class__', '__delattr__', '__dict__', '__doc__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_reserved_labelnames', '_samples', '_type', '_value', 'collect', 'count_exceptions', 'inc']
```

The Counter object does not seem to have a labels method attached to it. Perhaps some recent changes has affected the application of the decorator that applies it to the metrics?
#99 kind of indicates this same problem but has words relating it to pushgateway.

**Comment by claws** [comment]
I thought it might have something to do with the needing to declare the label names up front (which the docs seem to use) but this does seem to affect it.

``` console
$ python
Python 2.7.12 (v2.7.12:d33e0cf91556, Jun 26 2016, 12:10:39) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from prometheus_client import CollectorRegistry, Counter
>>> reg = CollectorRegistry()
>>> c = Counter('my_requests_total', 'HTTP Failures', ['method', 'endpoint'], registry=reg)
>>> c.labels(method='get', endpoint='/').inc()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: labels() got an unexpected keyword argument 'method'
>>> 
>>> c.labels({'method':'get', 'endpoint':'/'}).inc()
>>> 
```

If I pass the labels as a dict it seems to work.

**Comment by brian-brazil** [comment]
>>> c = Counter('items_total', 'number of items total', registry=reg)

This doesn't have any labels specified

**Comment by claws** [comment]
I think from your comment you are telling me that I'm using it wrong, that I should be declaring up front the set of labels that I am planning to use with a metric (rather than dynamically adding labels to a metric). 

So if I now go and define some labels, exactly as in the example docs, it still doesn't work for me.

``` console
$ python
Python 2.7.12 (v2.7.12:d33e0cf91556, Jun 26 2016, 12:10:39) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from prometheus_client import Counter
>>> c = Counter('my_requests_total', 'HTTP Failures', ['method', 'endpoint'])
>>> c.labels(method='get', endpoint='/').inc()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: labels() got an unexpected keyword argument 'method'
>>> 
```

Perhaps the problem I'm having is purely a docs issue that describes functionality that is not present.

**Comment by yosefy** [comment]
AttributeError: 'Gauge' object has no attribute 'labels'

▽
from prometheus_client import CollectorRegistry, Gauge, push_to_gateway

registry = CollectorRegistry()
g = Gauge('metric', 'help', ['a','b'], registry=registry)
g.set(10)
g.labels('value1', 'value2').inc()
push_to_gateway('127.0.0.1:9091', job='batchA', registry=registry)

gives
Traceback (most recent call last):
  File "test.py", line 5, in <module>
    g.set(12)
AttributeError: '_LabelWrapper' object has no attribute 'set'

if i remove
g.set(12)

it works ok and sets to 1

thanks

**Comment by Pitsubururu** [comment]
Try it:
registry = CollectorRegistry()
g = Gauge('metric', 'help', ['a','b'], registry=registry)
**g.labels('value1', 'value2').set(12)**
push_to_gateway('127.0.0.1:9091', job='batchA', registry=registry)

**Comment by winpat** [comment]
However this doesn't work in conjunction with decoraters.

```python
registry = CollectorRegistry()
g = Gauge('job_last_success_unixtime', 'Last time a batch job successfully finished',['method'],  registry=registry)

@g.labels('POST').time()
def wait():
    sleep(300)

push_to_gateway('pushgateway:9091', job='SomeJob', registry=registry)
```

Traceback:
```python
  File "tmp.py", line 6
    @g.labels('POST').time()
                     ^
SyntaxError: invalid syntax
```

**Comment by brian-brazil** [comment]
Usage questions are best asked on https://groups.google.com/forum/#!aboutgroup/prometheus-users

**Comment by RajshreeSome** [comment]
g = Gauge('node_cpu', 'metrics',"[node]", registry=registry)
when I am trying this i am getting an error
ValueError: Invalid label metric name: [

**Comment by zhaoyuan0218** [comment]
you can try:
g = Gauge('node_load5_norm', 'node_load5_norm', ["host"], registry=registry)
g.labels(hostname).set(value)
push_to_gateway(gateway_uri, job='pushgateway', registry=registry)

then:
metric like this:
node_load5_norm{'host'=xx} 0.1
