### ISSUE TITLE
Add set(>=_value) for Counters

### ISSUE THREAD

**Issue by hynek** [prometheus/client_python#101]
Counters should only increase, but sometimes – when instrumenting third party software like I do right now – I only get snapshots of the counters.  But it’s still totally counters so it would be nice if I could treat them as such.

If you’d agree this is useful, I’d make a quick PR that adds a protected `set()` method that allows to set a counter to `>=self._value`.

**Comment by brian-brazil** [comment]
You should be using a custom collector for interacting with other monitoring systems, not direct instrumentation.

**Comment by hynek** [comment]
Hmmm, I’m not interacting with other monitoring systems, I’m basically just exposing some `SELECT COUNT(*)` as metrics.  Would that fall under the same intended use case?

**Comment by brian-brazil** [comment]
That's interacting with a different monitoring system.

**Comment by juliusv** [comment]
@hynek Yeah, that's the classic exporter use case where you basically don't want to use full Prometheus metrics objects to track your own state, but just proxy third-party state with a throwaway metric during the actual scrape. See https://github.com/prometheus/mysqld_exporter for example. That also contacts MySQL during the scrape and uses ConstMetrics (but in Go) to translate the metrics state.

**Comment by hynek** [comment]
Fair enough, I’ll have a look .  thanks!
