### ISSUE TITLE
Gauge 'track_inprogress' function not working

### ISSUE THREAD

**Issue by damir1407** [prometheus/client_python#1017]
I am using the gauge 'track_inprogress' functionality to track my FastAPI endpoints. I followed the basic examples from the [documentation](https://prometheus.github.io/client_python/instrumenting/gauge/):

from prometheus_client import Gauge
g = Gauge('my_inprogress_requests', 'Description of gauge')

@g.track_inprogress()
def f():
  pass

with g.track_inprogress():
  pass

Neither of these options worked (decorator nor compound statement), as the gauge value never changes. 
I am using the latest 0.20.0 version and within the same endpoint function, I'm using another Counter (just for additional context).

Has anybody encountered a similar issue? Thanks in advance.

**Comment by csmarchbanks** [comment]
This is working for me, one thing is that it will be incredibly hard to see the gauge change if the function is just `pass`, try putting a short sleep there instead. With `pass` the gauge will be incremented and then decremented almost instantaneously and a request to gather the metrics would somehow have to interrupt the work happening in that thread.

**Comment by damir1407** [comment]
Hi @csmarchbanks, thanks for the response. The function is not just `pass`. For example, when I use something similar for `Counter` such as with c.count_exceptions() in the same function, it works. Also, I am observing the 'track_inprogress' in a time series graph so I should see a value change even if it's for a short amount of time. I also tried putting a short sleep but nothing different happened.
