### ISSUE TITLE
Exclude PID labels in multiprocess mode

### ISSUE THREAD

**Issue by Azmisov** [prometheus/client_python#1033]
I feel adding PID's to the label set violate the recommendations given here: https://prometheus.io/docs/practices/instrumentation/#do-not-overuse-labels. Anyway to redesign the client to not include PID in the labels? E.g. why not just have PID in the file names in the multiprocess directory? If nothing else, a caveat in the docs mentioning multiprocess mode is only recommended for <= 100 long running subprocesses.

**Comment by csmarchbanks** [comment]
Have you tried using `multiprocess_mode` mentioned in the [docs](https://prometheus.github.io/client_python/multiprocess/)? That will allow you to choose the proper aggregation to get rid of the PID label. For gauges it is not possible to know what the proper aggregation is ahead of time.

**Comment by Azmisov** [comment]
Ah interesting. Guess I didn't read the docs closely enough.
