### ISSUE TITLE
Empty samples is bug？ Help Me

### ISSUE THREAD

**Issue by worker24h** [prometheus/client_python#1052]
scare noting samples and pushed to pushgateway when a system starting，this is bug？  I'm not sure  @csmarchbanks 

![image](https://github.com/user-attachments/assets/1cd159a2-c868-460b-86d0-66b74f4a5187)

**Comment by csmarchbanks** [comment]
This is by design. The metric still exists but is empty which I believe is the correct behavior. Did anything break?
