### ISSUE TITLE
How to remove counters and labels from web server export

### ISSUE THREAD

**Issue by Kaydannik** [prometheus/client_python#108]
Hello
Could you please explain me how to delete some counters/labels from output?
For example i created a gauge 
g =  Gauge('superapp_performance', 'SuperDuper app RPS gauge',
                                                   ['instance','location','country'])
Then i updating it with info from apps:
g.labels(instance_id,location_name,country_name).set(hugeRPS)

And at some point i don't have this instance anymore, and i want to delete information about it. How to do it ? 
Thanks

**Comment by brian-brazil** [comment]
It sounds like you should be using a custom collector rather than direct instrumentation.

**Comment by DanielLuu** [comment]
Could you explain how a custom collector would work in this case? Do I have to add a method to remove metrics?

**Comment by axd1967** [comment]
could this be solved by adding rules to an `alertmanager` instead?
