### ISSUE TITLE
Add support for Tornado based exporter

### ISSUE THREAD

**Issue by yuvipanda** [prometheus/client_python#114]
We're considering using this in the [Jupyter](https://jupyter.org/) project, and would love for it to have a Tornado exporter similar to the twisted one.

**Comment by yuvipanda** [comment]
If y'all are willing, I'll send a PR when we start implementing it.

**Comment by brian-brazil** [comment]
I don't think it's a s popular, but I'm willing to add it if doesn't require anything silly.
