### ISSUE TITLE
Multiprocessing works differently in Linux and Windows

### ISSUE THREAD

**Issue by volkovandr** [prometheus/client_python#121]
Hi
That's my small example script. Create a subdirectory "metrics" in the folder from you are running the script and set the environment variable.
```
#!/usr/bin/python
'''
This is just an example of how to use prometheus_client in multiprocessing application
'''
import os
if 'prometheus_multiproc_dir' not in os.environ:
    os.environ['prometheus_multiproc_dir']='metrics'

from prometheus_client import Counter
from prometheus_client import start_http_server
from prometheus_client import CollectorRegistry
from prometheus_client.multiprocess import MultiProcessCollector
from prometheus_client import core
from multiprocessing import Pool


def worker(n):
    counter = Counter('counter', 'counter', registry=None)
    counter.inc()

def main():
    print("Main PID", os.getpid())
    clear_metrics_dir()
    registry = CollectorRegistry()
    MultiProcessCollector(registry)
    core.REGISTRY = registry
    start_http_server(8000)

    p = Pool(processes=10)
    p.map_async(worker, range(300000))

    p.close()
    p.join()
    print(registry.get_sample_value('counter'))


def clear_metrics_dir():
    dir = os.getcwd()
    os.chdir(os.environ['prometheus_multiproc_dir'])
    [os.remove(file) for file in os.listdir()]
    os.chdir(dir)


if __name__ == '__main__':
    main()

```
If I run this in Windows I got this output:
```
Main PID 27372
300000.0
```
and there are 10 files in the metrics subdirectory.

But on Linux the output is different:
```
Main PID 24671
42961.0
```
And there is only one file in the directory.

I'm not quite sure but my guess is the following:
In the core.py at lines 441-444 the variable _ValueClass is initialized:
```
if 'prometheus_multiproc_dir' in os.environ:
    _ValueClass = _MultiProcessValue()
else:
    _ValueClass = _MutexValue
```
And then that class is instantiated and it creates the files where the metrics data will be stored. 
The class itself is created in the function _MultiProcessValue() and it uses os.getpid() as a default value for the argument.
In Windows when you start another processes with _multiprocessing_ your main module is reloaded for each of the processes. And the prometheus_client library is also reloaded and the class is constructed for each of the new process.
In Lunux the module is loaded only once and therefore the class is created also only once. 
All that makes the library write all the metrics of all the processes to the same file on Linux! That makes the metrics basically wrong, and in the worst case the file got corrupted and the HTTP server can not read from the file. 
Though the stuff seems to work well if the load on the processes is small. E.g. if you put _sleep_ in the worker function and reduce the number of cycles it can (sometimes) work fine.

If i change the core.py in this way, it works fine on both Linux and Windows (lines 395-406):
```
def _MultiProcessValue(__pid=os.getpid()):
    files = {}
    files_lock = Lock()

    class _MmapedValue(object):
        '''A float protected by a mutex backed by a per-process mmaped file.'''

        _multiprocess = True

        def __init__(self, typ, metric_name, name, labelnames, labelvalues, multiprocess_mode='', **kwargs):
            pid = os.getpid()
            if typ == 'gauge':
```
but then the unit tests will most probably fail.

**Comment by brian-brazil** [comment]
It's documented that "Gunicron's preload_app feature is not supported", which is what you're effectively running in to. The new process currently needs to reload all Python modules for it to work.

The difference you're seeing is likely due to Python implementation differences across platforms, as Windows doesn't support `fork`.
