### ISSUE TITLE
Histogram for Event listeners 

### ISSUE THREAD

**Issue by naveensrinivasan** [prometheus/client_python#124]
I am new to this and I don't know how to solve this.

We are using [locust.io](locust.io) for our testing and we want to add prometheus for our metrics. Locust provides events [http://docs.locust.io/en/latest/extending-locust.html](http://docs.locust.io/en/latest/extending-locust.html) which has  request type , name, time and length for all methods. Here is the sample

``` python

from locust import events

def my_success_handler(request_type, name, response_time, response_length, **kw):
    print "Successfully fetched: %s" % (name)

events.request_success += my_success_handler
```

We would like to use this functionality to provide histogram data for our metrics. But one thing we realized is that we couldn't provide labels to histogram to identify which request is it for.

Is there any way we could achieve this instead of creating an histogram for each method. We have 10's of REST API calls we test with locust.

Thanks

**Comment by brian-brazil** [comment]
I'm not sure what you're really asking here. It's up to you to provide the label values you want.

**Comment by naveensrinivasan** [comment]
Can I add labels in the Historgram and Summary? If it is possible, can you please share an example?

Thanks

**Comment by brian-brazil** [comment]
They work the same as the others https://github.com/prometheus/client_python#labels

**Comment by naveensrinivasan** [comment]
Can I do this?
`            histogram.labels(method='get',endpoint='isActive').time() `

Can I add labels to Histogram's?

**Comment by brian-brazil** [comment]
Yes, that'll work in a context manager.

**Comment by naveensrinivasan** [comment]
Can you please show me an example?

**Comment by brian-brazil** [comment]
Usage questions are best asked at https://groups.google.com/forum/#!aboutgroup/prometheus-users
