### ISSUE TITLE
Adding a custom path to the http server for health checks

### ISSUE THREAD

**Issue by s-j** [prometheus/client_python#125]
Hi guys, I am using the library to implement a grpc service running on mesos (via aurora) and using the prometheus port to handle health checks as well as exporting metrics. I wonder therefore if there is an easy way to add a new path to the http server used within. In other words, I want port:/internal/status or similar to return empty HTTP:OK without any metrics.

Thanks and cheers,
Simon

**Comment by brian-brazil** [comment]
The included http server is just to get you going quickly. You're free to implement your own, and in general I'd expect most users to hook in the handler to your existing http server rather than using `start_http_server`.

**Comment by s-j** [comment]
Great, thanks!

I'll try something like the following:

```
class HealthRequestHandler(BaseHTTPRequestHandler):
    def do_GET(self):
        self.send_response(200)
        self.send_header('Content-type', 'text/html')
        self.end_headers()
        if self.path == "/internal/status":
            self.wfile.write(bytes("{\"status\":true}", "utf8"))
        else:
            self.wfile.write(generate_latest(core.REGISTRY))
        return

    def log_message(self, format, *args):
        return


def start_health_server(port, addr=''):
    class HealthRequestServer(threading.Thread):
        def run(self):
            httpd = HTTPServer((addr, port), HealthRequestHandler)
            httpd.serve_forever()
    t = HealthRequestServer()
    t.daemon = True
    t.start()
```

**Comment by analytically** [comment]
Would be handy indeed, for quick and easy metrics servers not having to use /metrics as their health check.
