### ISSUE TITLE
Non-gunicorn multiprocessing (mostly questions)

### ISSUE THREAD

**Issue by tlc** [prometheus/client_python#130]
I am trying to use multiprocessing support even though I am not using gunicorn.  

I have a master proc calling multiprocessing.Process() to create workers.  (I'm forking but not execing.)

All my mmap files in `prometheus_multiproc_dir` have the parent process id in the filename.  I *believe* this is not as intended and means that stats are being aggregated as they're saved instead of when they're served.  (A performance hit.)

I will try to import prometheus_client after the fork -- and in another file.  But that file will be imported...  Do the python imports make it impossible for me to have different global _ValueClass's without an exec or monkeying in prometheus_client?

Also, BTW, there is still a reference to shelve in the source.

**Comment by brian-brazil** [comment]
We don't currently support multiprocessing, as it doesn't work the way we expect gunicorn-like things to.

**Comment by dozer47528** [comment]
@brian-brazil  I have the same problem, any plan to support uwsgi?

**Comment by brian-brazil** [comment]
Can uwsgi start a brand new process for requests?

We currently support a partiuclar model of using multiple processes, not particular libraries.

**Comment by dozer47528** [comment]
I use uwsgi to start my application

` uwsgi --http-socket :8000 --master --workers 4 --enable-threads --threads 10 --wsgi-file server/wsgi.py`

There is one master process and four worker process.

But the `client_python` only created one file with the pid of master process.

**Comment by brian-brazil** [comment]
Unless you can find a way to make it fork&exec each worker, it's not going to work currently.

**Comment by banteg** [comment]
uWSGI config example:
```ini
[uwsgi]
http-socket = :8000
enable-threads = yes
lazy-apps = yes
processes = 4
wsgi = app:app
env = prometheus_multiproc_dir=multi
```

**Comment by esseti** [comment]
@banteg can you provide a  full example. this is the uwsgi ini file, but how/where do you start the wsgi_server? what port?

**Comment by ecksun** [comment]
> We don't currently support multiprocessing, as it doesn't work the way we expect gunicorn-like things to.

> We currently support a partiuclar model of using multiple processes, not particular libraries.

There is not much documentation about what is and is not supported, nor what model you are refering to, could you expand on that @brian-brazil ?

I have a kafka multiprocess worker which I want to export metrics from. The code below appears to work (I intend to use systemd ExecStopPost to cleanup afterwards), is there something I'm missing?

```python
def start_prometheus_server():
    class MetricsHandler(BaseHTTPRequestHandler):
        def do_GET(self):
            if self.path == '/metrics':
                self.respond_metrics()
            else:
                self.respond_not_found()

        def respond_not_found(self):
            self.send_response(404)
            self.send_header('Content-Type', 'text/plain')
            self.end_headers()
            self.wfile.write(b'Use /metrics\n')

        def respond_metrics(self):
            registry = CollectorRegistry()
            multiprocess.MultiProcessCollector(registry)
            data = generate_latest(registry)
            self.send_response_only(200)
            self.send_header('Content-Type', CONTENT_TYPE_LATEST)
            self.send_header('Content-Length', str(len(data)))
            self.end_headers()
            self.wfile.write(data)

    class PrometheusMetricsServer(threading.Thread):
        def run(self):
            httpd = HTTPServer(('', 8002), MetricsHandler)
            httpd.serve_forever()

    t = PrometheusMetricsServer()
    t.daemon = True
    t.start()
```

**Comment by brian-brazil** [comment]
That's just the exposition part which will work anywhere (doesn't even have to be in a related process). The problem is the instrumentation part.

**Comment by ecksun** [comment]
> That's just the exposition part which will work anywhere (doesn't even have to be in a related process). The problem is the instrumentation part.

Okay, what does that mean for me, will all my counters be wrong? Is it possible to get it to work currently at all?

**Comment by brian-brazil** [comment]
If you're using multiprocessing it won't work currently.

**Comment by ecksun** [comment]
> If you're using multiprocessing it won't work currently.

Alright, thats very sad to hear :(

In which manners will it not work and why not? What changes are required to fix that?

**Comment by brian-brazil** [comment]
See #127

**Comment by ecksun** [comment]
Is it correct to assume that it would work to simply create multiple python processes (in my case I would use systemd templates) that share the same metrics dir?

Also, sorry for continuing discussion on this closed issue, I feel there is a lack of documentation around what you can and can't do with regards to multiple processes with the python client, and more info in this issue would have helped me.

**Comment by brian-brazil** [comment]
This is already being discussed on the other issue, so I consolidated.
