### ISSUE TITLE
Outdated docstring for passing labels as dict

### ISSUE THREAD

**Issue by antialiasis** [prometheus/client_python#136]
[This commit](https://github.com/prometheus/client_python/commit/882d5769da695bee7be5a9806b4b1d4762e23a8a) removes support for passing a dictionary to `labels`. However, the docstring for `labels` still documents passing a dict, rather than keyword arguments. I spent unnecessarily long puzzling over an "Incorrect label count" error from a library that appeared to be using the method as documented.

**Comment by brian-brazil** [comment]
Thanks for spotting this, would you like to send a PR?

**Comment by antialiasis** [comment]
Okay, submitted one [here](https://github.com/prometheus/client_python/pull/137).
