### ISSUE TITLE
`Histogram.time` reuses the same `_HistogramTimer` instance for multiple requests when used as a decorator

### ISSUE THREAD

**Issue by obsoleter** [prometheus/client_python#140]
`Histogram.time` reuses the same `_HistogramTimer` instance for multiple requests when used as a decorator.  This results in incorrectly timed requests.  A simple example app bears this out:

```
import time

from flask import Flask, make_response
from werkzeug.wsgi import DispatcherMiddleware
from prometheus_client import make_wsgi_app, Histogram


app = Flask(__name__)
LATENCY = Histogram('request_latency_seconds', 'Tracking response times')


@LATENCY.time()
@app.route('/')
def index():
    time.sleep(2)
    return make_response('hello')


metrics_app = make_wsgi_app()
application = DispatcherMiddleware(app, {
    '/app': app,
    '/metrics': metrics_app
})


if __name__ == '__main__':
    import waitress
    waitress.serve(application, threads=50)
```

With this app, no requests should ever end up in any of the buckets below 2.5 seconds.  And yet many do.

**Comment by brian-brazil** [comment]
That would be bad, how do you suggest fixing this?

**Comment by obsoleter** [comment]
I mistyped in the details of the pull request.  It will provide the same behavior as using `Histogram.time()` as a context manager (with block).

**Comment by brian-brazil** [comment]
Thanks, could you add a unittest and fix the other two?

**Comment by brian-brazil** [comment]
I can't reeproduce, so closing.
