### ISSUE TITLE
"Historgam" fails with Python 2.7.6

### ISSUE THREAD

**Issue by d3QUone** [prometheus/client_python#144]
Hello!

I'm running `prometheus_client==0.0.19` with Flask. As far as I understand the source code of the client, this registers every "Metric" in default `prometheus_client.core.REGISTRY`. So in my app I do the following:
```python
def set_monitoring(self):
    self.server_summary = Histogram('main_flask_server', 'All requests timing', ['instance', 'endpoint'])
    self.server_errors = Histogram('main_flask_server_errors', 'Bad requests', ['instance', 'endpoint'])

...

app. set_monitoring()

...

app.server_summary.labels('i1', key).observe(dt_ms)

...

push_to_gateway(gateway=gateway, job='flask_meme', registry=REGISTRY)
```

On my local machine (MacOS Sierra, Python 2.7.12) everything is fine and works perfectly. But on the Ubuntu server with Python 2.7.6 I got the exception on startup. Traceback:
```python
unable to load app 0 (mountpoint='') (callable not found or import error)
Traceback (most recent call last):
  File "/home/vladimir/membot/imager/server.py", line 104, in uwsgi_app
    return get_app(conf=conf)
  File "/home/vladimir/membot/imager/server.py", line 95, in get_app
    flask_app.set_monitoring()
  File "/home/vladimir/membot/imager/server.py", line 46, in set_monitoring
    self.server_summary = Histogram('main_flask_server', 'All requests timing', ['instance', 'endpoint'])
  File "/usr/local/lib/python2.7/dist-packages/prometheus_client/core.py", line 556, in init
    registry.register(collector)
  File "/usr/local/lib/python2.7/dist-packages/prometheus_client/core.py", line 54, in register
    'in CollectorRegistry: ' + name)
ValueError: Timeseries already present in CollectorRegistry: main_flask_server_bucket
```

What am I doing wrong? Why Timeseries is already present in CollectorRegistry?

**Comment by brian-brazil** [comment]
Only one of a metric can exist in a registry, and you presumably have more than one object. Given you're using the pushgateway for a batch job, you should be using a custom registry for this.

**Comment by d3QUone** [comment]
But it raises on the first metric
And it also works on the local computer

**Comment by d3QUone** [comment]
Actually I get the same error with this:
```python
def set_monitoring(self):
    self.prometheus_registry = CollectorRegistry()
    self.server_summary = Histogram('main_flask_server', 'All requests timing', ['instance', 'endpoint'])
    self.prometheus_registry.register(self.server_summary)

app.server_summary.labels('i1', key).observe(dt_ms)

push_to_gateway(gateway=gateway, job='flask_meme', registry=app.prometheus_registry)
```

Could you please help with this case? :)

**Comment by brian-brazil** [comment]
It's best to take support questions like these to https://groups.google.com/forum/#!aboutgroup/prometheus-users

**Comment by d3QUone** [comment]
Sorry, but I'm using the README, and getting this error. Could you fix the documentation then? 

Section "Exporting to a Pushgateway"
```python
g = Gauge('job_last_success_unixtime', 'Last time a batch job successfully finished', registry=registry)
```
the `registry=registry` param is missing in metric object

`instance_ip_grouping_key` is missing

**Comment by RajshreeSome** [comment]
Even I am getting the same error.While I run the application I dont get any error.But when I am trying contanerize the my app.It is throwuing
File "test_pushgateway.py", line 5, in <module>
    push_to_gateway('localhost:9091', job='batchA', registry=registry1)
  File "/usr/local/lib/python2.7/site-packages/prometheus_client/exposition.py", line 198, in push_to_gateway
    _use_gateway('PUT', gateway, job, registry, grouping_key, timeout, handler)
  File "/usr/local/lib/python2.7/site-packages/prometheus_client/exposition.py", line 265, in _use_gateway
    headers=headers, data=data)()
  File "/usr/local/lib/python2.7/site-packages/prometheus_client/exposition.py", line 133, in handle
    resp = build_opener(HTTPHandler).open(request, timeout=timeout)
  File "/usr/local/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/local/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/local/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python2.7/urllib2.py", line 1228, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/local/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 99] Cannot assign requested address>

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by patrickleet** [comment]
> the whole community can benefit from the answers provided.

except those who look on github

**Comment by adriangay** [comment]
searching for ```<urlopen error [Errno 99] Cannot assign requested address>``` in the prmetheus-users-mailing list as suggested by @brian-brazil brings up nothing!

**Comment by brian-brazil** [comment]
Random github issues are not a good place for support requests, I'm locking this now.
