### ISSUE TITLE
generate_latest() for MultiProcessing writes both the MultiProcess Metrics and per Process Metrics

### ISSUE THREAD

**Issue by mariamsawires** [prometheus/client_python#145]
Hi,

I guess the title says it all but using Gunicorn multiprocessing environment and creating a CollectorRegistry() that is passed into MultiProcessorCollector()... then doing generate_latest() on that registry, I get both keys for MultiProcess metrics and per Process Metrics. However, I would like to only see the MultiProcess Metrics and ignore the per Process Metrics. Is there a way to do that?

Thanks,
Mariam

**Comment by brian-brazil** [comment]
Usage questions are best asked on https://groups.google.com/forum/#!aboutgroup/prometheus-users

It sounds like you're using the default registry rather than a custom registry as per the docs.
