### ISSUE TITLE
(feat) decorator labels

### ISSUE THREAD

**Issue by sstarcher** [prometheus/client_python#157]
The setup of using `@REQUEST_TIME.time()` is nice.  would it make sense to extend it to support labels so you could have different metrics for different method calls / http calls.

**Comment by brian-brazil** [comment]
Do you have a suggestion for how to implement this? I've not figured out why it doesn't work as-is.

**Comment by sstarcher** [comment]
@brian-brazil I have not had a chance to dig into the code to see how it's implemented.  So your saying currently as the code is written it should be adding labels for the decorator?

**Comment by brian-brazil** [comment]
Labels are orthogonal to the decorator. I haven't figured out the bit of Python semantics that prevents it from working in the way you'd expect.

**Comment by luafran** [comment]
If you can live with this, a workaround is to instantiate a Histogram object with label values and then call time() on this object. Like this:

```
REQUEST_TIME = Histogram('http_request_duration_seconds', 'help', ['method', 'endpoint', 'service'])
REQUEST_TIME_GET_TEST = REQUEST_TIME.labels(method='GET', endpoint="test", service='webapp-python')

@app.route('/test/<time_ms>', method='GET')
@REQUEST_TIME_GET_TEST.time()
def get_test(time_ms='0'):
    logger.info('Processing GET /test/'+time_ms)

    time_to_sleep = int(time_ms) / float(1000)
    time.sleep(time_to_sleep)

    retdata = {
        "status": "OK"
    }

    return retdata
```

The details after a not so deep analysis of the issue:
When you create a Histogram (or any other metric) with label names like this:

`REQUEST_TIME = Histogram('http_request_duration_seconds', 'help', ['method', 'endpoint', 'service'])`
Instead of a Histogram object, what you get is a _LabelWrapper object.

Since you need a Histogram object to call the time() decorator factory, the workaround is to get back a Histogram object calling labels() on the _LabelWrapper object before using the decorator.

**Comment by mciura** [comment]
FWIW, this works for me:
```python
from prometheus_client.core import _LabelWrapper

def time_monkey_patch(self, **kwargs):
    return self.labels(**kwargs).time()
_LabelWrapper.time = time_monkey_patch

REQUEST_TIME = Histogram(
    'http_request_duration_seconds', 'help', ['method', 'endpoint', 'service'])

@REQUEST_TIME.time(method='GET', endpoint='test', service='webapp-python')
def handler():
    pass
```
How about adding such a `time()` method to `_LabelWrapper`?

**Comment by brian-brazil** [comment]
That'd be a layering violation, _LabelWrapper isn't meant to know what's underneath it.

**Comment by mciura** [comment]
@brian-brazil Fair enough.  How do you feel about forwarding all unknown calls to the wrapped class?  Although the example below works only for methods without arguments like `time()`, by introducing special `kwargs` not meant for consumption by `labels()`, we may also handle methods with arguments.
```python
def __getattr__(self, name):
    def wrapper(*args, **kwargs):
        method = getattr(self.labels(*args, **kwargs), name)
        if callable(method):
            return method()
    return wrapper
```

**Comment by brian-brazil** [comment]
I'm not sure about that, some of the functions like `inc()` take an argument so I can see that leading to more confusing errors.

**Comment by drfloob** [comment]
Reviving this thread ... it seems Guido had "a gut feeling" in disallowing the kind of decorator syntax that would allow method chaining in decorators https://mail.python.org/pipermail/python-dev/2004-August/046711.html. Mentioned in PEP 318

I hacked a fairly non-pythonic workaround:

```python
engine_process_message_timer = REQUEST_TIME.labels(method="engine_process_message")
@engine_process_message_timer.time()
def my_func(...):
    pass
```

**Comment by brian-brazil** [comment]
Yeah, that's what I think everyone has to do unfortunately.
