### ISSUE TITLE
can decorator work with push gateway together

### ISSUE THREAD

**Issue by QingsongYao** [prometheus/client_python#160]
I like the decorator to add in a method, and I want each time, the metric changed (when the method was called),  the system automatically called a method to push the current metric to push gateway, I wonder how easy to implement this?

**Comment by brian-brazil** [comment]
That is not what the pushgateway is for, see https://prometheus.io/docs/practices/pushing/ 

Usage questions are best asked at https://groups.google.com/forum/#!aboutgroup/prometheus-users
