### ISSUE TITLE
Implementing quantiles for Summary: exact or approximate?

### ISSUE THREAD

**Issue by cubranic** [prometheus/client_python#162]
@brian-brazil welcomed PRs implementing quantiles for summaries in #92. I have a simplistic implementation that calculates quantiles exactly, but this requires keeping around all observations within the sliding window. I noticed that all other clients use Cormode and Muthukrishnan's [approximate algorithm](http://www.cs.rutgers.edu/~muthu/bquant.pdf). There is a Python package on [pyPI](https://pypi.python.org/pypi/quantile-python) that implements this algorithm. Would you prefer that it be used instead? I haven't used it myself, and it's marked in alpha status, but then again, so is the one used by the Ruby client.

**Comment by brian-brazil** [comment]
We should keep consistency with the other implementations, and avoid dependencies in the core.

**Comment by cubranic** [comment]
I take your comment about consistency with other implementations to mean that Python client should also use approximate stream quantiles? But I don't understand your comment about avoiding dependencies: Go and Ruby clients both use an external package for that algorithm. Can you clarify please?

**Comment by brian-brazil** [comment]
> I take your comment about consistency with other implementations to mean that Python client should also use approximate stream quantiles?

Yes.

> But I don't understand your comment about avoiding dependencies: Go and Ruby clients both use an external package for that algorithm. Can you clarify please?

In the client I maintain I try to keep no dependencies for the core components, as a version conflict in something like this could be very problematic.

**Comment by cubranic** [comment]
Well, version requirements can be pinned. But OK, I can include the algorithm implementation in this source tree.
