### ISSUE TITLE
Readme file does not make it clear that you also need to run Prometheus itself

### ISSUE THREAD

**Issue by saoili** [prometheus/client_python#164]
Working through the readme file here it's not clear that you need to run Prometheus itself as well. On reflection it's obvious, but it wasn't obvious to me, so maybe it won't be for others? I would just make a pull request on the readme but I'm not entirely should what should be said.

**Comment by brian-brazil** [comment]
Neither goes it make clear that you need Python :)

I don't think it'd be sane to exhaustively list every step to using every Prometheus component.

**Comment by saoili** [comment]
Could we at least change 'The official Python 2 and 3 client for Prometheus.' to 'The official Python 2 and 3 client for use with Prometheus.' ? I think it would make a big difference.

**Comment by brian-brazil** [comment]
I'm not seeing a difference there. Being a client implies that there's a server.

It's also not technically required to be running Prometheus (https://github.com/prometheus/client_python/#graphite).
