### ISSUE TITLE
Counter with labels does not have inc

### ISSUE THREAD

**Issue by marcpawl** [prometheus/client_python#168]
Please give a an example on how to use counters with labels.

I have:
  counters[key]= Counter(metric, metric,
  labelnames=['client'], labelvalues=[ data['client'] ])
  print counters[key]
  print dir(counters[key])
  counters[key].inc(diff)

 <prometheus_client.core._LabelWrapper object at 0xcf8ed0>
 ['__class__', '__delattr__', '__dict__', '__doc__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_kwargs', '_labelnames', '_lock', '_metrics', '_name', '_samples', '_type', '_wrappedClass', 'collect', 'describe', 'labels', 'remove']

    counters[key].inc(diff)
| AttributeError: '_LabelWrapper' object has no attribute 'inc'
 <prometheus_client.core._LabelWrapper object at 0xcf8ed0>

**Comment by brian-brazil** [comment]
Usage questions are best asked on https://groups.google.com/forum/#!forum/prometheus-users
