### ISSUE TITLE
Purge metrics samples

### ISSUE THREAD

**Issue by jkemp101** [prometheus/client_python#174]
I would like to purge all samples for a metric.  As far as I can tell the best way would be to iterate over the `_LabelWrapper` `_samples` and remove each sample.  Should `_samples` be renamed to `samples`?  Add a purge method?

My particular use case is to stop exporting some metrics when an error condition occurs.  I don't want to keep exporting a value that is not able to be determined.  For instance I might export values from redis and the redis instance is no longer accessible.

**Comment by brian-brazil** [comment]
You should use a custom collector in that case rather than direct instrumentation.

**Comment by jkemp101** [comment]
I'll give that approach a try.  Thanks.

**Comment by axd1967** [comment]
related : https://github.com/prometheus/client_python/issues/174
