### ISSUE TITLE
Problem with Gauge class

### ISSUE THREAD

**Issue by shineygreen** [prometheus/client_python#180]
In Python 2.7.5 when one passes labelnames as part of the Gauge constructor, a _LabelWrapper class is returned instead of a Gauge. Is this the expected behavior?

   \>\>\> from prometheus_client import Gauge
   \>\>\> fred=Gauge('one', 'A one')
   \>\>\> fred.\_\_class\_\_.\_\_name\_\_
   'Gauge'
   \>\>\> fred=Gauge('two', 'A two', ['numbers', 'integer'])
   \>\>\> fred.\_\_class\_\_.\_\_name\_\_
   '_LabelWrapper'

**Comment by brian-brazil** [comment]
Yes, this is how Labels work internally.

**Comment by shineygreen** [comment]
You don't think it is counter-intuitive for a Gauge constructor to return something other than a Gauge class or a Gauge subclass?

**Comment by brian-brazil** [comment]
Not particularly, it follows the documented API.

**Comment by shineygreen** [comment]
Thanks for the quick response, would you give me a pointer to the API documentation?

**Comment by brian-brazil** [comment]
https://github.com/prometheus/client_python#instrumenting
