### ISSUE TITLE
Issue #27 No module name resource, still there

### ISSUE THREAD

**Issue by vikramrajsitpal** [prometheus/client_python#183]
Hello,
I was just using Exscript on **windows 10** and turns out this issue is still there. Windows 7 did NOT throw any such error though. Can I please get an insight into this issue?
I could successfully install the module on Win10 but on running my first test, this issue popped up.

**Comment by vikramrajsitpal** [comment]
I am using the latest version of exscript which is available via pip on Aug 01, 2017 .
using Python 2.7.13

**Comment by brian-brazil** [comment]
Which exact version of the python client are you using?

**Comment by vikramrajsitpal** [comment]
@brian-brazil I am using Exscript 2.3.2

**Comment by brian-brazil** [comment]
That exception is not from the Prometheus python client.

**Comment by vikramrajsitpal** [comment]
Well, @brian-brazil I was hoping you could help me out. What can I do ?
As I mentioned, Win7 does not have any such problem, Win10 has it, I would really appreciate any help.

**Comment by brian-brazil** [comment]
This is not a Prometheus problem, I'm afraid I cannot help you.
