### ISSUE TITLE
Including timestamp in metric

### ISSUE THREAD

**Issue by jclcntl** [prometheus/client_python#185]
Hello,

I'd like to include the timestamp in the metric according to the Prometheus documentation: https://prometheus.io/docs/instrumenting/exposition_formats/

```
metric_name [
  "{" label_name "=" `"` label_value `"` { "," label_name "=" `"` label_value `"` } [ "," ] "}"
] value [ timestamp ]
```

I'd like that feature for the following reason: Some exporters take a while to gather certain information. Therefore I would like to run them asynchronously, not only when the endpoint is scraped. To guarantee that the metrics are as accurate as possible, I'd like to include the timestamp with the metric.

Currently, I don't think this is possible.

Thanks

**Comment by brian-brazil** [comment]
This isn't currently possible, but a patch to add it would be accepted. #176 is related.

Note that using the timestamp is only recommended when pulling data from another monitoring system that has timestamps, and not when caching.

**Comment by erikdsjostrom** [comment]
Has there been any change in regards to this issue? I'd also like to parse timestamps.

**Comment by jclcntl** [comment]
What's the timeframe for the openmetrics work? I see that on the roadmap it says near future, but can you share more details? Thank you!

**Comment by brian-brazil** [comment]
It'll likely be quite soon. However based on how you have described your use case, you should not use timestamps.

**Comment by jclcntl** [comment]
> Note that using the timestamp is only recommended when pulling data from another monitoring system that has timestamps, and not when caching.

**Comment by LukeDefeo** [comment]
Hi i could use this too. my use case is using https://github.com/GoogleCloudPlatform/k8s-stackdriver/tree/master/prometheus-to-sd to push metrics in prometheus format to stackdriver. Strackdriver needs to know what time range the counters are from / to for them to work

**Comment by hollodotme** [comment]
I have question regarding the timestamp value type. The [prometheus docs](https://prometheus.io/docs/instrumenting/exposition_formats/#comments-help-text-and-type-information) say:

>The timestamp is an int64 (milliseconds since epoch, i.e. 1970-01-01 00:00:00 UTC, excluding leap seconds), represented as required by Go's ParseInt() function.

Looking at the [python parser and its tests](https://github.com/prometheus/client_python/blob/master/tests/openmetrics/test_parser.py#L367) floats (I think microseconds) are used for the timestamps. 

What is the right format / type? Am I missing something?

**Comment by brian-brazil** [comment]
It's seconds for openmetrics.

**Comment by rabbl** [comment]
@brian-brazil since what version? in V2.1.0 prometheus parses the date correctly only with (unix timestamp (s) * 1000).

**Comment by PravinRanjan10** [comment]
Just convert timestamp value to ms(miliseconds). For example:

timestamp = int(float(datetime.datetime.now().timestamp()) * 1000)
