### ISSUE TITLE
Process metrics in multi-process mode

### ISSUE THREAD

**Issue by mightyguava** [prometheus/client_python#186]
It looks like in multi-process mode, the process collector no longer gets used by default, which makes sense since there are multiple processes to collect.

Can we use `resource.getrusage` with `resource.RUSAGE_BOTH` for information here? Or does this not work with processes created by gunicorn? I'm not familiar with measuring Python resource usage at all so just let me know if this sounds stupid.

**Comment by brian-brazil** [comment]
Per the docs (https://github.com/prometheus/client_python#multiprocess-mode-gunicorn) this doesn't work. Nor is it really sane to try and make it work.

**Comment by mightyguava** [comment]
Thanks for the quick reply! What's wrong with using `resource.getrusage`? The doc just says `Custom collectors do not work (e.g. cpu and memory metrics)`

**Comment by brian-brazil** [comment]
It only returns the information for the current process, which isn't sufficient.

**Comment by akshat-g** [comment]
@brian-brazil  - Hey so I implemented application level metrics for django application running in a multi process uwsgi server. All the metrics from different processes are getting collected in the directory created and added to the env(prometheus_multiproc_dir).

However between two deployments, as mentioned in the official docs, I delete this directory and create fresh again.
Now application level metrics create such files - counter_13737.db, counter_1373.db. Now after flushing the directory between deployments, these files also get deleted. But while collecting metrics after a fresh deployment, I get errors like - No such file or directory: /path_to_dir/counter_13737.db

Why would fresh deployment try to write/read to/from old files. How can I fix this issue? Can you please suggest something here?

Thanks in advance

**Comment by brian-brazil** [comment]
Are you sure you completely stopped the application before deleting the files?

**Comment by akshat-g** [comment]
yes I completely stopped the application running under supervisor by stopping the supervisor itself. I made sure before deleting directory and underlying files, that no uwsgi process was live. After that I deleted the directory.

**Comment by brian-brazil** [comment]
I'm not sure what's going on there. Could something be deleting the files on you?

**Comment by marksteward** [comment]
> After that I deleted the directory.

Only a guess, but did you recreate the directory again? client_python doesn't create it automatically.

**Comment by loehnertz** [comment]
@akshat-g 
You probably got it sorted by now but for other people that arrive in this thread:
My mistake was just putting the temporary directory into the root of my project whereas obviously, Gunicorn or uwsgi will look for it in the directory of the application you are starting (usually a Python module). So check the path of the environment variable again or move the directory accordingly.
