### ISSUE TITLE
MetricsHandler support multiprocessing

### ISSUE THREAD

**Issue by zoidbergwill** [prometheus/client_python#194]
I added this to the default `MetricsHandler` recently:

```
        if 'prometheus_multiproc_dir' in os.environ:
            multiprocess.MultiProcessCollector(registry)
```

Not sure if it's worth making a PR for it?

**Comment by brian-brazil** [comment]
This would be incorrect, as you usually want to use this only with a custom registry.

**Comment by zoidbergwill** [comment]
So is it usually incorrect or always incorrect?

Do we usually wanna use the `MetricsHandler` or `MultiProcessCollector` with a custom registry, should I not be using either of them?

Could you elaborate a little? Sorry, I haven't used the Prometheus Python client much yet.

**Comment by brian-brazil** [comment]
Usually incorrect. This couldn't be a default unless it was always correct.

> Do we usually wanna use the MetricsHandler or MultiProcessCollector with a custom registry, should I not be using either of them?

You should always use them that way.
