### ISSUE TITLE
Mechanism for coalescing prometheus metrics from several processes on one machine to a single HTTP server on that machine

### ISSUE THREAD

**Issue by DanGoldbach** [prometheus/client_python#198]
Hi,

We run a handful of prometheus-monitored Python processes on our machines. The processes are not workers; they have distinct tasks, distinct metrics, and each is started by systemd.  We would like to export all metrics to a single HTTP server, rather than hosting one server per process (easily achieved by calling start_http_server in each process).

Does a mechanism exist to achieve this, or to get close to achieving it? If not, what is the recommended setup for monitoring multiple processes per machine?

**Comment by brian-brazil** [comment]
That is not the Prometheus architecture, so no such feature will be added. See https://www.robustperception.io/one-agent-to-rule-them-all/
