### ISSUE TITLE
Histogram._samples() returns wrong values for buckets

### ISSUE THREAD

**Issue by pyhedgehog** [prometheus/client_python#201]
Sample:
```python
import prometheus_client
histogram = prometheus_client.Histogram('histogram', 'histogram', buckets=range(1,3))
histogram.observe(1)
histogram.observe(3)
print([m.get() for m in histogram._buckets])
print([v for k,l,v in histogram._samples() if k=='_bucket'])
```
expected results - printed lists should be same (1, 0, 1).
actual results:
```
[1.0, 0.0, 1.0]
[1.0, 1.0, 2.0]
```

**Comment by brian-brazil** [comment]
That's an internal method, there's no guarantees about what it returns.

**Comment by pyhedgehog** [comment]
It's what shown in metrics!

**Comment by brian-brazil** [comment]
What's the actual problem you're trying to solve here?

**Comment by pyhedgehog** [comment]
I'm trying to store and show histogram of file sizes.

**Comment by brian-brazil** [comment]
You will either want to use a histogram in the usual fashion there, or write a custom collector.

**Comment by pyhedgehog** [comment]
Well, seems that I've missed something. What is "usual fashion"? Could you give me link to docs or example?

**Comment by brian-brazil** [comment]
https://github.com/prometheus/client_python#histogram

**Comment by pyhedgehog** [comment]
I mean docs for _usage_. I.e. I want to receive alert on timeout. I thought that I should use something like `function_execution_histogram{le="+Inf"}>0`...

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by pyhedgehog** [comment]
Ok. Thank you.
