### ISSUE TITLE
Poor performance in MultiProcessCollector with frequently changing PIDs

### ISSUE THREAD

**Issue by manics** [prometheus/client_python#204]
I'm using [django-prometheus](https://github.com/korfuri/django-prometheus) in multiprocess mode, and I've noticed the time to fetch metrics increases the longer the server has been running. Currently I've got 5414 `*.db` files in `prometheus_multiproc_dir`.

[`MultiProcessCollector.collect`](https://github.com/prometheus/client_python/blob/v0.0.21/prometheus_client/multiprocess.py#L21) reads all db files which I suspect is the bottleneck.

[`mark_process_dead`](https://github.com/prometheus/client_python/blob/v0.0.21/prometheus_client/multiprocess.py#L89) only removes gauge files.

Do you think it'd be feasible to remove all files by copying the contents of `type_{pid}.db` files into a single `type_old.db` file? Or is this something that should be solved in django-prometheus?

**Comment by brian-brazil** [comment]
It's not safe to compact, as there's no locking and a pid might be reused.

How long is the scrape taking?

**Comment by manics** [comment]
django-prometheus was taking around 10s causing the scrape to timeout. There's a total of 55MB .db files in prometheus_multiproc_dir.

I've looked at further into this and can see a few options:
- Increase `scrape_timeout`
- Change our gunicorn `max_requests` to prevent workers turning over so quickly

**Comment by brian-brazil** [comment]
You're going to have to either burn cpu somewhere on locking, or reduce the churn. When I designed this I only had maybe 100 pids in mind. Increasing the interval+timeout and reducing the churn are both options.

**Comment by manics** [comment]
Thanks. If I've understood the code correctly the db files are re-read on each scrape, and would grow without bound assuming the PIDs don't change. Is there a maximum number of metrics or maximum db size beyond which you'd advise restarting the process?

**Comment by brian-brazil** [comment]
This is a relatively new feature, so there's no specific guidance yet. I'd say balance the disruption of a restart against the cost of handling more data.

**Comment by groner** [comment]
I'm running into this issue with metrics I started collecting last week.  Our average scrape time been going up a couple seconds every day.

I'm interested in the possibility of adding a compacting operation to mark_process_dead, if you're open to discussing it @brian-brazil.

**Comment by svanscho** [comment]
We are running into the same issue - is there a fix already?
