### ISSUE TITLE
@_MetricWrapper breaks pylint argument checks

### ISSUE THREAD

**Issue by collinstocks-oscar** [prometheus/client_python#210]
`@_MetricWrapper` changes the call signature of the classes it wraps, breaking pylint argument checks. This causes us to have to annotate every single prometheus object with `# pylint: disable-msg=no-value-for-parameter` to avoid erroneous lint warnings. This gets rather silly.

If the mandatory arguments in the call signature of the wrapper and the metrics classes (like Histogram, Counter, etc) matched, pylint would no longer raise this warning.

Code pointers:
Wrapper: https://github.com/prometheus/client_python/blob/d858f0d39536c2fe10b78d6e26109272b6b2ea46/prometheus_client/core.py#L544
Histogram `__init__()`: https://github.com/prometheus/client_python/blob/d858f0d39536c2fe10b78d6e26109272b6b2ea46/prometheus_client/core.py#L847

The linter complains that `labelvalues` isn't being set because it thinks the two positional arguments I pass are `name` and `labelnames`, when in fact I'm passing `name` and `documentation`.

Note that this is not a bug with PyLint, which can only be expected to do static analysis. Because decorators are arbitrary Python code, PyLint would have to execute the decorator in order to find the wrapper arguments.

**Comment by brian-brazil** [comment]
On one hand you say these are erroneous lint warnings, on the other that this is not a bug with PyLint. Only one of those things can be true. This is abstracting labels as designed, so I say this is a bug in PyLint.

**Comment by collinstocks-oscar** [comment]
This is a direct consequence of dynamically changing the class initialization signature, which is done in prometheus.

**Comment by brian-brazil** [comment]
What's the problem with doing that?

**Comment by collinstocks-oscar** [comment]
It means static analysis can't determine the class initialization signature because the signature is potentially non-deterministic. You and I know what the signature is, and it's documented, but an IDE or PyLint can't tell.

**Comment by brian-brazil** [comment]
What I'm hearing saying is that this is only a problem because of PyLint, and isn't a problem in and of itself.

Is there some particular solution you propose?

**Comment by collinstocks-oscar** [comment]
Right, it means code completion, etc. can't work with prometheus, either.

Would you mind if I spent some time exploring possible solutions, and send you a PR when I get a chance?

**Comment by brian-brazil** [comment]
I'm happy to consider a PR. I would rather the label stuff didn't leak down to Histogram.
