### ISSUE TITLE
Drop Python 2.6

### ISSUE THREAD

**Issue by hugovk** [prometheus/client_python#219]
Pytest and its dependency py have dropped support for Python 2.6 because it's been EOL for four years meaning it hasn't received security updates, and it's also little used so it's about time to drop it. They also dropped support for Python 3.3 which is also EOL and little used.

Here's the pip installs for prometheus_client from PyPI for the last month (via `pypinfo --percent --pip prometheus_client pyversion`).

| python_version | percent | download_count |
| -------------- | ------: | -------------: |
| 2.7            |   61.2% |         44,829 |
| 3.6            |   21.0% |         15,367 |
| 3.5            |   13.5% |          9,890 |
| 3.4            |    4.0% |          2,947 |
| 3.7            |    0.2% |            116 |
| 2.6            |    0.1% |             87 |
| 3.3            |    0.1% |             48 |
| 3.2            |    0.0% |              1 |

I suggest client_python also drops 2.6 (3.3 is already dropped).

**Comment by brian-brazil** [comment]
RHEL 6 has Python 2.6 and is supported through 2024. The effort to support 2.6 so far has been fairly small.

**Comment by ioggstream** [comment]
I think we could leave this tkt open as a reminder.

**Comment by hugovk** [comment]
Feel free to re-open a new ticket, I think I'll close this to clear my list, rather than having this on it for the next 4+ years :)

By the way, here's the numbers for February 2020:

| category | percent | downloads |
|----------|--------:|----------:|
| 2.7      |  32.65% | 1,863,581 |
| 3.6      |  30.54% | 1,742,994 |
| 3.7      |  24.41% | 1,392,992 |
| 3.5      |   8.30% |   473,979 |
| 3.8      |   3.06% |   174,552 |
| null     |   0.73% |    41,653 |
| 3.4      |   0.29% |    16,518 |
| 3.9      |   0.01% |       501 |
| 2.6      |   0.01% |       481 |
| 3.3      |   0.00% |        99 |
| Total    |         | 5,707,350 |

Source: `pip install -U pypistats && pypistats python_minor prometheus_client --last-month`

Cheers!
