### ISSUE TITLE
Best way to clear registry.

### ISSUE THREAD

**Issue by ragnagord** [prometheus/client_python#221]
I want to clear Gauge object (or even whole Registry/database) after being read by Prometheus. I think it requires deleting it in Registry. What is the best way to do it?

**Comment by brian-brazil** [comment]
This is not how Prometheus is meant to work. What are you trying to do?

**Comment by ragnagord** [comment]
i want to constantly send inconsistent amount of data to prometheus. I've added callback function so now i know when Prometheus is scraping data so i can keep it small if only i can reload gauge object. It's like i want to keep track of who did what and how many times and it means that person1 did some thing 10 days ago and then person2 is doing something everyday every hour. So instead of constantly sending to prometheus "person: person1 did thing: thing1 number of times: 0" i want it to be stored on Prometheus side but not being sent forever on every scrape.

**Comment by brian-brazil** [comment]
That sounds like event logging, which a metrics-based system like Prometheus is not a good choice for. I'd suggest looking at Graylog or ELK.
