### ISSUE TITLE
Label problem

### ISSUE THREAD

**Issue by pvanderlinden** [prometheus/client_python#225]
I'm not sure if this is a restriction in this library, or a prometheus restriction.

With the current implementation you have to always send exactly the same labels within a single metric. This makes it difficult if this label is not always available for that metric. Is this something Prometheus restricts, or can this be fixed in the library?

**Comment by brian-brazil** [comment]
This is on purpose, for metrics to make sense you have to know the label names in advance.

**Comment by pvanderlinden** [comment]
Wouldn't it make sense to do something like this though?
- name: `error_metric`, labels: `cause=exception`
- name: `error_metric`, labels: `cause=http_status, status=200`

Also that means, even if there is no reason to have a specific label for one increase of the metric, you have to send it with the metric otherwise it will break.

**Comment by brian-brazil** [comment]
That doesn't make sense at all for metrics, those should probably be different metrics. You're looking for event logging.

**Comment by pvanderlinden** [comment]
We log the specific exceptions, etc to logging as well indeed. This is more to keep metrics on how much which errors occurs till we got to the bottom of the problem (the metrics are meant to figure out where the main causes of the errors lay).

**Comment by pvanderlinden** [comment]
The reason we put it in a single metric is to also be able to see how much errors in total.

**Comment by brian-brazil** [comment]
I'd suggest tracking that metric without those labels then.

**Comment by pvanderlinden** [comment]
As a workaround we added an empty label in the places where we don't have the extra info. Not sure why the library enforces it, as Prometheus itself doesn't enforce it at all as far as I see.

**Comment by brian-brazil** [comment]
The client library guidelines require it, as anyone asking for this almost always is attempting to do event logging.

**Comment by pvanderlinden** [comment]
This case is not event logging, we have a separate system for this, this is to keep track of the amount this happens per type (which is used by many official exporters).

My main problem with this feature is that is isn't (clearly) documented that all labels are always required, and actually causes exceptions. I don't think metric logging should ever cause problems in the rest of the application.
