### ISSUE TITLE
labelvalues unicode convert should set encoding utf-8 to avoid decode exception

### ISSUE THREAD

**Issue by heshiyou** [prometheus/client_python#226]
the code: 
https://github.com/prometheus/client_python/blob/master/prometheus_client/core.py#L552

the exception:
![image](https://user-images.githubusercontent.com/707533/34150336-050c6a00-e4e3-11e7-931b-2e42a94d9f5d.png)

**Comment by brian-brazil** [comment]
Can you be more exact about what the issue is here? It looks like you passed an invalid argument.

**Comment by heshiyou** [comment]
OK, let me explain.

The value I passed is encoded utf-8, sys.getdefaultencoding() is ascii, which is the issue.

**Comment by brian-brazil** [comment]
Can you provide a test case?

**Comment by heshiyou** [comment]
Will provide that late. The issue is quite simple, unicode() function uses sys.getdefaultencoding() as encoding for decode if the encoding arg leaves blank. In this case, my system default encoding is ascii.

**Comment by heshiyou** [comment]
```
======================================================================= FAILURES ========================================================================
__________________________________________________________ TestMetricFamilies.test_labelnames ___________________________________________________________

self = <tests.test_core.TestMetricFamilies testMethod=test_labelnames>

    def test_labelnames(self):
        cmf = UntypedMetricFamily('u', 'help', labels=iter(['a😂'.encode('utf-8')]))
>       self.assertEqual(('a',), cmf._labelnames)
E       UnicodeDecodeError: 'ascii' codec can't decode byte 0xf0 in position 1: ordinal not in range(128)

tests/test_core.py:408: UnicodeDecodeError
```

will fire a PR later

**Comment by heshiyou** [comment]
I see that labelvalue takes unicode string, not encoded string. Is that right?

**Comment by brian-brazil** [comment]
Yes, it takes a unicode string.

**Comment by heshiyou** [comment]
Then the problem will be the label name and metric name only accepts ascii letters, what I need is using some non-ascii words, like emojis 😂😂😂.
https://github.com/prometheus/client_python/blob/master/prometheus_client/core.py#L27
Is this prometheus’s limit or client’s.

**Comment by brian-brazil** [comment]
That's a restriction of Prometheus.
