### ISSUE TITLE
Parser: support of metrics.proto

### ISSUE THREAD

**Issue by JulienBalestra** [prometheus/client_python#233]
Following the current implementation of your [parser](https://github.com/prometheus/client_python/blob/d3562a1021304cf32bb9c0c417594d88244f3767/prometheus_client/parser.py), the function `text_string_to_metric_families` yields a `core.Metric` instance.

I wonder if you may be interested in providing - or as replacement - a [metric.proto](https://github.com/prometheus/client_model/blob/master/metrics.proto) object.

In addition, would you be interested in supporting a `application/vnd.google.protobuf` format to the actual parser ?

In that case, we have a similar use case at Datadog so we would be happy to help working on it.

**Comment by brian-brazil** [comment]
Why do you want to support proto? Virtually everything supports the text format, and Prometheus 2.0 no longer supports proto.

**Comment by JulienBalestra** [comment]
The goal was to use the same object whatever the original format is.
Indeed if prometheus only supports the text format, that's pointless. 

Thank you for the answer, I'm closing the issue.
