### ISSUE TITLE
Tmp mm files haven't been clear while process exit

### ISSUE THREAD

**Issue by kkfnui** [prometheus/client_python#236]
https://github.com/prometheus/client_python/blob/4dd660c88be994342c353d8f5aacbda809a364ea/prometheus_client/multiprocess.py#L94

How about the implement ?

```
def mark_process_dead(pid, path=None):
    """Do bookkeeping for when one process dies in a multi-process setup."""
    if path is None:
        path = os.environ.get('prometheus_multiproc_dir')
    for f in glob.glob(os.path.join(path, '*.db')):
        os.remove(f)
```

**Comment by brian-brazil** [comment]
Can you explain exactly what you think is going wrong?

**Comment by kkfnui** [comment]
Sorry! I should show my case first.

I use [django-prometheus](https://github.com/korfuri/django-prometheus) for monitor server performance. 
Yesterday, Web server occur hight cpu usage that caused by  the scrape request. I found there are many `.db` files in folder `os.environ.get('prometheus_multiproc_dir')`.  There are more than 1k files,  and only 16 web server process.  

Files name, like `counter_*.db` , `gauge_all_*.db`, `histogram_*.db`

The `mark_process_dead` only remove 'gauge_livesum_{0}.db', 'gauge_liveall_{0}.db' which is a part of all.

**Comment by brian-brazil** [comment]
That's the expected behaviour. There's a file per pid, and I presume you've been churning through them. If it's a problem I suggest stopping the webserver, wiping the directory, and starting it again.

**Comment by kkfnui** [comment]
Thanks, I'd clean tmp files when deploy server.

Isn't the api `mark_process_dead` design for clean tmp files when process dead/exit?

**Comment by brian-brazil** [comment]
It's to remove gauges for which you only care about live data, which is going to be a small proportion of all metrics.

**Comment by kkfnui** [comment]
Thanks!
