### ISSUE TITLE
Histogram buckets sorting incorrect w/ different no. of leading digits

### ISSUE THREAD

**Issue by choldgraf** [prometheus/client_python#247]
We're trying to sort the labels in our buckets within Grafana, but running into challenges because the bucket floats aren't being standardized to have the same number of leading digits when converted to strings.

e.g., if our buckets are `[2, 4, 8, 16, 32]`, the sorted bucket labels are `[16, 2, 4, 32, 8]` since it's sorting by first digit. Is there a way to ensure that the proper order is retained when they're converted to strings?

**Comment by brian-brazil** [comment]
Bucket le labels are required to be valid float64 values. If you want to sort them you will need to parse them into float64s first.

**Comment by choldgraf** [comment]
Is this something that PromQl supports? I've been searching through the docs but haven't found anything about parsing labels as floats...

**Comment by brian-brazil** [comment]
It isn't, this is something you need to do in whatever is handling the HTTP API output.

**Comment by choldgraf** [comment]
sounds good - I'll try to figure this out on the grafana side then. will close and try to post a solution if I figure one out
