### ISSUE TITLE
register.unregister(collector) function breaks if same metric exists with multiple label values

### ISSUE THREAD

**Issue by sherif84** [prometheus/client_python#248]
I'm utilizing the python client to write an exporter that basically takes a rest request -> calls a remote server and retrieves metrics -> exports to Prometheus. in order to support the rest request and handle the routing  I had to use flask instead of the client's http_server. since I'm using one collector with different init values, creating a new collector object every time. I believe it uncovered an issue in the unregister function, as when it calls the 

for name in self._collector_to_names[collector]:
    del self._names_to_collectors[name]

since the "self._collector_to_names[collector] " dictionary allows duplicates, and  self._names_to_collectors[name] doesn't, in the second iteration attempting to delete the same name fails to throw an exception 

output:

```
File "/Users/sfathall/Desktop/test_registry.py", line 62, in metrics
    REGISTRY.unregister(scollector)
  File "/Library/Python/2.7/site-packages/prometheus_client/core.py", line 63, in unregister
    del self._names_to_collectors[name]
KeyError: u'temperature'
````

steps to reproduce: 

python test_registry.py

browse to : http://localhost:9999/metrics?target=house5 

test_registry.py

```python
#!flask/bin/python
from flask import Flask,Response,abort,request
import traceback
import sys
from prometheus_client import start_http_server, Summary,Gauge,exposition 
from prometheus_client.core import GaugeMetricFamily, CounterMetricFamily, REGISTRY
from random import *


METRICS_PREFIX='temperature'
CONTENT_TYPE_LATEST = str('text/plain; version=0.0.4; charset=utf-8')

def get_temperature(target):
    result= {'room1':randint(10,120), 'room2':randint(10,120)}
    return result



class SampleCollector(object):
    def __init__(self, target):
        self.target=target

    def collect(self):
        temps= get_temperature(self.target)
        for room,value in temps.iteritems():
            g = GaugeMetricFamily('temperature', 'temeperature value',labels=['target','room'])
            g.add_metric([self.target,room], value)
            yield g


app = Flask(__name__)




@app.route('/', methods=['GET'])
def index():
    return "Usage: /metrics?target=target_host_address"


@app.route('/metrics', methods=['GET'])
def metrics():
    reqargs = request.args
    target= reqargs.get('target')
    if target==None:
        abort(404)
    try:
        scollector=SampleCollector(target=target)
        REGISTRY.register(scollector)
        print '##########  _names_to_collectors ################'
        print REGISTRY._names_to_collectors
        print '\n\n############# _collector_to_names #################' 
        print REGISTRY._collector_to_names
        #REGISTRY.collect()
        data= exposition.generate_latest(registry=REGISTRY)
        print data
        REGISTRY.unregister(scollector)
        return Response(data, mimetype=CONTENT_TYPE_LATEST)
    except Exception, err:
        try:
            exc_info = sys.exc_info()
            try:
                raise TypeError("Again !?!")
            except:
                pass
        finally:
            # Display the *original* exception
            traceback.print_exception(*exc_info)
            del exc_info
            abort(404)


if __name__ == '__main__':
    app.run(host="0.0.0.0", port=int("9999"), debug=False)

```

**Comment by brian-brazil** [comment]
This is incorrect usage, as the registry isn't setup to detect duplicates within a collector and it is your responsibility to provide sane metrics that follow the exposition format. Here you need to return one GaugeMetricFamily from the collector. This code also has a race, collectors should not be registered during the handling of a /metrics. Instead you need a custom registry here, as you are writing a blackbox-style exporter.

The unregister method is only intended for use in unittests.

**Comment by sherif84** [comment]
Hi Brian,
Thanks for the prompt response, also worth mentioning that our team is adopting Prometheus as the main metrics monitoring authority for our networks infrastructure, so we greatly appreciate the work you have done.

so a couple of questions:
1.  is it not expected to have the same metric with multiple label values ? or is that not following the standard format. Example: I'm expecting  something like below ( I'd like to aggregate the temperature across the houses and also across the rooms without creating a metric for every house :
# HELP python_info Python platform information
# TYPE python_info gauge
python_info{implementation="CPython",major="2",minor="7",patchlevel="11",version="2.7.11"} 1.0
# HELP temperature temperature value
# TYPE temperature gauge
temperature{room="room2",target="house5"} 24.0
# HELP temperature temperature value
# TYPE temperature gauge
temperature{room="room1",target="house5"} 108.0

so from the Prometheus prospective, are these considered sane metrics?  if so, then that will break the unregister function even in unit tests

2. is there any documentation for python based black box exporters? or examples you could refer us to.

Thanks again

**Comment by brian-brazil** [comment]
> so from the Prometheus prospective, are these considered sane metrics

That is invalid output. All the time series need to be part of one metric, as shown in the example: https://github.com/prometheus/client_python#custom-collectors

> is there any documentation for python based black box exporters? or examples you could refer us to.

The SNMP exporter used to be written in Python.

**Comment by sherif84** [comment]
thanks brian, I'll look into the old python code

so having one metric with multiple label values is invalid?  if so how can I create a metric with one name -> different value at different labels?

that is similar to how it is done in the snmp exporter currently though:
```
# HELP ifHCOutBroadcastPkts The total number of packets that higher-level protocols requested be transmitted, and which were addressed to a broadcast address at this sub-layer, including those that were discarded or not sent - 1.3.6.1.2.1.31.1.1.1.13
 TYPE ifHCOutBroadcastPkts counter
ifHCOutBroadcastPkts{ifIndex="335544320"} 4645645
ifHCOutBroadcastPkts{ifIndex="369098861"} 656
ifHCOutBroadcastPkts{ifIndex="369098866"} 45
```

**Comment by sherif84** [comment]
closing as it seems to be a non-issue , will continue conversation in google group

**Comment by cauwulixuan** [comment]
meet the same issue, how did you solve that? @sherif84

**Comment by cauwulixuan** [comment]
Hope someone could come up to the [google group](https://groups.google.com/forum/#!topic/prometheus-developers/0iWjebijEvk)
