### ISSUE TITLE
Remove prometheus_multiproc_dir environment variable

### ISSUE THREAD

**Issue by vklap** [prometheus/client_python#250]
Hi,

It would be great if you could remove the dependency on the "prometheus_multiproc_dir" environment variable.

Thanks

**Comment by brian-brazil** [comment]
What would you suggest instead?

**Comment by vklap** [comment]
Add a config class that exposes this prometheus_multiproc_dir variable - which could be altered / set only at startup and only once (maybe by making this config class a singleton, or by keeping this config data in a class "static" property).

If this prometheus_multiproc_dir property won't be set - then just resort to taking this value from the "prometheus_multiproc_dir" environment variable, as done today.

**Comment by brian-brazil** [comment]
That depends on it being the very first thing that is loaded, which is not a thing you have control of.

**Comment by vklap** [comment]
What about "lazy loading" this value?

**Comment by brian-brazil** [comment]
That'd be quite expensive, and wouldn't work at all for gauges.

**Comment by brian-brazil** [comment]
What's the actual problem you have with the current approach?

**Comment by vklap** [comment]
I've to define this env variable in every piece of code that uses the prometheus client (from infrastructure based packages to web/worker apps - and in all the environments I'm deploying the code).

**Comment by brian-brazil** [comment]
You don't need to touch any code, just the deployment scripts.

**Comment by vklap** [comment]
Sure, I know this -  and unfortunately that's what I'm doing, because I've no other choice -
and it's not only in the deployment scripts - it's also in every development environment that relies on the prometheus client.

In my humble opinion relying solely on environment variables in general, and specifically for dynamically linking types - as done in the core.py module, shown below - is problematic:

`if 'prometheus_multiproc_dir' in os.environ:
    _ValueClass = _MultiProcessValue()
else:
    _ValueClass = _MutexValue`

This dependency is even worse when it's in an external library that your code depends upon - because it forces the dependent code to declare environment variables that are not even related to its domain.

Think about this: what if you had to define even a single environment variable for each and every library your code depends on - you would end up with a gazillion environment variables ;)

I believe that relying on some global initialization code is definitely the way to go.

Again, this is my humble opinion - and if you disagree, then it's fine.
On the other hand, if what I've written makes sense to you - then I would be happy to try and give a few tips about how I think this can be resolved.

Anyway, thank you very much for being so responsive.

**Comment by brian-brazil** [comment]
I do disagree, as we can't rely on global init code as we'd have to guarantee it was always run first - which there is no way to do in general. Thus the environment variable.

There's nothing stopping you from setting the environment variable in your code rather than from the invoking strips, but I expect it'll be fragile.

**Comment by brycedrennan** [comment]
@brian-brazil Probably a silly question, but why can't it just default to `{os_tmp_folder}/prometheus` and be overridable with the env variable?

**Comment by brian-brazil** [comment]
We don't want to use it unless it's needed, as there's various downsides to it.

**Comment by brycedrennan** [comment]
Ah I didn't realize that this setting is not just merely specifying the path to use when in MultiProcess mode.   It's actually controlling whether it's used. 

I think we can refactor the library to not need this specified before any metrics are defined.  Would you be open to a PR for that?

**Comment by brian-brazil** [comment]
I'm not sure that's possible, but I'd be interested to see what you're thinking.

**Comment by brycedrennan** [comment]
@brian-brazil I'm working on a solution to this. You mentioned a concern about performance, is there any sort of benchmark or specific scenarios you'd like me to test for?

**Comment by brian-brazil** [comment]
How long an observation events takes. What are you thinking?

**Comment by brycedrennan** [comment]
Well I came up with a solution that worked but in the end found a simpler way.  All that needs to to be updated is the readme example gunicorn configuration file.  

```python
import distutils.dir_util
import glob
import os
import tempfile


def on_starting(server):
    coordination_dir = os.environ.get("prometheus_multiproc_dir", tempfile.gettempdir() + "/prometheus-multiproc-dir/")
    os.environ["prometheus_multiproc_dir"] = coordination_dir
    distutils.dir_util.mkpath(coordination_dir)
    _clear_metrics(coordination_dir)


def worker_exit(server, worker):
    from prometheus_client import multiprocess

    multiprocess.mark_process_dead(worker.pid)


def _clear_metrics(path):
    for filepath in glob.glob(path + "*.db"):
        os.remove(filepath)
```

**Comment by brian-brazil** [comment]
That's not safe in the general case, as users may import other things here before the environment get changed.

**Comment by brycedrennan** [comment]
I'd imagine its pretty rare to import metrics in the gunicorn conf file. Perhaps adding a comment "Make sure you don't import or initialize any metrics in the gunicorn configuration file" would address that. 

I'm fine with it just existing in this thread though, as people will find it if needed.

The other solution I was working on worked but threw away any data collected before the user specified multiprocessing mode.  I don't have motivation to finish that anymore though.

**Comment by rakshitcgupta** [comment]
Hi, Probably this is a basic question. I couldn't find documentation on this - What should be the value of prometheus_multiproc_dir ? In my pod it throws up error "ValueError: env prometheus_multiproc_dir is not set or not a directory" Is there a standard value for this? Should I be setting this value from a secret or config map? Thanks
