### ISSUE TITLE
Reset Counter's value to zero if the value reach `+Inf`

### ISSUE THREAD

**Issue by pyk** [prometheus/client_python#265]
Hey, there is a case when my metric counter reach `+Inf` value. 

```
sanic_requests_total{endpoint="/products",method="GET"} +Inf
```

This case can be reproduced using the following code:

```python
# app.py
import sys

from sanic import Sanic
from sanic import response
import prometheus_client as prometheus
from prometheus_client import exposition

app = Sanic()

# pylint: disable=E1120
srt = prometheus.Counter("sanic_requests_total",
                         "Track the total number of requests",
                         ["method", "endpoint"])

# Overflow the prometheus counter
@app.get("/test-overflow")
async def test_overflow(request):
    # pylint: disable=E1101
    srt.labels(method=request.method, endpoint=request.path).inc(sys.float_info.max)
   
    return response.json("hello")

@app.get("/metrics")
async def metrics(request):
    output = exposition.generate_latest().decode("utf-8")
    return response.text(body=output,
                         content_type=exposition.CONTENT_TYPE_LATEST)

if __name__ == '__main__':
    app.run(host="0.0.0.0", port=8080)
```

If this is happen, the graph on the Grafana is showing a flat line zero. The current solution is to simply restart the server if the counter value reach `+Inf`. Maybe we can [reset the counter value](https://github.com/prometheus/client_python/blob/master/prometheus_client/core.py#L326) if the value reach `+Inf` ?

**Comment by brian-brazil** [comment]
May I ask what your use case is for this?

**Comment by pyk** [comment]
@brian-brazil my use case is using `Counter` metric to track the total number of HTTP requests for my microservices

**Comment by brian-brazil** [comment]
I somehow doubt that you are going to overflow a float by counting http requests.
