### ISSUE TITLE
ImportError: No module named 'resource' on Windows

### ISSUE THREAD

**Issue by flesire** [prometheus/client_python#27]
I tried to use the client on Windows with python 2.7 and i have the following error :

ImportError: No module named 'resource'

This error occurs because 'resource' module is only available for UNIX system.

Is 'resource' module usage could be optional in a Windows application ?

Regards.

**Comment by brian-brazil** [comment]
I don't have a Windows system to test on, but if you can add something to disable that on Windows I'll be happy to accept a PR

**Comment by brian-brazil** [comment]
Can you try out #28 and see if it fixes the problem?

**Comment by brian-brazil** [comment]
#28 is in and released, so this should be good.

**Comment by vikramrajsitpal** [comment]
@brian-brazil Can you please take a look at issue #183 

Thanks.
