### ISSUE TITLE
Metrics objects (e.g. Counter) does not have labels method

### ISSUE THREAD

**Issue by ezyang** [prometheus/client_python#272]
```
>>> import prometheus_client
>>> x = prometheus_client.Counter('foo', 'foobar')
>>> x.labels
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Counter' object has no attribute 'labels'
```

The documentation seems to imply that this is possible. This is on 0.2.0

Relevant README docs:

Labels
All metrics can have labels, allowing grouping of related time series.

See the best practices on naming and labels.

Taking a counter as an example:

```
from prometheus_client import Counter
c = Counter('my_requests_total', 'HTTP Failures', ['method', 'endpoint'])
c.labels('get', '/').inc()
c.labels('post', '/submit').inc()
```

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by ezyang** [comment]
The answer is that the `labels` method is only defined if you pass the set of labels in the constructor of the counter/whatever. If you don't pass it, then the labels method is undefined. This is surprising; normally the methods of a Python object would be defined no matter what arguments you pass to a constructor.

**Comment by callowaylc** [comment]
`The answer is that the labels method is only defined if you pass the set of labels in the constructor of the counter/whatever. If you don't pass it, then the labels method is undefined` 

lol, if the case, so awful..
