### ISSUE TITLE
write_to_textfile() overwrites file

### ISSUE THREAD

**Issue by aweiteka** [prometheus/client_python#276]
I have multiple instances of a script that runs periodically, potentially concurrently. I plan to use the textfile collector with node_exporter. However with this [simple example script](https://paste.fedoraproject.org/paste/KNaS3P4TsMxrwZhtW01aTg) the textfile gets overwritten each time the script runs. I would expect `inc()` with `write_to_textfile()` to safely read and increment the value in the file. Am I using registry incorrectly?

**Comment by brian-brazil** [comment]
This is working as expected, it's not intended to be used as a event aggregator.
