### ISSUE TITLE
Efficient histogram observations

### ISSUE THREAD

**Issue by jkruse-tds** [prometheus/client_python#279]
I've been searching for a couple days and couldn't find anything similar.  Is there a way to take already computed histogram data and add it in bulk.  My current solution is doing multiple observations using a range as the number of iterations.

For example, using this input: 

            8192 |                                         0
           16384 |                                         2
           32768 |                                         0
           65536 |@@@@@@@@@@@@@@@@@@@                      74
          131072 |@@@@@@@@@@@@@@@                          59
          262144 |@@@                                      14
          524288 |                                         0

It would be nice to call a single function that observes the first item the value for the last item.

**Comment by brian-brazil** [comment]
Why are you trying to do bulk adds to a histogram?

**Comment by jkruse-tds** [comment]
I'm using DTrace to get some idea on write times within ZFS.  It is able to provide me with data already in buckets and I figured a histogram would be the proper place to put that and visualize it within a heatmap in grafana.

**Comment by brian-brazil** [comment]
That sounds like you're writing an exporter, https://github.com/prometheus/client_python#custom-collectors is how you go about that,
