### ISSUE TITLE
CustomCollector usage, not showing metrics

### ISSUE THREAD

**Issue by bitsofinfo** [prometheus/client_python#280]
I reviewed multiple questions on how to rest/clear gauges etc. All the answers point to a custom collector

https://github.com/prometheus/client_python#custom-collectors
https://github.com/prometheus/client_python/issues/182

I did this as in the example, followed by `start_http_server(8000)`

I see the collector being called, but there are zero metrics at http://locahost:8000

am I missing something?

**Comment by brian-brazil** [comment]
I get output from that, so I'd double check your code.

**Comment by bitsofinfo** [comment]
my misktake!
