### ISSUE TITLE
Abusive memory usage after high traffic multiprocess gunicorn

### ISSUE THREAD

**Issue by theonlydoo** [prometheus/client_python#283]
After doing some tests w/ [patator](https://github.com/lanjelot/patator) to try and guess paths on an internal app, we encountered an abusive memory usage case which was not obvious. This is kind of related to: https://github.com/prometheus/client_python/issues/275

A 4GB docker was oomkilling its processes after a DoS phase, those processes were respawned by gunicorn, who was reading at boot time the .db files, triggering a 200Mb/s disk read at each bootstrap, all those bootstraps were triggering oomkills, with a resulting endless oom loop. 

I discarded any incoming traffic, isolated the docker and saw the exact same thing. So, a strace on the active pids were showing a lot of read, I looked at the opened files and saw those .db files. After a brutal deletion of those files, I finally got the container to settle down to a normal CPU/RAM usage (forgot to mention that the CPU was stuck @500%, seems coherent with the db load).

I finally took a screenshot of the resulting variation of both CPU and RAM on ctop:
![](https://dooby.fr/y/rq69n4m)

Some tech details:

```
prometheus_client==0.0.21
gunicorn==19.8.1
```

**Comment by brian-brazil** [comment]
Your description doesn't sound right, the only time all of these files are read is when a /metric scrape is performed. Are you sure you had no incoming traffic? Can you also indicate how many files you had?

**Comment by theonlydoo** [comment]
```
"du -h /tmp ; ls -lh /tmp/multiproc-tmp"
98M	/tmp/multiproc-tmp
98M	/tmp
total 98M
-rw-r--r-- 1 nobody nogroup 1.0M Jun 13 16:01 counter_12.db
-rw-r--r-- 1 nobody nogroup 2.0M Jun 13 16:01 counter_14.db
-rw-r--r-- 1 nobody nogroup 1.0M Jun 13 16:02 counter_164.db
-rw-r--r-- 1 nobody nogroup 1.0M Jun 13 16:02 counter_202.db
-rw-r--r-- 1 nobody nogroup 1.0M Jun 13 16:01 counter_27.db
-rw-r--r-- 1 nobody nogroup 2.0M Jun 13 16:01 counter_40.db
-rw-r--r-- 1 nobody nogroup 1.0M Jun 13 16:01 gauge_min_12.db
-rw-r--r-- 1 nobody nogroup 1.0M Jun 13 16:01 gauge_min_14.db
-rw-r--r-- 1 nobody nogroup 1.0M Jun 13 16:02 gauge_min_164.db
-rw-r--r-- 1 nobody nogroup 1.0M Jun 13 16:02 gauge_min_202.db
-rw-r--r-- 1 nobody nogroup 1.0M Jun 13 16:01 gauge_min_27.db
-rw-r--r-- 1 nobody nogroup 1.0M Jun 13 16:01 gauge_min_40.db
-rw-r--r-- 1 nobody nogroup  16M Jun 13 16:01 histogram_12.db
-rw-r--r-- 1 nobody nogroup  32M Jun 13 16:01 histogram_14.db
-rw-r--r-- 1 nobody nogroup 1.0M Jun 13 16:02 histogram_164.db
-rw-r--r-- 1 nobody nogroup 1.0M Jun 13 16:02 histogram_202.db
-rw-r--r-- 1 nobody nogroup  16M Jun 13 16:01 histogram_27.db
-rw-r--r-- 1 nobody nogroup  32M Jun 13 16:01 histogram_40.db

```

after a while, gunicorn workers are just loopcrashing (I can't even do another web hit), the app receives no more http trafic.

The DoS takes about 2khits/s for ~ 3min and workers are logging in a loop:
```
2018-06-13 16:05:37 [644:gunicorn.error:271] [INFO] Booting worker with pid: 
```
a strace gives me:
```
mmap(NULL, 262144, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f47ee7bd000
```
a lot of reads
and cpu/ram usage are looking like this on that inactive app:
![](https://dooby.fr/y/h7649wb)
and after a deletion of those .db files:
![](https://dooby.fr/y/nkvha4m)

So, I don't know if the crashloop occurs on a scrape (which could makes sense) or a worker bootstrap, but it occurs after a short high traffic period.

**Comment by brian-brazil** [comment]
It sounds to me like some other part of your code is likely to blame here. To verify, disable multiprocess mode by not providing the environment variable.

**Comment by theonlydoo** [comment]
We anticipated that answer a bit and tried to run the app without prometheus exporter → the bug is not present anymore and I can hit the app quite relentlessly without any notable consequences.

**Comment by brian-brazil** [comment]
> We anticipated that answer a bit and tried to run the app without prometheus exporter 

That helps, but is not the question I asked. What happens if you disable multiprocess mode?

How big is your /metrics? To have 32MB for the histogram for one process is not easy. I smell a cardinality issue.

**Comment by brian-brazil** [comment]
It turns out that this was a cardinality issue on a path label.
