### ISSUE TITLE
Pushgateway, is it safe to use REGISTRY?

### ISSUE THREAD

**Issue by WoLpH** [prometheus/client_python#286]
Since it's a lot of work to modify all methods to always have a `registry` available it would be far more convenient to have something like this:

```python
def collected(function):
    @functools.wraps
    def _collected(*args, **kwargs):
        try:
            return function(*args, **kwargs)
        finally:
            push_to_gateway(job=function.__name__, registry=REGISTRY)
    return _collected

@collected
def some_function()
     ...
     g = Gauge('something', 'Something')
     ...
```

**Comment by brian-brazil** [comment]
For the intended use cases of the pushgateway of service level batch jobs, you want a custom registry rather than the default one as it'd add in lots of metrics that weren't really relevant.

**Comment by brian-brazil** [comment]
It also looks like you're trying to push more than once in an application's lifecycle, see https://prometheus.io/docs/practices/pushing/

**Comment by WoLpH** [comment]
I'm trying to capture the measurements being generated by background tasks (which are passed around through rabbitmq). So I'd want to capture all data from a single task (similar to a single http request in a webserver) and push it after.

So alternatively could I modify the method to temporarily monkeypatch the `REGISTRY`?

**Comment by brian-brazil** [comment]
It sounds like you want to use normal direct instrumentation then, not the pushgateway as this is offline processing.

**Comment by WoLpH** [comment]
The amount of processes running these is quite variable so I'm not sure that would be convenient. Adding/removing endpoints constantly doesn't seem like a very convenient way of working but I could be wrong...

I'm coming from a statsd based system where this is easily possible but I'm not sure how to easily translate it.

**Comment by brian-brazil** [comment]
Direct instrumentation is the statsd equivalent, no need to involve the pushgateway. Use things like gauges in the usual way, as file-level objects.

**Comment by WoLpH** [comment]
Ok, that sounds good. But how could I collect it after the fact? These processes are not (all) long-running so capturing it from an endpoint might not work

**Comment by brian-brazil** [comment]
If you've a multi-process setup, check out https://github.com/prometheus/client_python#multiprocess-mode-gunicorn

**Comment by WoLpH** [comment]
They're launched separately unfortunately (from cron and/or supervisord) so that approach won't work :(

**Comment by brian-brazil** [comment]
That'd still work, however it sounds like you've a few different systems here. Anything using supervisord is a daemon, and should use direct instrumentation. Cron jobs can be service-level batch jobs, so should push the metrics you care about when they exit to the pushgateway,

**Comment by WoLpH** [comment]
Ok, thanks for the help :)
I'll give it a try
