### ISSUE TITLE
Thread suite broken on Python 2 due to lack of concurrent.futures

### ISSUE THREAD

**Issue by kyrias** [prometheus/client_python#296]
As of https://github.com/prometheus/client_python/commit/889a6fb91636c6d1b0728436686f7017c9a778b1 the test suite requires `concurrent.futures`, which was introduced in Python 3.2, meaning that the test suite is now nonfunctional under Python 2.7.

**Comment by brian-brazil** [comment]
You need to install the futures packages on Python 2 for the tests to work.
