### ISSUE TITLE
error: [Errno 104] Connection reset by peer

### ISSUE THREAD

**Issue by cauwulixuan** [prometheus/client_python#298]
Recently I met an issue. I wrote an exporter to scrape hadoop metrics from several hadoop jmx urls using client_python. The exporter runs perfect at first, but some times an `connection reset error` report in the log, the metrics won't update either.

Any suggestions here? Thanks.

Here is the error log:
```
Aug 18 12:34:58 k8s-1 python[18975]: Traceback (most recent call last):
Aug 18 12:34:58 k8s-1 python[18975]: File "/usr/lib64/python2.7/SocketServer.py", line 593, in process_request_thread
Aug 18 12:34:58 k8s-1 python[18975]: self.finish_request(request, client_address)
Aug 18 12:34:58 k8s-1 python[18975]: File "/usr/lib64/python2.7/SocketServer.py", line 334, in finish_request
Aug 18 12:34:58 k8s-1 python[18975]: self.RequestHandlerClass(request, client_address, self)
Aug 18 12:34:58 k8s-1 python[18975]: File "/usr/lib64/python2.7/SocketServer.py", line 649, in __init__
Aug 18 12:34:58 k8s-1 python[18975]: self.handle()
Aug 18 12:34:58 k8s-1 python[18975]: File "/usr/lib64/python2.7/BaseHTTPServer.py", line 340, in handle
Aug 18 12:34:58 k8s-1 python[18975]: self.handle_one_request()
Aug 18 12:34:58 k8s-1 python[18975]: File "/usr/lib64/python2.7/BaseHTTPServer.py", line 310, in handle_one_request
Aug 18 12:34:58 k8s-1 python[18975]: self.raw_requestline = self.rfile.readline(65537)
Aug 18 12:34:58 k8s-1 python[18975]: File "/usr/lib64/python2.7/socket.py", line 476, in readline
Aug 18 12:34:58 k8s-1 python[18975]: data = self._sock.recv(self._rbufsize)
Aug 18 12:34:58 k8s-1 python[18975]: error: [Errno 104] Connection reset by peer
```

`promtheus` version:
```
[root@k8s-1 prometheus-1.7.2.linux-amd64]# prometheus -version
prometheus, version 1.7.2 (branch: HEAD, revision: 22eadbe635528fa17b99a7635fed6b6018103042)
  build user:       root@05b1548df2cc
  build date:       20170926-16:41:43
  go version:       go1.8.3
```
`prometheus-client` version: 0.2.0

**Comment by brian-brazil** [comment]
I don't see anything unusual here, the other side closed the connection.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by LionelZhao28** [comment]
I meet the same problems, I don't know where the requests come from.
But the error logs covered the entire screen and it is too hard to check the project logs.
I think the server should catch this exception and let the user determine whether print it out
