### ISSUE TITLE
A server serving HTTP/1.1 responses with MetricsHandler causes client requests to timeout

### ISSUE THREAD

**Issue by banjoh** [prometheus/client_python#299]
In a server running HTTP/1.1 protocol version the **Content-Length** header is recommended in responses of at least **GET** requests. Lack of this header causes clients to wait indefinitely ending up in a **read timeout** There are other recommendations such as the server closing the connection, but that is counteract connection persistence (keepalive).

```python
from http.server import BaseHTTPRequestHandler, HTTPServer
from prometheus_client import MetricsHandler

class HTTPRequestHandler(MetricsHandler):
    
    # Necessary for connection persistence (keepalive)
    protocol_version = 'HTTP/1.1'

    def do_GET(self):
        return super(HTTPRequestHandler, self).do_GET()

if __name__ == "__main__":
    server_address = ('', 8000)
    HTTPServer(server_address, HTTPRequestHandler).serve_forever()
```

```bash
[banjoh@ubuntu] 16:49 $ curl -v --max-time 10 localhost:8000
* Rebuilt URL to: localhost:8000/
*   Trying ::1...
* TCP_NODELAY set
* connect to ::1 port 8000 failed: Connection refused
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8000 (#0)
> GET / HTTP/1.1
> Host: localhost:8000
> User-Agent: curl/7.58.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Server: BaseHTTP/0.6 Python/3.6.5
< Date: Thu, 23 Aug 2018 13:49:55 GMT
< Content-Type: text/plain; version=0.0.4; charset=utf-8
* no chunk, no close, no size. Assume close to signal end
< 
# I removed the metrics payload from here ....
python_info{implementation="CPython",major="3",minor="6",patchlevel="5",version="3.6.5"} 1.0
* Operation timed out after 10002 milliseconds with 1013 bytes received
* stopped the pause stream!
* Closing connection 0
curl: (28) Operation timed out after 10002 milliseconds with 1013 bytes received
```

To fix this add ```self.send_header("Content-Length", len(output))``` after https://github.com/prometheus/client_python/blob/master/prometheus_client/exposition.py#L100

RFC -> https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html

**Comment by banjoh** [comment]
To preempt the obvious question, I'm using the library this way in an effort to extend an existing HTTP server implementation. In my use case I need to expose a **host:port/metrics** endpoint. My handler looks something like below

```python
class HTTPRequestHandler(MetricsHandler):
    # Necessary for connection persistence (keepalive)
    protocol_version = 'HTTP/1.1'

    def do_GET(self):
        endpoint = urlparse(self.path).path
        if endpoint == '/foo':
            return self.get_foo()
        elif endpoint == '/metrics':
            return super(HTTPRequestHandler, self).do_GET()
        else:
            # respond with 404
```

**Comment by brian-brazil** [comment]
Can you point to exactly where in the spec it says that content-length is required? I can't see it.

**Comment by banjoh** [comment]
I updated the issue a bit.

The RFC says **SHOULD** which is a recommendation, so you are right. However, there are recommendations of how a server respond if the header is missing.

There are 7 recommendations in [rfc7230](https://greenbytes.de/tech/webdav/rfc7230.html#message.body.length)

**Comment by brian-brazil** [comment]
This sounds like an issue with your intermediate code, we're following the spec here.

**Comment by brian-brazil** [comment]
In that case the issue then is you specifying HTTP 1.1, if you remove that it'll work.

**Comment by banjoh** [comment]
It will work, but I need HTTP 1.1 for connection reuse. Otherwise connection pooling cannot work

**Comment by brian-brazil** [comment]
That's an impendence mismatch on your end then, which I'm afraid I can't help you with. There's changes planned that depend on things working this way.

**Comment by banjoh** [comment]
Alright.

I disagree on the impedance mismatch though since with this _current version_ of , `MetricsHandler` is bound to `protocol_version < 'HTTP/1.1'`. Yes, the implementation is not violating the protocol as such, but user-agents are left in an ambiguous state, hence the time out. Web server implementations inject the header, but the  `MetricsHandler` class is not extendable.

> There's changes planned that depend on things working this way.

If there are changes that depend of things remaining as they are, it would be good to mention using `MetricsHandler` as is with `'HTTP/1.1'` just won't work.

**Comment by akx** [comment]
Wouldn't this be simply fixed by adding

```python
self.send_header('Content-Length', str(len(output))
```
at around

https://github.com/prometheus/client_python/blob/c0cee96e3cbd6f9c2a768502dcc2be3a7330abb1/prometheus_client/exposition.py#L136

since we do definitely know the size of the payload anyway?

**Comment by cliffpracht** [comment]
@banjoh I'm hitting the same issue.  Were you able to work around/solve this?

**Comment by banjoh** [comment]
@akx yes, that would do the trick. @cliffpracht I have not found a workaround yet.

**Comment by brian-brazil** [comment]
This doesn't look like an issue on our end per-se, and OpenMetrics will be even more streaming.
