### ISSUE TITLE
Can't import Info and Enum

### ISSUE THREAD

**Issue by misach** [prometheus/client_python#304]
Hi all

I'm a newly on this but I tried to follow the READ.ME.
I successfully created my first exporter:
```
from prometheus_client import start_http_server, Summary
import random
import time

# Create a metric to track time spent and requests made.
REQUEST_TIME = Summary('request_processing_seconds', 'Time spent processing request')

# Decorate function with metric.
@REQUEST_TIME.time()
def process_request(t):
    """A dummy function that takes some time."""
    time.sleep(t)

if __name__ == '__main__':
    # Start up the server to expose the metrics.
    start_http_server(8000)
    # Generate some requests.
    while True:
        process_request(random.random())
```

But when I try to import Info or Enum I'm getting an error message:
```
Traceback (most recent call last):
  File "./run_test.py", line 1, in <module>
    from prometheus_client import start_http_server, Summary, Info
ImportError: cannot import name Info

```
I'm using python 2 but I tried it with python 3 as well. Same result. Import of Counter, Gauge and Histogram are working.
 
What do I wrong?

**Comment by brian-brazil** [comment]
These classes were recently added, are are not yet in a released version.

**Comment by misach** [comment]
Ah okay - that explains it :-) . Is there already a release date by when you can install it via pip?

**Comment by ellisgeek** [comment]
Any timeline on the release of Enum and Info? there are some things that I would like to instrument that would benefit from these types.
