### ISSUE TITLE
Missing Info & Enum classes

### ISSUE THREAD

**Issue by localhostport80** [prometheus/client_python#305]
In fact the documentation tells the following

> Four types of metric are offered: Counter, Gauge, Summary and Histogram.

Nevertheless a few lines below it shows the classes Enum and Info, which are not available for me, so `from prometheus_client import Info` results in `ImportError: cannot import name {Info, Enum}`. Am I missing something?

**Comment by brian-brazil** [comment]
A release hasn't been made with these changes yet.
