### ISSUE TITLE
Option to block main thread when serving metrics

### ISSUE THREAD

**Issue by NotAFile** [prometheus/client_python#314]
When writing exporters, I usually want the program to run indefinitely once I call `start_http_server`. Currently, I need to add a workaround using e.g. `while True: sleep(100)`. It would be nicer if there was a `block=True` or similar kwarg which would hang the main thread instead.

This seems simple enough that I might try add it myself if I get a positive reaction.

**Comment by Shtsh** [comment]
signal.pause() would be a better solution

https://docs.python.org/3/library/signal.html#signal.pause

**Comment by brian-brazil** [comment]
It's one line of code for the user to add, so I don't see a big need to expand the API.
