### ISSUE TITLE
SSL with basic auth CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by Drewster727** [prometheus/client_python#319]
Hi All,

I'm attempting to push custom metrics over ssl with basic auth enabled.
I have setup an nginx reverse proxy to accept connections on port 9092, and then redirects to the push gateway port (9091).

Here's how I'm pushing the metrics:
```
METRICS_MONITOR_HOST = "https://somedomain.com"

def prometheus_auth_handler(url, method, timeout, headers, data):
    username = METRICS_MONITOR_USER
    password = METRICS_MONITOR_PASS
    return basic_auth_handler(url, method, timeout, headers, data, username, password)

def upload_results_to_prometheus(result_dict):
    registry = CollectorRegistry()
    for metric_name, value in result_dict.items():
        g = Gauge(metric_name, "", registry=registry)
        g.set(value)

    push_to_gateway("%s:%s" % (METRICS_MONITOR_HOST, METRICS_MONITOR_PORT),
        job=job_name, registry=registry, handler=prometheus_auth_handler)
```

I am seeing a CERTIFICATE_VERIFY_FAILED error when it attempts to push:

> Traceback (most recent call last):
>   File "/deploy/siphon/siphon/utils/syshealth_metrics.py", line 153, in <module>
>     main()
>   File "/deploy/siphon/siphon/utils/syshealth_metrics.py", line 147, in main
>     upload_results_to_prometheus(result_dict)
>   File "/deploy/siphon/siphon/utils/syshealth_metrics.py", line 59, in upload_results_to_prometheus
>     job=job_name, registry=registry, handler=prometheus_auth_handler)
>   File "/usr/local/lib/python2.7/dist-packages/prometheus_client/exposition.py", line 224, in push_to_gateway
>     _use_gateway('PUT', gateway, job, registry, grouping_key, timeout, handler)
>   File "/usr/local/lib/python2.7/dist-packages/prometheus_client/exposition.py", line 295, in _use_gateway
>     headers=[('Content-Type', CONTENT_TYPE_LATEST)], data=data,
>   File "/usr/local/lib/python2.7/dist-packages/prometheus_client/exposition.py", line 178, in handle
>     default_handler(url, method, timeout, headers, data)()
>   File "/usr/local/lib/python2.7/dist-packages/prometheus_client/exposition.py", line 157, in handle
>     resp = build_opener(HTTPHandler).open(request, timeout=timeout)
>   File "/usr/lib/python2.7/urllib2.py", line 429, in open
>     response = self._open(req, data)
>   File "/usr/lib/python2.7/urllib2.py", line 447, in _open
>     '_open', req)
>   File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
>     result = func(*args)
>   File "/usr/lib/python2.7/urllib2.py", line 1241, in https_open
>     context=self._context)
>   File "/usr/lib/python2.7/urllib2.py", line 1198, in do_open
>     raise URLError(err)
> urllib2.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)>

This is of course a self-signed certificate and I do not care at this point to get a signed one. Can I get around this somehow? Thank you.

**Comment by brian-brazil** [comment]
You'll need to create a custom handler if you want to set https settings.

**Comment by Drewster727** [comment]
@brian-brazil thanks -- is there any example of creating a custom handler?

**Comment by brian-brazil** [comment]
You can look at the ones that are already in the codebase.

**Comment by Drewster727** [comment]
OK - I will just copy the basic_auth_handler def into my own code, and pass that in with the SSL verification disabled. Thanks.

**Comment by blingster7** [comment]
@Drewster727 what did your custom handler look like out of curiosity?

**Comment by PerJNilsson** [comment]
@brian-brazil would you be able to link to the ones in the codebase? Unable to find anything to make sence of

**Comment by fernandino143** [comment]
I can related @PerJNilsson . Also can't find an actual example. Anyone?

**Comment by Kurzhalsgiraffe** [comment]
I also found this solution, which works for me:
```python
# Custom Basic Auth Handler, that skips TLS verification
def custom_auth_handler(url, method, timeout, headers, data):
    def handle():
        with requests.Session() as session:
            session.trust_env = False
            session.auth = HTTPBasicAuth(PUSHGATEWAY_USERNAME, PUSHGATEWAY_PASSWORD)
            session.headers.update(headers)
            response = session.request(
                method=method,
                url=url,
                timeout=timeout,
                data=data,
                verify=False
            )
            return response
    return handle```
