### ISSUE TITLE
Export _INF publicly

### ISSUE THREAD

**Issue by korfuri** [prometheus/client_python#32]
Hi,

For my [Django exporter](http://github.com/korfuri/django-prometheus) I need to import _INF from prometheus_client because I build my own buckets (powers of 2, powers of 10) and I need _INF at the end.

Could you expose it publicly in the API (in __init__.py ideally, since it was moved in 0.0.10)?

**Comment by brian-brazil** [comment]
Hmm, I can see the use but it doesn't feel quite right to have this as part of the main public API. I can also see myself reorganising the internals a bit more to tighten things up a bit and this getting in the way.

Are you aware that if you don't put Inf as the last bucket that the client will do it for you?

**Comment by beorn7** [comment]
And if the client forgets to add it, the server will do it for you. :)

The inf bucket is essentially redundant (same value as `..._count`).

**Comment by korfuri** [comment]
Oh, this changes everything :) Thanks!
