### ISSUE TITLE
Opt-in to built-in collectors?

### ISSUE THREAD

**Issue by akx** [prometheus/client_python#321]
Slightly related to the multiproc deadlock I found in my #313 PR, it would be nice if `GC_COLLECTOR`, `PLATFORM_COLLECTOR` and `PROCESS_COLLECTOR` weren't implicitly created and registered.

After all, [they say](https://www.python.org/dev/peps/pep-0020/) that

> Explicit is better than implicit.

and the fact that just initializing a `GCCollector()` hooks in to the garbage collector and starts creating metrics feels a little bad.

**Comment by brian-brazil** [comment]
The only time you wouldn't' be interested in these is if you're doing something fancy, such as creating a snmp-style exporter and using custom registries - which are empty by default.

If users had to add an ever-expanding list of collectors by hand, they'd never end up with their benefits.

**Comment by akx** [comment]
Well, something like `prometheus_client.install_default_collectors(registry=REGISTRY)` would be a good middle road, probably.

Future versions of the library can just make that function install new collectors as they are implemented, so users who have opt-inned to have the default collectors would get new ones for free, and those more discerning (like my use case) can enable the collectors they want in whichever registry they like.

**Comment by brian-brazil** [comment]
The Prometheus client library guidelines are that these should be enabled by default, and there are ways to disable them if you really want. All the previous users who have asked for something like this in the various clients have typically misunderstood how the system was meant to be used.

**Comment by akx** [comment]
I totally understand the philosophy of "metrics all the things!", sure, but still, I would say it's considered bad form for `import`ing modules to do this sort of thing in the Python world. 

The [Java client](https://github.com/prometheus/client_java#included-collectors) requires this sort of explicit step anyway (but the [Golang client](https://github.com/prometheus/client_golang/blob/0a8115f42e037a6e327f9a269a26ff6603fb8472/prometheus/registry.go#L55-L58) doesn't; it uses a `func init` to implicitly initialize these metrics).

Regarding disabling the GC collector (which, at present, is my most pressing issue, as I can't deploy our app with `prometheus_client` enabled with it active due to the deadlock problem in #322):  
* The metrics it exposes are registered as-is in the `REGISTRY`, so unregistering them would involve digging through the registry's internals to figure out which metrics are GC metrics, then calling `.unregister()` on them, and
* filtering through `gc.callbacks` to remove the `_cb` function.

I don't consider that a very clean way to disable the collector I didn't want in the first place. 😞

**Comment by brian-brazil** [comment]
> The Java client requires this sort of explicit step anyway

That's due to technical limitations, if I could sanely make it automatic I would.

I'd prefer to fix the deadlock issue.

**Comment by mcelep** [comment]
I am also facing similar issues like @akx  while trying to unregister the 'default' metrics. There should ideally be an easier way to opt out.

**Comment by Stivo** [comment]
I also ended up here. I am not instrumenting a webserver, this library just seemed to be the easiest way to push some metrics to prometheus. Both the client and prometheus are running on a raspberry pi, so I am worried about storage.

**Comment by brian-brazil** [comment]
There's already an opt-out, and the GC issue is fixed now.

**Comment by akx** [comment]
> There's already an opt-out

Is there an officially documented/sanctioned opt-out method, or do you mean just weeding out collectors manually from the default registry?

**Comment by brian-brazil** [comment]
Each of the default collectors has a public name so you can unregister them.

**Comment by MikeSchuette** [comment]
Can we document this in the Readme?  I'm somewhat new to Python and have failed to figure this out.

**Comment by sss-ng** [comment]
@MikeSchuette 

To unregister the default collectors:

```python3
import prometheus_client

prometheus_client.REGISTRY.unregister(prometheus_client.GC_COLLECTOR)
prometheus_client.REGISTRY.unregister(prometheus_client.PLATFORM_COLLECTOR)
prometheus_client.REGISTRY.unregister(prometheus_client.PROCESS_COLLECTOR)
```
