### ISSUE TITLE
Documentation about existing parameters in metrics?

### ISSUE THREAD

**Issue by ricardohbin** [prometheus/client_python#323]
There are some important parameters in all metrics constructors (https://github.com/prometheus/client_python/blob/master/prometheus_client/core.py#L765) like `registry` that is not documented.

What do you think about put them in README?

**Comment by brian-brazil** [comment]
Unit is new, and hasn't been documented yet.

Namespace/subsystem are vestigal, and I don't generally recommend them.
Registry is only for advanced cases, and is mentioned in the README where it's needed.
