### ISSUE TITLE
A Gauge metric not working?

### ISSUE THREAD

**Issue by hawran** [prometheus/client_python#333]
Hi all,
I've tried to create one gauge metric within a small Python project:
```
# at file level
m = Gauge('m', 'Number of ...')
...

# some 'init' section
m.set(0.0)
...

# setting to a new value somewhere within a code
m.set(new_value)
...
```
However, when I get metrics (via `GET .../metrics`) the value of the metric `m` is stil zero (`0.0`):
```
# HELP m Number of ...
# TYPE m gauge
m 0.0
```

I've done some small tests and I've found a strange thing as follows:
From the snippet
```
...
print("BEFORE m._samples(): {}".format(m._samples()))
m.labels(l='x').set(alive)
print("AFTER m._samples(): {}".format(m._samples()))
...
```
I've got the output:
```
BEFORE m._samples(): (('', {}, 0.0),)
AFTER m._samples(): (('', {}, 1.0),)
```

What am I missing?

Some system info:
```
$ pip3 list --user
...
prometheus-client (0.4.2)
...
Xubuntu:
$ lsb_release -a
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.5 LTS
Release:        16.04
Codename:       xenial
$
```

NB Other metric (a Counter one) works as expected.

**Comment by brian-brazil** [comment]
I can't reproduce this, can you show a full minimal program?

**Comment by hawran** [comment]
> I can't reproduce this, can you show a full minimal program?

Hi Brian,
I've checked my code again and found some hidden typos, :-/.
So everything works as expected now.

Sorry for disturbing you,
haw.

**Comment by brian-brazil** [comment]
No problem.
