### ISSUE TITLE
start_http_server should put metrics on a /metrics url by default

### ISSUE THREAD

**Issue by wrouesnel** [prometheus/client_python#34]
Since prometheus assumes the metrics will be on /metrics by default, the client library should make this assumption too (and provide a configurable to change it).

**Comment by brian-brazil** [comment]
start_http_server serves metrics on all endpoints, which includes /metrics. Is this not working for you?

**Comment by wrouesnel** [comment]
Hm...it wasn't earlier but seems to be now. Between now and then I fixed a bug which was rapidly re-creating collectors in my code, so maybe that did it. Closing this issue - thanks!
