### ISSUE TITLE
python 2.7.15 prometheus_client bad cache

### ISSUE THREAD

**Issue by dillonko** [prometheus/client_python#342]
The current cache path for the prometheus client is not working  because it is a bad path. I have added the console output  below.

```
$ python -m pip install prometheus_client
Collecting prometheus_client
  Using cached https://files.pythonhosted.org/packages/61/84/9aa657b215b04f21a72ca8e50ff159eef9795096683e4581a357baf4dde6/prometheus_client-0.4.2.tar.gz
    Error [Errno 2] No such file or directory while executing command python setup.py egg_info
Could not install packages due to an EnvironmentError: [Errno 2] No such file or directory
```

if I curl this path it shows that it no longer exist so it does not work when running and breaks.

does anyone have a fix for this issue?

**Comment by brian-brazil** [comment]
That's an ENOENT from your local system, likely something's not right with your filesystem.

**Comment by dillonko** [comment]
Hi @brian-brazil ,
Thank you for the fast reply do you know how to fix this issue. It could be the fact that its a Mac and I just upgraded to Mojave.

**Comment by brian-brazil** [comment]
No idea, strace is your friend for this sort of thing.

**Comment by dillonko** [comment]
Thanks @brian-brazil I am using a Mac it seems that strace has an alternative called dtruss I am just not sure how to use it. Can you point me toward any useful information.

**Comment by brian-brazil** [comment]
I'm going to presume this is resolved by now, it's unlikely to be a problem with this repo.
