### ISSUE TITLE
Enum not working

### ISSUE THREAD

**Issue by xoh** [prometheus/client_python#353]
Using a custom collector with an Enum does not work - the call to Enum blocks. I've set up a minimal example to demonstrate the issue:
```
from prometheus_client import start_http_server, Enum, REGISTRY
import time

class EnumCollector(object):
        def collect(self):
                print("before enum")
                e = Enum('task_state', 'Description of enum', states=['starting', 'running', 'stopped'])
                print("after enum")
                e.state('running')
                yield e

if __name__ == '__main__':
        start_http_server(8765)
        REGISTRY.register(EnumCollector())
        while True: time.sleep(3600)
```

Starting either via `python test.py` (Python 2.7.12) or `python3 test.py` (Python 3.5.2) prints "before enum" and stops responding. CTRL+C does nothing using Python 2:
```
$ python test.py
before enum
^C^C
```

CTRL+C with Python 3 renders the following stack trace:
```
$ python3 test.py
^CTraceback (most recent call last):
  File "test.py", line 14, in <module>
    REGISTRY.register(EnumCollector())
  File "/home/xoh/.local/lib/python3.5/site-packages/prometheus_client/core.py", line 96, in register
    names = self._get_names(collector)
  File "/home/xoh/.local/lib/python3.5/site-packages/prometheus_client/core.py", line 136, in _get_names
    for metric in desc_func():
  File "test.py", line 7, in collect
    e = Enum('task_state', 'Description of enum', states=['starting', 'running', 'stopped'])
  File "/home/xoh/.local/lib/python3.5/site-packages/prometheus_client/core.py", line 854, in init
    registry.register(collector)
  File "/home/xoh/.local/lib/python3.5/site-packages/prometheus_client/core.py", line 95, in register
    with self._lock:
KeyboardInterrupt
```

The installed version of prometheus_client is 0.4.2:
```
$ pip show prometheus_client
...
Version: 0.4.2
```
```
$ pip3 show prometheus_client
...
Version: 0.4.2
```

**Comment by brian-brazil** [comment]
Enum is like Counter, you don't use it in collectors. You probably want StateSetMetricFamily.

**Comment by xoh** [comment]
Thanks for the quick response!

My plan was to use Enum inside the collector to implement a custom exporter monitoring the state of a cluster with states red (degraded), yellow (warning - a single failure would lead to degradation) and green (everything is fine). I will try StateSetMetricFamily. After a quick look on the source of StateSetMetricFamily this should work for me, thus I close the issue.

Thanks again for your fast help!
