### ISSUE TITLE
Replace multiprocess mode with utility to map-reduce stats from subprocesses

### ISSUE THREAD

**Issue by neumond** [prometheus/client_python#359]
I have async workers controlled by master process, so this becomes bad to use multiprocessing.Lock() and file IO to collect stats. This can be done optimally if every worker process could collect it's own stats, expose them in `/metrics`, then use map-reduce, i.e. sending request to every worker for metrics (probably automatically applying some labels as well), then merging them into resulting dataset.

For prometheus it will look like single endpoint to poll. It is much easier to discover. It doesn't spoil async applications with blocking syscalls. It encapsulates worker pool maintaining complexity.

The only needed thing in code of this library is function able to merge several metrics outputs.

**Comment by brian-brazil** [comment]
If all the processes had http servers, we'd have Prometheus scrape them directly. However this doesn't help us scrape metrics for dead or short-lived processes.

The file reads should also be from memory, and don't hold locks.

**Comment by neumond** [comment]
Not exactly, what if process pool works over unix sockets? And this is too complex to fine tune discovery of these processes. Some people, including me, do not need this complexity and level of monitoring.

You can see what people do to get around this:
- Involving consul http://blog.archer.onl/article/collecting-prometheus-metrics-for-python-services-behind-gunicorn-using-consul/
- Putting statsd in the middle https://medium.com/@damianmyerscough/monitoring-gunicorn-with-prometheus-789954150069
- Inventing libraries https://pypi.org/project/prometheus-async/
- Inventing libraries again https://pypi.org/project/aioprometheus/
- And again.. https://pypi.org/project/hr-prometheus/

What I propose in this issue, is removing all multiprocessing/locking and all I/O code from core, allowing people to build opt-in adapters for their needs. And module for merging outputs, which should merely process set of texts into another one.

**Comment by brian-brazil** [comment]
Windows doesn't have unix sockets, and that'd be hitting the kernel. There's already a solution in this library.

**Comment by neumond** [comment]
I need to make additional research, I still believe all of this should be much simpler and way more a choice of user regarding channels of data transmission/overall architecture.
