### ISSUE TITLE
Garbage collector metrics lead to deadlock

### ISSUE THREAD

**Issue by megabotan** [prometheus/client_python#363]
Story:
We have default gc metrics, for example python_gc_collected_objects_count.
Someone tries to get metrics value(for example http handler). This leads to MutexValue.get() call. Lock is aquired inside get() method.
If garbage collector decides to run at this moment, the callback updating gc metrics is triggered. Inside this callback metrics is need to be updated, but it cant get the lock which is already taken. Deadlock.

Snippet reproducing this story: (if you try to open localhost:8000 it will fail).
``` python
import gc
import time
from threading import Lock
from prometheus_client import values
from prometheus_client import start_http_server


class MutexValue(object):
    '''A float protected by a mutex.'''

    _multiprocess = False

    def __init__(self, typ, metric_name, name, labelnames, labelvalues, **kwargs):
        self._value = 0.0
        self._lock = Lock()

    def inc(self, amount):
        with self._lock:
            self._value += amount

    def set(self, value):
        with self._lock:
            self._value = value

    def get(self):
        with self._lock:
            gc.collect()    #<------------------------------ Added only this line
            return self._value


values.ValueClass = MutexValue

start_http_server(8000)
while True:
    time.sleep(1)
```
Do we really need lock in get() method?

**Comment by brian-brazil** [comment]
What version are you using? This should already be fixed.

**Comment by megabotan** [comment]
prometheus-client==0.5.0

**Comment by brian-brazil** [comment]
Okay, I see what's happening. As this isn't the first issue in this area, how the GC collector works should probably be reconsidered so that we're not using the client library on the critical path.

**Comment by mhoyer** [comment]
We experienced the same in our application. Is there any workaround or fix in sight?

**Comment by brian-brazil** [comment]
PRs and ideas welcome.

**Comment by KeNaCo** [comment]
Our mitigation of this problem is simply wrapping call with timeout which kill thread. Sufficient enough to keep ThreadPool working..
