### ISSUE TITLE
Make query parameters available in the client

### ISSUE THREAD

**Issue by MarkusTeufelberger** [prometheus/client_python#370]
I'd like to write an exporter that takes parameters (e.g. http://example.com:12345/metrics?foo=bar&fizz=buzz - see https://prometheus.io/docs/prometheus/latest/configuration/configuration/#scrape_config `params` about how to set these).

Maybe I overlooked it, but it doesn't seem to me that these parameters are available when requests are coming in? It would be great if it could be documented somewhere how to implement an exporter that way.

**Comment by brian-brazil** [comment]
This is something to be implemented outside the client library, collectors explicitly don't have access to these to avoid layering violations.

**Comment by MarkusTeufelberger** [comment]
So something like `blackbox_exporter` or the `node_exporter` (https://github.com/prometheus/node_exporter#filtering-enabled-collectors) is a layering violation? Alternatively, if I want to monitor a bunch of known API endpoints via an exporter, I should add one job per host instead of setting a variable?

I can see several uses for parameters and I don't really see what would be violated by using them. It would be nice if you could either explain what you mean by these "layering violations" or what kind of issue you want to avoid by having parameters available in Prometheus, but not available to exporters in the official client.

**Comment by jasondewitt** [comment]
I came here looking for the same thing. I want to implement an exporter similar to how BlackBox works, except to run Lighthouse tests for a given url that is passed to the exporter via relabel configs and query params, the same way that BlackBox exporter works.

If this is not possible with the python client, I guess I finally have the project to make me finally learn Go.

**Comment by brian-brazil** [comment]
It's possible in the Python client the same way it's possible in Go. This isn't a feature that'll be added.
