### ISSUE TITLE
exposition.generate_latest() is slow

### ISSUE THREAD

**Issue by belm0** [prometheus/client_python#374]
With just the default metrics of the Python client, this function takes around 2 ms on my old-ish laptop.  I'm sure it would rise to 5-10 ms once the app starts adding metrics.  Given limited options due to the GIL, it's really not acceptable to halt soft real-time applications for that amount of time on every metrics pull.

Upon profiling, I noticed some low hanging fruit:
  * floatToGoString() is 18% of total time.  I think it could be replaced with Python's "g" format.
  * sample_line() local function is just slow - 13% of total time in its own code.  Worth trying to optimize.
  * str.format() is called ~500 times for each call to generate_latest(), representing 12% of total time.  f-strings would probably do wonders.

**Comment by brian-brazil** [comment]
1: Not quite, we need a slightly different format
3: f-strings are not available in Python 2

I'm happy to look at optimisation PRs.

**Comment by belm0** [comment]
'g' format has precision control, so the 'f' vs. 'e' switching could be made to match Go's 'g'.  From there I think it's just transform of "inf" -> "Inf", etc.?

**Comment by belm0** [comment]
my plan for throttling CPU use of `generate_latest()` without modification to client_python:
  * given that generate_latest() only uses the collect() method of input registry
  * wrap the collect method
  * after every ~500 usec wall time, collect iteration will sleep for ~50 ms  (so 1% CPU cap)
  * assuming that generate_latest() can be called from a background thread

**Comment by brian-brazil** [comment]
That won't work if there's an exporter written in Python, and would slow some things down quite a bit.

**Comment by belm0** [comment]
Would you explain how it would break things?

The sleeping wrapper would only be on the registry object passed to `generate_latest()`.  Anything else using the registry would get the normal collect() behavior.

**Comment by brian-brazil** [comment]
generate_latest is how it's usually used, including by exporters.

**Comment by belm0** [comment]
I guess in my case I have a custom exporter, calling generate_latest() directly to serve the text on an asyncio web server.  I'm not aware of anything else which would use generate_latest().

**Comment by brian-brazil** [comment]
Most users wouldn't even be aware that generate_latest is being called, as it's usually done under the covers.

**Comment by belm0** [comment]
Sorry for the confusion.  To be clear, the scheme of adding sleep during collect iteration is just something I would do locally for my needs to work around the issue.  I landed on that because it doesn't require maintaining any patches to client_python (it's merely fiddling with the object passed to generate_latest).

As far as a more general improvement that could be submitted, I'd suggest revisiting whether clients must match Go float formatting in such exacting detail.  I'm sure Go's float parser can handle both 1234567.8 and 1.2345678+e06 equally well.    If floatToGoString() were simplified to just inf and nan case changes (if that's even needed), it would be a big win.

**Comment by belm0** [comment]
Demonstrating that golang float parsing is not particular about fixed vs. exponent notation, nor case, nor exponent leading 0.  The floatToGoString() translation doesn't appear to be needed-- am I misunderstanding?

```
inputs := []string{"1234567.9", "1.2345679e+06", "1.2345679e+6", "inf", "-inf", "nan"}
```
```
1.2345679e+06
1.2345679e+06
1.2345679e+06
+Inf
-Inf
NaN
```

https://play.golang.org/p/MvmKCnPsyA_8

**Comment by brian-brazil** [comment]
It's required for some openmetrics stuff, and this code is the reference implementation. Thus it uses it everywhere it avoid confusion for other implementors.

**Comment by belm0** [comment]
openmetrics explicitly requires 1.2345679e+06 rather than 1234567.9?  Has anyone questioned that?  It's inefficient for scripting language clients to implement custom floating point to string conversion.

**Comment by brian-brazil** [comment]
It's only required in certain places, and it's more a question of if it's possible than efficiency.

**Comment by belm0** [comment]
> It's only required in certain places

Why would openmetrics specify the exact point of switching between fixed and exponent notation, rather than parse either notation?

I don't see any detail about this in the openmetrics draft (https://github.com/OpenObservability/OpenMetrics/blob/master/markdown/metric_exposition_format.md)

The Prometheus docs say only that the number is able to parse by Go's ParseFloat() (https://prometheus.io/docs/instrumenting/exposition_formats/)

> it's more a question of if it's possible than efficiency

It's heavy for clients like Python or JS to do such custom number formatting, and specifically for Python represents about 20% of text generation time.

**Comment by brian-brazil** [comment]
I don't think there's anything we can really do here, so closing off.
