### ISSUE TITLE
File descriptor leak caused by clients causing system to get down

### ISSUE THREAD

**Issue by tusharmakkar08** [prometheus/client_python#377]
I am facing this issue with prometheus-client==0.5.0 and Python 3.5.2. I am using `start_http_server` command to start the server. 

To be precise my close_wait connections keep on increasing till my server stops serving requests.

x@ip-10-0-0-0:~$ lsof -i | grep 8002
python 10601 x 3u IPv4 78413488 0t0 TCP *:8002 (LISTEN)
python 10601 x 55u IPv4 82060563 0t0 TCP ip-10-0-0-0.ap-south-1.compute.internal:8002->ip-172-00-00-00.ap-south-1.compute.internal:45114 (CLOSE_WAIT)
python 10601 x 80u IPv4 82089551 0t0 TCP ip-10-0-0-0.ap-south-1.compute.internal:8002->ip-172-00-00-00.ap-south-1.compute.internal:45976 (CLOSE_WAIT)
python 10601 x 81u IPv4 82088475 0t0 TCP ip-10-0-0-0.ap-south-1.compute.internal:8002->ip-172-00-00-00.ap-south-1.compute.internal:46006 (CLOSE_WAIT)
python 10601 x 82u IPv4 82089875 0t0 TCP ip-10-0-0-0.ap-south-1.compute.internal:8002->ip-172-00-00-00.ap-south-1.compute.internal:46034 (CLOSE_WAIT)
python 10601 x 83u IPv4 82092200 0t0 TCP ip-10-0-0-0.ap-south-1.compute.internal:8002->ip-172-00-00-00.ap-south-1.compute.internal:46064 (CLOSE_WAIT)

![image](https://user-images.githubusercontent.com/2357025/52057592-7085a780-258b-11e9-9242-a3fc0cef98d4.png) 

This issue is similar to https://github.com/prometheus/jmx_exporter/issues/327 

Attaching strace here for the issue. https://ideone.com/0VORDa

**Comment by brian-brazil** [comment]
I don't see anything there related to Prometheus. Why do you think the issue is with the python client?

That's also not a complete strace.

**Comment by tusharmakkar08** [comment]
I think the issue is due to `start_http_server` functionality in the client. When I am running it via third-party http server (wsgi) there is no such issue.

**Comment by brian-brazil** [comment]
Can you get a full strace of one of those tcp connections?

**Comment by tusharmakkar08** [comment]
Thing is, as of now, I am unable to reproduce the issue. It happens once in 2 days. I would get strace of those connection whenever the issue occurs again.

**Comment by brian-brazil** [comment]
Did you manage to get more debug information?

**Comment by brian-brazil** [comment]
Closing as stale, given no other reports like this I presume the issue is elsewhere.
