### ISSUE TITLE
Initializing a metric with a tuple for labels leads to incorrect label count

### ISSUE THREAD

**Issue by wrouesnel** [prometheus/client_python#38]
```python
g = prometheus_client.Gauge(
            "my_super_special_metric",
           "This is  ametric", 
           ("label"))
g.labels({"label" : "somevalue"}).set(1)
```
Leads to "incorrect label names".
Changing it to:
```python
g = prometheus_client.Gauge(
            "my_super_special_metric",
           "This is  ametric", 
           ["label"])
g.labels({"label" : "somevalue"}).set(1)
```
works normally.

Since both are iterable types, it would be idiomatic python to ensure that any non-string sequence type supplied for the labels be treated as a list of labels.

**Comment by brian-brazil** [comment]
> ("label")

This isn't a tuple, it's a string in parens. ("label", ) is what you want.

**Comment by wrouesnel** [comment]
Doi :)

**Comment by Sispheor** [comment]
And if we want multiple labels?
I tried this bu it  doesn't work
```python
my_val= Gauge('val_name', 'My val description,
                               [("product_name",), ("server_name",)])
```

**Comment by Sispheor** [comment]
It's ok, here is the way to go for thos who pass here

```python
# declaration of the gauge
my_val= Gauge('val_name', 'My val description, ["product_name", "server_name"])

# usage
my_val.labels(product_name=product_name, server_name=server_name).set(val)

```

**Comment by hokiegeek2** [comment]
> It's ok, here is the way to go for thos who pass here
> 
> ```python
> # declaration of the gauge
> my_val= Gauge('val_name', 'My val description, ["product_name", "server_name"])
> 
> # usage
> my_val.labels(product_name=product_name, server_name=server_name).set(val)
> ```

Thank you @Sispheor!
