### ISSUE TITLE
Question: how to instrument a multiprocessing program?

### ISSUE THREAD

**Issue by moio** [prometheus/client_python#382]
Specifically: I am trying to instrument a program that uses `multiprocessing` directly, without Gunicorn or any other framework/server.

What are the basic assumptions? What I am currently doing (in the parent process) is:

```python
prometheus_dir = "/tmp/my-dir"
shutil.rmtree(prometheus_dir, ignore_errors=True)
os.mkdir(prometheus_dir)
os.environ["prometheus_multiproc_dir"] = prometheus_dir

registry = CollectorRegistry()
multiprocess.MultiProcessCollector(registry)
start_http_server(8004, registry=registry)
```

Then code I want to instrument lives in child processes, where I am using:

```python
REQUEST_TIME = Summary('request_processing_seconds', 'Time spent in request')

[...]

@REQUEST_TIME.time()
@tornado.gen.coroutine
def method(self, load):
  [...]
```

Expected behavior: `request_processing_seconds_count` and `request_processing_seconds_sum` grow as `method` gets called.

Actual behavior: `request_processing_seconds_count` and `request_processing_seconds_sum` stay at 0.0.

I am surely doing something wrong, but I could not figure out what from documentation or internal code so far - if anybody could explain that would be very very nice.

Thanks in advance!

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by moio** [comment]
Thanks, sorry.
