### ISSUE TITLE
MetricWrapperBase.remove() should accept kwargs in the same way as label() does

### ISSUE THREAD

**Issue by nodakai** [prometheus/client_python#385]
https://github.com/prometheus/client_python/blob/master/prometheus_client/metrics.py#L160

Making it usable as `ctr.labels(...).remove()` can also be a useful enhancement, by holding a reference to the parent Counter inside children.

**Comment by brian-brazil** [comment]
What's your use case for this? Remove should be used pretty rarely to start with.

**Comment by nodakai** [comment]
We have a system under monitoring whose subsystems (each with its own metrics, distinguished by a label) can dynamically be added or removed once in a while depending on external events. Imagine hot-[un]plugging of storage devices.

**Comment by brian-brazil** [comment]
That sounds like you should be using custom collectors rather than direct instrumentation.

**Comment by nodakai** [comment]
I'm rather hesitant to start a philosophical design discussion here, when we already have a functional system and all I propose is improving the usability of an existing API

**Comment by brian-brazil** [comment]
This is a usage question that was answered, so closing.
