### ISSUE TITLE
Rename labelvalues to _labelvalues to make clear that it's internal

### ISSUE THREAD

**Issue by bm371613** [prometheus/client_python#398]
Metrics with labelvalues are not collected. In the example below, I would expect all 3 counters to be collected, but the one with labelvalues is not.

```
from prometheus_client import REGISTRY, Counter

c1 = Counter("c1", "c1")
c2 = Counter("c2", "c2", labelnames=["l1"])
c3 = Counter("c3", "c3", labelnames=["l1"], labelvalues=["v1"])

c1.inc()
c2.labels("v1").inc()
c3.inc()

for item in REGISTRY.collect():
    print(item)  # prints c1 and c2, but not c3
```

**Comment by brian-brazil** [comment]
That should be producing an exception, that's invalid usage.

**Comment by bm371613** [comment]
Where should I learn about the intended usage?

sob., 13.04.2019, 11:44 użytkownik Brian Brazil <notifications@github.com>
napisał:

**Comment by brian-brazil** [comment]
https://github.com/prometheus/client_python#labels

**Comment by bm371613** [comment]
It does not mention labelvalues. If labelvalues are not for passing values
for labels and my example is invalid usage, the issue should be that
labelvalues are not intuitive and not documented.

sob., 13.04.2019, 12:35 użytkownik Brian Brazil <notifications@github.com>
napisał:

**Comment by brian-brazil** [comment]
Non-existent features tend not to be documented.

**Comment by bm371613** [comment]
I meant the labelvalues argument. It is an argument of a constructor of a
public class that is not documented. It would be fine if there was only one
reasonable behavior given its name and that was how it worked, but this is
not the case.

I have an answer now, but I won't close the issue - you may want to keep it
open as a reminder that the labelvalues parameter could use a docstring.
Otherwise close it.

sob., 13.04.2019, 14:54 użytkownik Brian Brazil <notifications@github.com>
napisał:

**Comment by dash-rai** [comment]
> It is an argument of a constructor of a public class that is not documented.
I agree with @bm371613 here. It is easily assumed that `labelvalues` is meant for accepting default values for labels, and there is no indication that this is wrong -- like @brian-brazil said, it doesn't raise an exception.

I'm not sure what the intended use of `labelvalues` is, but it would be a useful feature to have the ability to set "default" labels or a base set of labels for all child metrics. Support for chaining calls to `.labels()` would probably be required too.

**Comment by ewtoombs** [comment]
`labelvalues` is for internal use only. It is used in the `MetricWrapperBase.labels()` method to create a new `MetricWrapperBase` with `labelvalues` set. Since the metric already was registered, there's an if statement in `MetricWrapperBase`'s constructor that prevents registration of the metric if `labelvalues` is set.

So, *that's* why you're seeing the behaviour that you are. The user was never supposed to use the `labelvalues` argument of `MetricWrapperBase` in the first place.

This is terrible and it should be fixed! One way to do it is add an internal argument, `register=True`, to `MetricWrapperBase`. Then, `MetricWrapperBase.labels()` initiates the child `MetricWrapperBase` with `_register=False`. Then, `labelvalues` will have the obvious and assumed behaviour.

Incidentally, if this is what you want, initialise `c3` like this instead:
```
c3 = Counter('c3', 'c3', labelnames=['l1']).labels('v1')
```

**Comment by lulzmachine** [comment]
IMO the current situation is quite confusing and quite time consuming. What do you feel about adding a couple of lines in the documentation to warn about this argument? Or perhaps just a warning for users?

**Comment by brian-brazil** [comment]
I'm not sure how changing the user docs will help if users are ignoring the docs and instead digging into the source and using undocumented internal APIs.

**Comment by lulzmachine** [comment]
In this case it's not clear that it's an internal API. Labelvalues is a kwarg on a public constructor, and it looks like it fills a need that the end user often feels (setting a default value for a Gauge's labels). If it's only meant to be internal then yeah maybe you're right, the best place to make hanger might not be in the documentation. 

Renaming it by prepending a "_" is a common pythonic way of marking something as internal. Maybe that?

**Comment by brian-brazil** [comment]
That sounds reasonable.

I'll note that a default value for a label doesn't really make sense, you need to have code to provide the actual label value one way or the other.

**Comment by brian-brazil** [comment]
@belm0 That is unrelated to this issue.

**Comment by belm0** [comment]
It's related because the people attempting to use `labelvalues` are wanting precisely this functionality, as the OP concedes.

**Comment by brian-brazil** [comment]
No, they're not looking for initialisation of childs. Please don't confuse the issue.

**Comment by SeYoungKim** [comment]
Still in 2025, at first I thought `_labelvalues` was for sharing labelsets. And metrics with `_labelvalues` weren't collected without any exception, warning message. I couldn't find any explanation about this and needed to look into its code... 

I think at least there must be a warning keyword. It will help potential users save a lot of time.
