### ISSUE TITLE
Invalid response to "application/openmetrics-text" Prometheus requests

### ISSUE THREAD

**Issue by Gyllsdorff** [prometheus/client_python#399]
I just setup Prometheus 2.9.1, when it tries to parse my `/metrics` url it throws a `invalid metric type "info"` error if I have a `Info` line.

Error from Prometheus log:
```
prometheus_1                          | level=warn ts=2019-04-19T17:59:44.932649585Z caller=scrape.go:835 component="scrape manager" scrape_pool=apps target=http://127.0.0.1:20171/metrics msg="append failed" err="invalid metric type \"info\""
```

Code:
```python3
from prometheus_client import Info
app_info = Info("app_info", "Application information")
```

`curl http://localhost/metrics --header "Application: foo"`:
```
# HELP python_info Python platform information
# TYPE python_info gauge
python_info{implementation="CPython",major="3",minor="7",patchlevel="2",version="3.7.2"} 1.0
# HELP app_bm_info Application information
# TYPE app_bm_info gauge
app_bm_info{test="bar"} 1.0
```

`curl http://localhost/metrics --header "Accept: application/openmetrics-text; version=0.0.1,text/plain;version=0.0.4;q=0.5,*/*;q=0.1"`:
```
# HELP python_info Python platform information
# TYPE python_info gauge
python_info{implementation="CPython",major="3",minor="7",patchlevel="2",version="3.7.2"} 1.0
# HELP app_bm_info Application information
# TYPE app_bm_info info
app_bm_info{test="bar"} 1.0
```

If I intercept prometheus request and change the `Accept` header to something else Prometheus get the response in a format it can parse.

It is the `# TYPE app_bm_info info` line Prometheus does not like.

**Comment by brian-brazil** [comment]
Can you show the full headers involved?

**Comment by Gyllsdorff** [comment]
This is a dump of the incoming request from Prometheus 2.9.1.
```json
{
 "client": [
  "127.0.0.1",
  37532
 ],
 "headers": [
  [
   "host",
   "127.0.0.1:20171"
  ],
  [
   "user-agent",
   "Prometheus/2.9.1"
  ],
  [
   "accept",
   "application/openmetrics-text; version=0.0.1,text/plain;version=0.0.4;q=0.5,*/*;q=0.1"
  ],
  [
   "accept-encoding",
   "gzip"
  ],
  [
   "x-prometheus-scrape-timeout-seconds",
   "2.000000"
  ]
 ],
 "http_version": "1.1",
 "method": "GET",
 "path": "/metrics",
 "query_string": "",
 "root_path": "",
 "scheme": "http",
 "server": [
  "127.0.0.1",
  20171
 ],
 "type": "http"
}
```

[This](https://github.com/prometheus/client_python/blob/master/prometheus_client/exposition.py#L135) means the library will respond with the Openmetric formatted response which seems to use the raw `type` of the metric, but Prometheus only accepts counter, gauge, histogram, summary, or untyped.

The regular `python_info` output uses the `Gauge` class directly instead of the `Info` class which bypasses this problem.

https://prometheus.io/docs/instrumenting/exposition_formats/#comments-help-text-and-type-information
> If the token is TYPE, exactly two more tokens are expected. The first is the metric name, and the second is either counter, gauge, histogram, summary, or untyped, defining the type for the metric of that name.

**Comment by brian-brazil** [comment]
What are the response headers?

**Comment by Gyllsdorff** [comment]
Thanks man, I think that is the problem. :)

Response headers:
```json
[
  [
    "content-type",
    "application/json"
  ],
  [
    "x-request-id",
    "QZsB94nVYm/8"
  ],
  [
    "access-control-allow-origin",
    "*"
  ],
  [
    "access-control-max-age",
    "3600"
  ],
  [
    "access-control-allow-methods",
    "GET, POST, OPTION, DELETE, PATCH"
  ],
  [
    "access-control-allow-headers",
    "authorization"
  ],
  [
    "content-type",
    "application/openmetrics-text; version=0.0.1; charset=utf-8"
  ]
]
```

A middleware added a `content-type: application/json` header, when I remove it everything started working as expected.
