### ISSUE TITLE
Add ConstLabels feature in python client

### ISSUE THREAD

**Issue by Ashish-Bansal** [prometheus/client_python#406]
There's ConstLabels feature in the Prometheus Go client which is missing in the python client.

**Comment by brian-brazil** [comment]
That feature is going away from Go I believe. Can you explain your use case?

**Comment by beorn7** [comment]
The reason that ConstLabels aren't really needed anymore in the Go client is that we have https://godoc.org/github.com/prometheus/client_golang/prometheus#WrapRegistererWith now. Does the Python client have a similar feature?

**Comment by Ashish-Bansal** [comment]
> https://godoc.org/github.com/prometheus/client_golang/prometheus#WrapRegistererWith

I see. 

The usecase is I want to specify the instance label for each metric pushed to the pushgateway.

**Comment by brian-brazil** [comment]
You've looking for grouping labels then for the pushgateway, which we do support. 

Also, https://prometheus.io/docs/practices/pushing/. You should not be pushing instance labels to the pushgateway.

**Comment by beorn7** [comment]
> The usecase is I want to specify the instance label for each metric pushed to the pushgateway.

In that case, chances are you want to use that label as part of the grouping key. Which would implicitly add it to all metrics pushed with that grouping key.

**Comment by Ashish-Bansal** [comment]
I see. So, the usecase in the Go client is adding the fixed custom label per process when prometheus scrapes the target ? https://github.com/prometheus/client_golang/blob/master/prometheus/examples_test.go#L237


Anyway, thanks for the help! Grouping key would resolve my usecase.

**Comment by brian-brazil** [comment]
> So, the usecase in the Go client is adding the fixed custom label per process when prometheus scrapes the target (instead of pushgateway) ? 

No, it's when some subsystem is re-using the metrics of another library and is running a few copies of it do to sharding/whatever and wishes to differentiate the metrics from the different copies. It's not correct to set a label/prefix on an entire target.

**Comment by Ashish-Bansal** [comment]
> it's when some subsystem is re-using the metrics of another library and is running a few copies of it do to sharding/whatever and wishes to differentiate the metrics from the different copies

Okay, that's the reason why `WrapRegistererWith` will be deprecating `ConstLabels`, since one will be able to create multiple registries adding different const labels for those metrics in a single process which won't be cleaner with `ConstLabels`. cool!
