### ISSUE TITLE
Make _INITIAL_MMAP_SIZE configurable and/or part of public API

### ISSUE THREAD

**Issue by xavfernandez** [prometheus/client_python#426]
We tend to create a lot of processes leading to lot of metrics files lying around (around 30k pids used in a week).
With each file taking initially 1MB, this leads to 30GB of used space, mainly containing zeroes.

An easy fix was to monkey-patch `prometheus_client.core._INITIAL_MMAP_SIZE` and set it to 1kB instead.

It works perfectly but apparently the import moved and is now `prometheus_client.mmap_dict._INITIAL_MMAP_SIZE`.
We'll update it (and add an assert to check for its next move ^^) but it would be cleaner if this was officially configurable.

**Comment by brian-brazil** [comment]
That's not how the client works, you should have no more than a few MB of vitrual memory used at a time.

**Comment by xavfernandez** [comment]
> That's not how the client works, you should have no more than a few MB of vitrual memory used at a time.

I'm not sure I follow. We are using multiprocess mode which write mmap to files (as far as I understand), and on one of our server that's what I see:
```
$ ls -sh /tmp/prometheus_metrics/ | wc -l
52446
$ ls -sh /tmp/prometheus_metrics/ | head
total 205M
4.0K counter_10022.db
4.0K counter_10037.db
4.0K counter_10062.db
4.0K counter_10098.db
4.0K counter_1011.db
4.0K counter_10160.db
4.0K counter_10161.db
4.0K counter_10174.db
4.0K counter_10217.db
```

**Comment by brian-brazil** [comment]
Ah, you mean disk space rather than memory. I'd expect those files to be sparse, you can check with `du`.

**Comment by xavfernandez** [comment]
> Ah, you mean disk space rather than memory. I'd expect those files to be sparse, you can check with du.

My bad, you are right, I had only checked with ls:
```
$ du -h test
4.0K    test
$ ls -lh test
-rw-r--r-- 1 xfernandez users 2.0M Jun 13 15:01 test
```
So my monkey-patch and this issue were useless, sorry for the noise :-/
