### ISSUE TITLE
Prometheus counters disappears !

### ISSUE THREAD

**Issue by h4ckroot** [prometheus/client_python#432]
Hello,
I have a small python service, which I am using for capturing some events from another system and publish these events as Prometheus metrics. The service is simple !. It uses flask for exposing APIs for external systems, and based on hits on the API, it will increase the count of the corresponding prometheus counter. I am also using uwsgi, along with Nginx. The service looks like the below code. My problem is, I can fetch the metrics from Prometheus easily, but after a while (hours), the counters seem to disappear, and when I curl the metrics endpoint, I can see only the description of the metric, and no values at all!

from flask import Flask, Response, Request, request
import prometheus_client
from prometheus_client import start_http_server, Counter, Summary

CONTENT_TYPE_LATEST = str('text/plain; version=0.0.4; charset=utf-8')

SERVICE_RESPONSE_CODE_2xx = Counter('service_response_code_2xx_total',
        'service response code 2xx triggered.',
        labelnames=['service', 'code'])

app = Flask(__name__)
@app.route('/service/response-code/2xx', methods=['POST'])
def service_response_code_2xx():
    code = request.json['code']
    service = request.json['service']
    service_RESPONSE_CODE_2xx.labels(service,code).inc()
    LOG_TOTAL_REQUESTS.labels(service).inc()
    return 'OK', 200

@app.route('/metrics')
def metrics():
    return Response(prometheus_client.generate_latest(), mimetype=CONTENT_TYPE_LATEST)

if __name__ == '__main__':
    app.run()

**Comment by brian-brazil** [comment]
I suspect you want multi-process mode.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by h4ckroot** [comment]
Thanks for your guidance. I have opened a new topic on the same. Please note, that in my case I am not trying to use a multi-process, as I am using a single process for uwsgi. Also, I have noticed that at the time of the disappearnce of the metrics, a garbage collection event happens !. If you can shed some light, that would be really appreciated.
