### ISSUE TITLE
Default metrics (cpu, ram etc...) with MultiProcessCollector ?

### ISSUE THREAD

**Issue by noam1610** [prometheus/client_python#433]
Hello,

When using the MultiProcessCollector with gunicorn, we loose all the default metrics like cpu, ram etc ...

Is there a way to have these metrics even with MultiProcessCollector  ?

Thanks

**Comment by brian-brazil** [comment]
There isn't, and they wouldn't be of much use.

**Comment by aolsux** [comment]
I actually want to have exactly that: individual memory usage of my sub processes.
Up to now, i simply log the sub-process memory with `psutil.Process(os.getpid()).memory_info().rss`.
It would be nice to extend the libraries functionality to support that. Here are my thoughts about it:

### Target Scenario
Multiple sub processes each exposing its individual process metrics with the ProcessCollector on one single port from the parent process.

### Idea: Proxy Collector with `multiprocessing.Manager` or `Pipe`
As the collector would be created in the subprocess (i.e. after forking from parent) it is not available in the parent process where the main registry is exposed.

To overcome this I could image a proxy collector which gets registered in the parent process. This proxy collector can communicate with the sub process collectors e.g. via a multiprocessing pipe.

This way, communication between processes only takes place, when the endpoint in the parent is actually scraped.

This approach however, may lead to the following problem: If multiple Collectors exist in child processes which use the same metrics (same name, and set of labelnames) but different labelvalues, the parent registry may complain about duplicates. Ultimately, this means, that duplicates can only be checked upon collect, and not upon register.

**Comment by brian-brazil** [comment]
That doesn't quite work, what if for example one of the children was doing something blocking?

**Comment by aolsux** [comment]
Well, of course within the subrocess, the metric proxy to the parent process has to run in its own thread.

**Comment by brian-brazil** [comment]
This isn't something we can do generally I'm afraid.
