### ISSUE TITLE
File write error that seems to be unique to both docker and my system

### ISSUE THREAD

**Issue by jeffreyt** [prometheus/client_python#437]
Seeing the below error trace from trying to set up a gauge in my main.py.  Weird thing is I'm literally only seeing it on my system in a docker container.  Not seeing on other dev systems and on cloud cluster.  Also very strange, when it seems to work on other machines I don't even see the `tmp` directory being used at all.   

Sorry I hope this is not too obscure as it has to do with docker but any help would be appreciated.
```
Traceback (most recent call last):
  File "./main.py", line 28, in <module>
    "My Gague",
  File "/usr/local/lib/python3.7/site-packages/prometheus_client/metrics.py", line 324, in __init__
    labelvalues=labelvalues,
  File "/usr/local/lib/python3.7/site-packages/prometheus_client/metrics.py", line 102, in __init__
    self._metric_init()
  File "/usr/local/lib/python3.7/site-packages/prometheus_client/metrics.py", line 331, in _metric_init
    multiprocess_mode=self._multiprocess_mode
  File "/usr/local/lib/python3.7/site-packages/prometheus_client/values.py", line 49, in __init__
    self.__reset()
  File "/usr/local/lib/python3.7/site-packages/prometheus_client/values.py", line 63, in __reset
    files[file_prefix] = MmapedDict(filename)
  File "/usr/local/lib/python3.7/site-packages/prometheus_client/mmap_dict.py", line 61, in __init__
    self._f = open(filename, 'rb' if read_mode else 'a+b')
FileNotFoundError: [Errno 2] No such file or directory: 'tmp/prometheus_cache/gauge_all_13.db'
```

**Comment by brian-brazil** [comment]
What version are you using, what filesystem, and do you have something deleting files?

**Comment by jeffreyt** [comment]
Thanks for replying, I'm using prometheus_client 0.7.0, the filesystem is overlay and I don't think I have anything that would delete files.  I simplified my code to just setup the Gauge, start the http server and measure running in a loop that sleeps a bit.

I mentioned identical code seems to be running fine on other devs systems so, one thing I was wondering is if the `tmp/prometheus_cache` is always created or if it is used differently depending on operating system or other externals?

**Comment by brian-brazil** [comment]
It doesn't vary based on OS/filesystem, so I'm wondering if you've a filesystem that's not behaving as expected.

**Comment by jeffreyt** [comment]
So when everything is working normally, should I see the `tmp/prometheus_cache` directory and files within generated?  And is it cleaned up afterwards?  I don't think I have seen it in the case when it has been working.

**Comment by brian-brazil** [comment]
There should be files in it, and it's up to you to wipe it.

**Comment by brian-brazil** [comment]
This has gone stale, if this is still happening let us know.
