### ISSUE TITLE
`CollectorRegistry(auto_describe=True)` problem - registry with auto_describe does not proccess several metrics properly.

### ISSUE THREAD

**Issue by amadeuszkryze** [prometheus/client_python#444]
Hi, I'm working on modified version of [django-prometheus](https://github.com/korfuri/django-prometheus) that is able to send metrics to pushgateway. I've encountered very strange problem - once registry is initialized with `auto_describe` it does not store metrics defined like:

```
requests_by_view_transport_method = Counter(
    'django_http_requests_total_by_view_transport_method',
    'Count of requests by view, transport, method.',
    ['view', 'transport', 'method'],
)
```
in fact once metrics also are served like:
```
from prometheus_client import make_wsgi_app
from wsgiref.simple_server import make_server

app = make_wsgi_app()
httpd = make_server('', 8000, app)
httpd.serve_forever()
```
those metrics are present, but once doing
```
def PushMetrics(registry, name="django"):
    push_to_gateway(
        f"{settings.PUSHGATEWAY_HOST}",
        job=name,
        grouping_key={
            'container': socket.gethostname(),
            'service': settings.SERVICE,
        },
        registry=registry,
    )

PushMetrics(prometheus_client.REGISTRY, f"django-info")
```
they are not visible in `pushgateway:port/metrics`

**Comment by brian-brazil** [comment]
Firstly, this is not a recommended use of the pushgateway.

Secondly, have you checked exactly what's going on in the pgw interaction?

**Comment by amadeuszkryze** [comment]
Ok, maybe it's not recommended use of pushgateway but it works and I haven't found anything at least promising - so I chosen pgw.

I've debugged it a little and I've found that creating custom registry without `auto_describe` and applying those registery to metric definitions works perfectly with pushing to pgw.

btw. the problem that I'm trying to solve requires gathering metrics from swarm services like scaled python apps, so I'm not able to gather data in 'usual prometheus way' - to scrape every swarm task separately, because swarm LB routes the traffic to random tasks..

**Comment by brian-brazil** [comment]
Sounds like you need a swarm SD.

**Comment by amadeuszkryze** [comment]
If you could link me some article that speaks about gathering application metrics from swarm and swarm SD I'd be thankful. I'm researching this topic since 2months and pgw it the best what I've found so far. 
PS1 why usage is pgw is not recommended? 😅
PS2 this is still bug in pgw - it does not push all metrics while in autodiscovery mode, what do we do about it?

**Comment by brian-brazil** [comment]
https://prometheus.io/docs/practices/pushing/

Where the bug is here is not determined.

**Comment by amadeuszkryze** [comment]
Ok, so I've made my research, now prom instance is running within swarm and it uses `dns_sd_configs` to get container list. Fun fact - still does not work as suppose. The metric `requests_by_view_transport_method` (mentioned earlier) is still not correctly gathered by Swarm Prometheus scrape. However metrics is present in containers metrics when manually reached `container:port/metrics` any ideas?

Swarm prom config
```
global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'PROMETHEUS'
    scrape_interval: 15s
    static_configs:
      - targets:
        - 'localhost:9090'

  - job_name: 'django-some-backend'
    dns_sd_configs:
    - names:
      - 'tasks.XXX-YYY-ZZZ-swarm_some-backend'
      type: 'A'
      port: 10000
```

**Comment by brian-brazil** [comment]
Sounds like you there's something multi-process going on, or tricky networking.

**Comment by amadeuszkryze** [comment]
Yes it was exactly multi-process issue, thanks for help, I've found what i was looking for. I discovered that prom_client http server was not really working with django middleware metrics 😅 that should be highlighted somewhere (in fact it is but deep in code). Closing, thanks for help.
