### ISSUE TITLE
Missing gauge metrics for labels only used in subprocess

### ISSUE THREAD

**Issue by aolsux** [prometheus/client_python#446]
When using the multiprocess collector and gauges, the exposed metrics only list those gauges that  have labels set in the parent process. Output of test case:

```
# HELP some_gauge Multiprocess metric
# TYPE some_gauge gauge
some_gauge{labelname="labelvalue",pid="1493"} 1.0
some_gauge{labelname="labelvalue",pid="1503"} 0.0
some_gauge{labelname="sub-process",pid="1503"} 2.0
# HELP some_gauge Some Description
# TYPE some_gauge gauge
some_gauge{labelname="labelvalue"} 1.0
```
I would expect at least the following additional line:
```
some_gauge{labelname="sub-process"} 2.0
```
Test case for reproducing (prometheus-client 0.7.1, Python 3.7.3)
```
# NOTE: Do not import any prometheus modules here, as that may initialize some of the static variables while
#       the prometheus_multiproc_dir environment variable is not yet set.
import multiprocessing
import os
import shutil
import time
from multiprocessing import current_process
from unittest import TestCase


class TestMultiProcessPrometheus(TestCase):

    @classmethod
    def setUpClass(cls) -> None:
        os.environ.update({"prometheus_multiproc_dir": "/tmp/prom"})

    def setUp(self) -> None:
        if os.path.exists("/tmp/prom"):
            shutil.rmtree("/tmp/prom")
        os.makedirs("/tmp/prom")

    def test_multiprocessing_gauge(self):
        import prometheus_client
        from prometheus_client.multiprocess import MultiProcessCollector
        from prometheus_client.registry import CollectorRegistry
        from prometheus_client import generate_latest

        gauge = prometheus_client.Gauge("some_gauge", "Some Description", labelnames=["labelname"], registry=None)
        registry = CollectorRegistry()
        MultiProcessCollector(registry=registry)
        registry.register(gauge)

        gauge.labels("labelvalue").set(1)

        def subprocess():
            gauge.labels("sub-process").set(2)

        process = multiprocessing.Process(target=subprocess)
        process.start()
        process.join()

        text = generate_latest(registry).decode('utf-8')
        print(text)
        self.assertIn('some_gauge{labelname="labelvalue"} 2.0', text.split('\n'))
```

**Comment by brian-brazil** [comment]
This is working as I'd expect, however your usage isn't sane. In particular `registry.register(gauge)` is incorrect, only the MultiProcessCollector should be in that registry not any direct instrumentation.

**Comment by aolsux** [comment]
Well, if I only register the `MultiProcessCollector` no metrics will ever end up in the registry, unless i use the default `REGISTRY` for the gauge.

Still, event with correct usage how is that the expected behavior? If process A (parent) uses labelvalue "A" and process B (child) used value "B", why is only the A metric exposed and B silently dropped?

I consider the `MultiProcessCollector` as a reduce operation grouped by metric name and label values. I.e. every combination of name, and labelnames should result in a reduced metric. Where am I thinking wrong?

**Comment by brian-brazil** [comment]
> Well, if I only register the MultiProcessCollector no metrics will ever end up in the registry, unless i use the default REGISTRY for the gauge.

That's not how multiprocess mode works, it's eschews normal registries.

> why is only the A metric exposed and B silently dropped?

I don't see anything being dropped here.

**Comment by aolsux** [comment]
I think i get it now. I took the 
```
some_gauge{labelname="sub-process"} 2.0
```
as the "main metric of interest" and assumed the 
```
some_gauge{labelname="sub-process",pid="1503"} 2.0
```
metrics more detailed and considered for internal use. I guess instead i should consider those as the metrics of interest. 

One more thing:
In my usecase it would be nice to allow custom labename and value instead of `pid=XYZ` as all my processes have names matching their purpose (they are not all just "worker"). Ill get back to you if i manage to integrate such functionality into the `MultiprocessCollector` class :)
Thanks!
