### ISSUE TITLE
Using multi prometheus replica in K8s scraping from external end point using custom collector

### ISSUE THREAD

**Issue by atangger** [prometheus/client_python#449]
I am trying to implement a metrics agent which allow reporting previous metrics data with timestamp.
It seems that I have to use CustomCollector.
But when I use the following code, it seems that I got two metrics with the same name and label. I have two Prometheus instance running in the K8s cluster and I can see that each time of scraping the CustomCollector is called two times.
```
from prometheus_client import start_http_server, Summary, Gauge
from prometheus_client.core import GaugeMetricFamily, CounterMetricFamily, REGISTRY
from prometheus_client.registry import CollectorRegistry
import random
import time


class CustomCollector(object):
    def collect(self):
        print("Start collector")
        global ga
        c = GaugeMetricFamily('my_god_gauge132', 'Help text', labels=['foo'])
        c.add_metric(['bar'], random.randint(0,100))
        yield c
# Decorate function with metric.
@REQUEST_TIME.time()
def process_request(t):
    """A dummy function that takes some time."""
    time.sleep(t)

if __name__ == '__main__':
    # Start up the server to expose the metrics.
    start_http_server(9400)
    REGISTRY.register(CustomCollector())
    # Generate some requests
    while True:
        process_request(random.random())
```
![Screen Shot 2019-08-11 at 11 19 57 AM](https://user-images.githubusercontent.com/22708039/62838001-2f054180-bc2b-11e9-8c82-c08404209f18.png)
![Screen Shot 2019-08-11 at 11 20 03 AM](https://user-images.githubusercontent.com/22708039/62838002-30cf0500-bc2b-11e9-86f8-80133cdffa89.png)

It seems that the union of those two metrics have all of the data, but I am curious why this is happening.

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by atangger** [comment]
@brian-brazil I believe this is related to the implementation of CustomCollector, there are some race condition if multi Prometheus trying to scrape from the server using CustomCollector. So it will end up with duplicate metrics.
