### ISSUE TITLE
Facilitate sharing of collectors

### ISSUE THREAD

**Issue by AndreLouisCaron** [prometheus/client_python#450]
Hi there!

Thanks for this library, it's been quite useful to me team and I :-)

I have a use case where mutltiple [Pyramid](https://docs.pylonsproject.org/projects/pyramid/en/latest/) applications are hosted in the same process.  While trying to expose a histogram metric for HTTP request duration, I noticed that each Pyramid application tries to create the "same" `prometheus_client.Histogram` object while sharing a single `prometheus_client.CollectorRegistry` for the whole process.

Unfortunately, this is not allowed.  I can easily reproduce the behavior:

```python
>>> import prometheus_client
>>> r = prometheus_client.CollectorRegistry()
>>>
>>> h1 = prometheus_client.Histogram(
...    'http_request_duration_seconds',
...    'HTTP request duration in seconds',
...    registry=r,
... )
>>> print(h1)
<prometheus_client.metrics.Histogram object at 0x000001746C91A320>
>>>
>>> h2 = prometheus_client.Histogram(
...     'http_request_duration_seconds',
...     'HTTP request duration in seconds',
...     registry=r,
... )
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "…\lib\site-packages\prometheus_client\metrics.py", line 499, in __init__
    labelvalues=labelvalues,
  File "…\lib\site-packages\prometheus_client\metrics.py", line 107, in __init__
    registry.register(self)
  File "…\lib\site-packages\prometheus_client\registry.py", line 29, in register
    duplicates))
ValueError: Duplicated timeseries in CollectorRegistry: {'http_request_duration_seconds_count', 'http_request_duration_seconds_created', 'http_request_duration_seconds_bucket', 'http_request_duration_seconds_sum'}
```

I understand why duplicate time series are not allowed -- clearly, that wouldn't make sense for Prometheus when collecting the metrics.

I also understand that deploying multiple applications in the same process is not recommended in a microservices architecture.  However, this pattern is quite common in Python code bases and it's quite useful for us to keep this behavior during our transition away from a monolithic deployment to microservices.

I currently work around this problem within something like this:

```python
>>> import prometheus_client
>>>
>>> def get_collector(t, n):
>>>     collectors = set(r._collector_to_names.keys())
>>>     for c in collectors:
>>>         if c._type != t:
>>>             continue
>>>         if c._name != n:
>>>             continue
>>>         return c
>>>     raise ValueError('collector not found')
>>> 
>>> r = prometheus_client.CollectorRegistry()
>>> 
>>> h1 = prometheus_client.Histogram(
>>>     'http_request_duration_seconds',
>>>     'HTTP request duration in seconds',
>>>     registry=r,
>>> )
>>> print(h1)
<prometheus_client.metrics.Histogram object at 0x000001C5363FAC88>
>>>
>>> h2 = get_collector(
>>>     'histogram',
>>>     'http_request_duration_seconds',
>>> )
>>> print(h2)
<prometheus_client.metrics.Histogram object at 0x000001C5363FAC88>
>>>
>>> assert h1 is h2
```

In short, using this pattern, we can "create-or-resolve" a given collector and everything works out just the way we wanted.

However, I'm not super comfortable with this implementation because it means my app depends on implementation details of `prometheus_client`.  I hope we can work something out to get a public API for this use case.

It seems to me like this is only limited by an API design choice: applications instantiate the collector objects directly.  If they were using some kind of caching factory pattern like this, then we'd get the best of both worlds:

```python
h = registry.histogram(
    'http_request_duration_seconds',
    'HTTP request duration in seconds'
)
```

Would you willing to accept a change to the library that adds such an API?  I'm willing to put some effort into a PR if you're open to it.

Thanks in advance :-)

**Comment by brian-brazil** [comment]
This is by design, metrics almost never be shared across different pieces of code. If you think you want this then either move the metric up the call stack, or name your metric more uniquely.

**Comment by AndreLouisCaron** [comment]
Thanks for your quick feedback :-)

Unfortunately, I've already tried (and failed) at both those things.

> move the metric up the call stack

This is functionally equivalent, but syntaxically impossible in this context: the pieces of code that initialize the multiple WSGI applications do not share a call stack I control (or that should even be aware of Prometheus metrics).

> or name your metric more uniquely

I assume you mean something like putting them in separate namespaces?  This creates multiple issues:

1. we can no longer get a single view on all apps  (due to use of a namespace rather than a label); and
2. once we complete our transition to microservices, we'll no longer need the multiple namespaces for this metric, so we'll need to update all our dashboards & alerts.

**Comment by brian-brazil** [comment]
> the pieces of code that initialize the multiple WSGI applications do not share a call stack I control (or that should even be aware of Prometheus metrics).

Sounds like you should add a router so that you can add the metrics.

**Comment by AndreLouisCaron** [comment]
Listen, I was offering some help to add syntactic sugar for what seems to somewhat common pattern in Python applications.  Seems like you're not interested, so I will continue using my workaround.
