### ISSUE TITLE
[Question] Globally configuring namespace and subsystem

### ISSUE THREAD

**Issue by sidps** [prometheus/client_python#456]
Is it possible to configure a global namespace and subsystem, instead of using these as arguments while creating a given metric? My current workaround is to pass these configs around all over the codebase.

**Comment by brian-brazil** [comment]
It isn't. You shouldn't be passing these around, as a metric name is about a line of code not a binary. I'd generally recommend hardcoding the full name as needed, it makes grepping easier.

**Comment by sidps** [comment]
How do I go about this with shared libs? I'm writing a kafka client that will be used across several applications. Using the namespace/subsystem notion maps well onto how these applications are setup in kubernetes. This could perhaps be accomplished through labels instead of the metric name prefixes, but this isn't exactly how labels were meant to be used and perhaps constitutes [overuse](https://prometheus.io/docs/practices/instrumentation/#do-not-overuse-labels).

**Comment by brian-brazil** [comment]
That's something for target labels, and not anything your code needs to worry about.
