### ISSUE TITLE
Expose metrics to a different configurable path (rather the default /metrics )

### ISSUE THREAD

**Issue by salehdeh76** [prometheus/client_python#458]
Is it possible to expose the metrics (the `start_http_server` method) to another path?

For example I want to use this path : http://192.168.56.102:9800/mycustommetrics
instead of the default http://192.168.56.102:9800/metrics

**Comment by brian-brazil** [comment]
start_http_server is meant to be simple to get you going quickly, you can use it as a base to write your own more custom handling.
