### ISSUE TITLE
Python runtime metrics

### ISSUE THREAD

**Issue by jzelinskie** [prometheus/client_python#473]
Hey there,

The Go client library includes some metrics on the language runtime by default. Perhaps we could do the same with Python. A quick search yielded [this package] which includes some basic metrics from the `gc` package. Is there any additional logic that we'd need to consider to support the multiprocess/gunicorn mode?

[this package]: https://github.com/korfuri/python-gc-prometheus

**Comment by brian-brazil** [comment]
We already expose all that we can I believe in terms of runtime stuff, unfortunately Python doesn't have that much.

**Comment by jzelinskie** [comment]
Oh -- I didn't even notice [this file](https://github.com/prometheus/client_python/blob/master/prometheus_client/gc_collector.py). The codebase I was working in wasn't even using this library, just mimicking it. 🤦‍♂ No wonder we didn't have these metrics.

Thanks Brian
