### ISSUE TITLE
query parser

### ISSUE THREAD

**Issue by eranreshef** [prometheus/client_python#484]
Is there any way (pythonic or not) to parse a promql query and extract all the metrics being used in it?

Thanks.

**Comment by brian-brazil** [comment]
No, you'd have to work from the Go parser for this.

**Comment by eranreshef** [comment]
Thanks @brian-brazil . Any plans or thoughts on adding such functionality to promtool or the client libraries? It could be useful.

**Comment by brian-brazil** [comment]
There's no plans for that.

**Comment by eranreshef** [comment]
🤷‍♂️
