### ISSUE TITLE
Need to create a custom metric to host data to Prometheus default port using .NET

### ISSUE THREAD

**Issue by Srivaniausali** [prometheus/client_python#485]
Hi
I am new to Prometheus Dataserver.
as per my understanding Counter, gauge, Summary, Histogram are 4 standard type of metrics in Prometheus.
But, I want to Create the customized metric based on my data and reporting needs using .net(c#).
I got the equivalent to create customized metric in Python that is : UnknownMetricFamily

"""EXAMPLE 2"""

class mycollector(object):
def collect(self):
mf = UnknownMetricFamily("citrix7subnets", "gives count of subnets",labels=["farm", "sunbnet", "location", "Ddcname"])
mf.add_metric(["Xendesktop", "LAN", "Hyderabad", "hdc"], 1)
yield mf

	"citrix7subnets" is my Metric/measurement name 
	"farm", "location", "Ddcname"  are my Tag keys 
	"sunbnet" is my Field key
if name == 'main':
REGISTRY.register(mycollector())
start_http_server(8080)
while True:
time.sleep(1)

where as I need this equivalent to create customized metric in .net.
Is this the correct way to achieve my requirement? or Do we have any other alternate to proceed further. 
Could you please on this . Thanks in advance.

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by Srivaniausali** [comment]
> It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

tqs for the info :-)
