### ISSUE TITLE
Import data from a file and export it to Prometheus

### ISSUE THREAD

**Issue by lorentinoooo** [prometheus/client_python#488]
I want to know how I could get to import data from a text file and then export it to Prometheus. I've done a piece of code that it works but at the moment I try to display the values in Prometheus, it only shows one value and not all of them as I would like. Next, I attached some pictures about the code and what Prometheus do, just to show you a little bit. I don't really know what is wrong to not obtain what I want. The problem is like Prometheus was not able to process such amount information in short amount of time. It only plots the first value. Besides, collect function is called more than once and it keeps plotting the same value again and again.

```
import os, time

from prometheus_client import start_http_server
from prometheus_client.core import GaugeMetricFamily, REGISTRY

class getParameters(object): # read some parameters from a given file and store them in a Gauge 
    def __init__(self, param):
        self.param = param

    def _readSheet(self):
        thgpt = GaugeMetricFamily('TFM_throughpt', 'Throughpt Measure', labels=['IP','module'])
        for file in os.listdir("."):
            if os.path.isfile(file) and file.startswith("test_", 0, 5):
                try:
                    with open(file,'r',encoding = 'utf-8') as f:
                        line = f.readline()
                        while line:
                            if line:
                                aux = line.split(" ")
                                if ('Thgptup:' in line):
                                    thgpt.add_metric([self.param, 'Upload'],float(aux[1]))
                                elif ('Thgptdown' in line):
                                    thgpt.add_metric([self.param, 'Download'],float(aux[1]))
                                elif ('Thgpt' in line):
                                    thgpt.add_metric([self.param, 'Overall'],float(aux[1]))
                                line = f.readline()

                        yield thgpt

                except Exception as f:
                    print(f)

    def _getParam(self): #just read the sample which has been stored in the  Gauge above
        for data in self._readSheet():
            yield data

    def collect(self):
        for x in self._getParam():
            yield x

        yield GaugeMetricFamily('my_gauge', 'Help text', value=7)

param = 'localhost'
REGISTRY.register(getParameters(param))
print ('Reading is Done!')
start_http_server(8000)

try:
    wait_time = 20.0
    while True:
        time.sleep(wait_time)
except KeyboardInterrupt:
    pass
```
![Captura de pantalla 2019-11-14 a las 22 28 33](https://user-images.githubusercontent.com/48497789/68948894-35223580-07b9-11ea-8a80-d8ee3f4a352a.png)
![Captura de pantalla 2019-11-14 a las 22 28 51](https://user-images.githubusercontent.com/48497789/68948896-35223580-07b9-11ea-80cb-f2d7057adee9.png)

and next you can see what I really want to obtain:

![Captura de pantalla 2019-11-14 a las 22 33 02](https://user-images.githubusercontent.com/48497789/68948898-35223580-07b9-11ea-98cd-29c92096b81f.png)

Does anyone help me out with this task, please? I really appreciate your help.
Thanks in advance guys.

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
