### ISSUE TITLE
Allow GraphiteBridge to set a prefix

### ISSUE THREAD

**Issue by hynek** [prometheus/client_python#49]
Hi,

while testing and maybe transitioning, I’m very grateful for the GraphiteBridge.

However as far as I can tell, there’s no way to namespace (with a dot) my metrics and they just land in the main “directory”.

Could you please add a way to set a prefix that is prepended to all metrics?

**Comment by brian-brazil** [comment]
That sounds like a reasonable and simple request, I'll add it to the Hacktoberfest list.

**Comment by kvikas** [comment]
Hi Brian,

I was looking into this. Does this mean `bridge.graphite.GraphiteBridge.push()` needs an optional namespace parameter? And it gets `_sanitize()`ed with `.` preserved and prepended to name.

**Comment by brian-brazil** [comment]
I'd add an optional `prefix` parameter so as not to confuse it with the `namespace` parameter that Prometheus client libraries have. I'm not sure there's any need to sanitize it, as it's provided by a user that knows that it's going to graphite and what storage backend they have - unlike normal label values which can be arbitrary Unicode.

**Comment by brian-brazil** [comment]
Fixed by #56

**Comment by hynek** [comment]
Sweet, thanks!
