### ISSUE TITLE
Multiprocessing collector doesn't work

### ISSUE THREAD

**Issue by Sayed-Soroush-Hashemi** [prometheus/client_python#490]
### version
prometheus_client==0.7.1

### How to reproduce
```python
import json
import os
import time
from multiprocessing import Pool
from concurrent.futures import ThreadPoolExecutor, ProcessPoolExecutor 

from prometheus_client import Counter, CollectorRegistry, multiprocess, start_http_server, generate_latest

os.environ['prometheus_multiproc_dir'] = './tmp_test' 

registry = CollectorRegistry()
multiprocess.MultiProcessCollector(registry)

counter_1 = Counter('name_counter_1', '', ['l1', 'l2'], registry=registry)

def f(i):
	while True:
		counter_1.labels(f'l1_val_{i}').inc()
		print(f'process {i}')
		print(generate_latest(registry).decode('utf-8'))
		time.sleep(i+1)

def test_multiprocessing_pool():
	with Pool(2) as p:
		p.map(f, [1, 2])

def test_process_pool_executor():
	with ProcessPoolExecutor(2) as p:
		p.map(f, [1, 2])

def test_thread_pool_executor():
	with ThreadPoolExecutor(2) as p:
		p.map(f, [1, 2])


if __name__ == '__main__':
	# test_multiprocessing_pool()
	test_process_pool_executor()
	# test_thread_pool_executor()

```
### what I see
Each process collects only its own metrics when using `ProcessPollExecuter` and `multiprocessing.Pool`, but it works correctly when using `ThreadPoolExecutor`.
```text
process 1
# HELP name_counter_1_total 
# TYPE name_counter_1_total counter
name_counter_1_total{l="l_val_1"} 2.0
# TYPE name_counter_1_created gauge
name_counter_1_created{l="l_val_1"} 1.575303633967081e+09

process 2
# HELP name_counter_1_total 
# TYPE name_counter_1_total counter
name_counter_1_total{l="l_val_2"} 2.0
# TYPE name_counter_1_created gauge
name_counter_1_created{l="l_val_2"} 1.5753036339671488e+09
```
### what I expect
Each process should be able to collect all the metrics in all the processes.

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by Sayed-Soroush-Hashemi** [comment]
Sorry. I don't know the conventions here.

**Comment by Sayed-Soroush-Hashemi** [comment]
Looks like the same question was asked before in the mailing list. [Here](https://groups.google.com/d/msg/prometheus-users/y2HpXDvVqLU/9Qzn67E2BgAJ) 's the question. In short, the answer is this: environment variables that set using `os.environ` don't propagate into the child processes. So the code I sent [above](https://github.com/prometheus/client_python/issues/490#issue-531245740) can be fixed by removing the `os.environ['prometheus_multiproc_dir'] = './tmp_test'` line and setting the environment variable with `export prometheus_multiproc_dir=./tmp_test` before running the process.
