### ISSUE TITLE
Type hint stubs

### ISSUE THREAD

**Issue by paravoid** [prometheus/client_python#491]
It'd be awesome if client_python was type hinted, as that would allow downstream consumers to typecheck their API calls (one has to explicitly `# type: ignore` the import right now).

My understanding is that the project is actively trying to support (very) old versions of Python. In this case, there are two options: a) type hints in comments b) type stubs (`.pyi`). The latter is preferrable; this can be shipped by either [typeshed](https://github.com/python/typeshed), or, ideally, [in the software itself](https://mypy.readthedocs.io/en/latest/installed_packages.html). For more about the pros and cons of each solution, I've found Bernat Gabor's [blog post](https://www.bernat.tech/the-state-of-type-hints-in-python/) to be informative.

Adding the hints across the entire code base is easy but still, not a trivial amount of work. Tools like [MonkeyType](https://github.com/Instagram/MonkeyType/issues) can help bootstrap that process. Given the good code test coverage, I tried running the test suite with MonkeyType (`monkeytype run -m pytest`) and it generated the majority of the hints. There were, however, some corner cases that it wasn't able to figure out or otherwise failed to generate, and I'm not familiar enough with the codebase to help with that.

Thanks & thanks for all of the work you've been putting on this module!

**Comment by brian-brazil** [comment]
This seems reasonable to add to the public bits of the API via comments.

> My understanding is that the project is actively trying to support (very) old versions of Python.

More that we're not going to drop them until they cause too much hassle, so far it has only been a little annoying.

**Comment by akx** [comment]
#718 dropped support for Python 2 altogether, so real type hints could now be added.

**Comment by paravoid** [comment]
I believe type hints now exist, so resolving this. Thanks!
