### ISSUE TITLE
Multiprocess - gauge metric continue to be reported after process exist

### ISSUE THREAD

**Issue by asherf** [prometheus/client_python#495]
Very similar to https://github.com/prometheus/client_python/issues/236 (well, basically the same...)
What I am seeing (added some logging before & after calling `multiprocess.mark_process_dead(worker.pid)`

And I am seeing this:
```
[REDACTED-POD_NAME gunicorn] [2019-12-13 23:34:04 INFO] child_exit start. pid=11 files=['counter_1.db', 'histogram_1.db', 'counter_12.db', 'counter_11.db', 'histogram_11.db', 'histogram_12.db', 'counter_13.db', 'histogram_13.db', 'gauge_all_1.db'] worker=<gunicorn.workers.sync.SyncWorker object at 0x7f544f110a90> server=<gunicorn.arbiter.Arbiter object at 0x7f544f1f6550>
[REDACTED-POD_NAME gunicorn] [2019-12-13 23:34:04 INFO] child_exit end. pid=11 files=['counter_1.db', 'histogram_1.db', 'counter_12.db', 'counter_11.db', 'histogram_11.db', 'histogram_12.db', 'counter_13.db', 'histogram_13.db', 'gauge_all_1.db']
```
The issue is, that not cleaning up those files (specifically, gauge_all_XXX) means that the metrics in them is being returned to prometheus even though the gunicorn process is no longer alive (and thus not updating the value).
this is a problem because we use the gauge to report a version number of an internal DB and we have a check (alert) to make sure we have the same version(value) across all of the pods (this runs in k8s) running this app.

@brian-brazil I think cleaning up those DBs is worth while, right now, my workaround is to do it from my app code (after `multiprocess.mark_process_dead(worker.pid)` returns)
but it feels to be that the client library should cleanup after itself...

I am happy to work on a PR/code to fix this if this is something you will consider merging.
Otherwise, feel free to close this issue.

**Comment by brian-brazil** [comment]
This behaviour is correct, if you wanted them not reported you'd use `liveall`.

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
