### ISSUE TITLE
why split data type into different files？

### ISSUE THREAD

**Issue by lee3164** [prometheus/client_python#517]
https://github.com/prometheus/client_python/blob/56a8a533d094d7c64881ec510b96a167d9da5786/prometheus_client/values.py#L60

I have a question? why we not store data that in a process into a common file? for example, process 1 store its data into a common file prom_1.db other than 4 db files(counter_1.db, histogram_1.db, summary_1.db, gauge_1.db) .

**Comment by brian-brazil** [comment]
Different types of metrics need different handling.

**Comment by lee3164** [comment]
> Different types of metrics need different handling.
why we store the metrics type into a mmap file？instead we store it into mmap file name

**Comment by brian-brazil** [comment]
I'm not seeing what you're getting at. Do you have a concrete suggestion?
