### ISSUE TITLE
Will there be any new release soon?

### ISSUE THREAD

**Issue by esanchezm** [prometheus/client_python#523]
Hi,

We're using this library in our systems, specifically for the Prometheus Pushgateway, and we just have a minor issue with the `grouping_key` that I found it's already resolved in the master branch. It was resolved in PR #442 (August 2019) but that (and many other fixes) weren't released in a new public version.

The latest released version is 0.7.1 on the 20 Jun 2019 and I'd like to know if there's any plan to do a new release that includes that and many other fixes. Can anyone tell me?

*Note*: _I know I could install a newest version from the git repository, but I'd like to avoid that. I think it would be beneficial for newcomers as well_

**Comment by brian-brazil** [comment]
There's a few things that might be changing on the OpenMetric front, so I'm holding off a bit until that's looking more solid.

**Comment by esanchezm** [comment]
I get your point but I still think that releasing all the patches and fixes done from August 2019 could be beneficial. Instead of waiting for some standards to be published or developed, couldn't you just do a release? What's exactly holding you  a newer version? Is it not backwards compatible? Just asking :)

**Comment by brian-brazil** [comment]
There may be small breaking-ish changes in OpenMetrics, so I'd prefer not to put out something that may turn out to be incorrect and thus misleading.

**Comment by alexandrevicenzi** [comment]
+1 for this, waiting for #483 to be released.

**Comment by luohao** [comment]
Is there an ETA for next release? I am also waiting for #483 .

**Comment by esanchezm** [comment]
I'm not familiar at all with the changes that @brian-brazil is pointing out but, if I could give him my opinion, I think he should follow the [RERO philosophy](https://www.wikiwand.com/en/Release_early,_release_often) to help avoiding frustration, create a better community and understand people's issues and needs are important. My case was easy to patch on the client side, but I think other people are affected. My 2 cents :smile:

**Comment by brian-brazil** [comment]
I'm hoping to do a release soon, but there's something broken with PyPy and Twisted that's causing our CI to fail that's stumping me. If anyone could help with that that'd be appreciated.

**Comment by brian-brazil** [comment]
Release is out.
