### ISSUE TITLE
Support set_function for Enum

### ISSUE THREAD

**Issue by asomers** [prometheus/client_python#526]
Gauges have a handy `set_function` that can be used to calculate the gauge's value on demand.  However, Enums do not.  So an exporter that uses both Gauges and Enums must still use a polling loop for the enums, even though it can calculate the Gauges' values on demand.  It would be handy of Enum had a `set_function` method, too.

**Comment by brian-brazil** [comment]
An exporter shouldn't be using Gauges or Enums, it should be using MetricFamilies which are created at each scrape.

**Comment by asomers** [comment]
Ok, I'm confused.  What is the library useful for besides exporters?  Probably you and I disagree on the definition of an exporter.

**Comment by brian-brazil** [comment]
An exporter is something that takes metrics from a 3rd party system and converts them to Prometheus format.

**Comment by asomers** [comment]
I always thought of an exporter as anything that publishes metrics, ala node_exporter, grok_exporter, etc.  So please tell me, why are MetricFamilies considered superior to Gauges and Enums?

**Comment by brian-brazil** [comment]
That is beyond the scope of issues on this bug tracker, if you're looking for how to write good instrumentation I'd suggest taking it up on the prometheus-users mailing list.

**Comment by asomers** [comment]
I disagree.  This really seems like a shortcoming of client_python's documentation.  For example, what is a Registry?  When does the `collect` method get called, and what is its contract?  Those are not explained in the README.

**Comment by brian-brazil** [comment]
Usage questions are best asked on the mailing list if you're trying to do something non-trivial.

**Comment by asomers** [comment]
I don't think I'm asking for anything unusual.  I simply don't understand how to use this library for lack of basic documentation.  Is there something I'm missing?  I don't see any documentation other than the README, and no links to external docs other than the Prometheus concepts.

**Comment by brian-brazil** [comment]
This issue was opened for a set_function for Enum, for which you have not presented a use case. Accordingly I am going to close this, you can use a custom collector if you really need it.

This issue tracker is not for usage questions as that doesn't scale, please use the mailing list.
