### ISSUE TITLE
Too many decimal places in output

### ISSUE THREAD

**Issue by mafagafogigante** [prometheus/client_python#53]
Some bibliography so it doesn't sound like pure opinion:

![how_many_decimal_places](https://cloud.githubusercontent.com/assets/8271090/10252703/ab91fd9c-690f-11e5-9988-625808be2be6.png)
[from Measuring the User Experience: Collecting, Analyzing, and Presenting Usability Metrics]

Also, Mathematica, Octave, MATLAB and other mathematical software hide some decimal places when it doesn't matter.

I get some lines like the following:

    request_processing_seconds_sum 9.3512252295
    request_latency_seconds_sum 15.77115141185

And I am suggesting that they get changed to:

    request_processing_seconds_sum 9.351
    request_latency_seconds_sum 15.771

How many decimal places we are going to use is open for discussion, but 10 seems **not** an OK decision for a final product.

---

There is also a need to define where we are going to perform the rounding (we could truncate, but rounding seems statistically fairer). It could be done in the ``_samples`` functions of the classes defined in core.py, but maybe there is a better place.

Thanks for reading.

**Comment by beorn7** [comment]
I can't speak for the Python library, but at least the Go client library represents floats in a way that exactly the same IEEE-754 representation is created on the server side. The Go client would naturally use protobuf between machines, so one could easily thing the text format is just informational and for humans. The Python client, however, only speaks the text format, so arguably it's made for machines, too.

**Comment by mafagafogigante** [comment]
I see. And if there are machines reading this output - I suppose there are, right? - it cannot be polished.

**Comment by brian-brazil** [comment]
The current output is a bit eager to use scientific notation, but we need as full precision as we can't predict user use cases (maybe they're measuring something in nanoseconds) and advertise 64bit float support.

Even if there were an output format intended entirely for humans, we'd still display as much precision as we could.

**Comment by mafagafogigante** [comment]
Understood. So this is going to stay as it currently is.
