### ISSUE TITLE
Cannot import the new module `make_asgi_app`

### ISSUE THREAD

**Issue by idob111** [prometheus/client_python#531]
I love your project and it's really helpful .
After doing `pip install prometheus_client`
When i try to import `make_asgi_app` the app could not recognize the module (while it does recognize the `make_wsgi_app`).
When I perform a local pip install  it does work.

Is there an option that the pip is not updated or am i doing something wrong?
tnx :)

**Comment by brian-brazil** [comment]
That hasn't made it into a release yet.

**Comment by denisSurkov** [comment]
Hi 

When are you going to release this awesome feature?

**Comment by brian-brazil** [comment]
I'm holding off on a release until some final OpenMetrics details are determined, as this is the reference client.

**Comment by NargiT** [comment]
any new for the release?

**Comment by brian-brazil** [comment]
As it stands I'm mainly blocked by the failing CI for twisted/asgi/pypy, so any help there would be appreciated.

**Comment by NargiT** [comment]
Can you provide the link of the failing build ? not able to find it in this repo

**Comment by brian-brazil** [comment]
Weird, it just started passing again after being broken for ~2 months.

**Comment by brian-brazil** [comment]
Release is out.
