### ISSUE TITLE
proposal: split parser into it's own library

### ISSUE THREAD

**Issue by alexandrevicenzi** [prometheus/client_python#533]
Hi,

It would be nice if [parser.py](https://github.com/prometheus/client_python/blob/master/prometheus_client/parser.py) was a library outside this client.

The use case would be, I want to parse files that I have stored, I don't need most of the code in the client (and twisted) because I'm only parsing files.

Here is a sample code that uses only parser.

```py
from prometheus_client import parser

fd = open('metrics', 'r')

for metric in parser.text_fd_to_metric_families(fd):
  print(metric)
```

Prometheus client would make use of Prometheus parser library, everything would still work as expected.

I'm willing to send a patch if this seems like a good idea.

**Comment by brian-brazil** [comment]
The library is purposefully self-contained with no dependencies, so you shouldn't need it split out. Twisted is optional.
