### ISSUE TITLE
Metric miss when setting the gauge value to zero

### ISSUE THREAD

**Issue by raul1991** [prometheus/client_python#539]
I use the python client for storing metrics for a user's online presence. For example when a user comes online I start counting seconds and then as soon as he goes offline ,I post the metric to grafana. Now after posting the online timespan I immediately need to update that user has gone offline so I set the metric value to 0.

The last update remains and the one value before it does not appear on grafana as prometheus metric show the last metric reading only (checked via /metrics)

# Steps to reproduce

# Example using a Gauge class in the client

- User 1 comes online for 20 seconds
- /metrics updated with 20seconds 
- Now set /metrics to 0 since user has gone offline.
- Earlier metric disappeared.

**Comment by raul1991** [comment]
Should I be using the counter instead and reset it to 0 as soon as the user goes offline ? Wouldn't this also result the same ?

Is it because of the scraping interval of prometheus. I mean when I reset it twice it was maybe done within the same scrape time interval so only the last update remained. Is it so ?
Any way around this problem ?

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by raul1991** [comment]
Can you add me there.I don't seem to have access to it

**Comment by raul1991** [comment]
> It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

Can you answer it here ?

https://groups.google.com/forum/m/#!topic/prometheus-users/8TNFERifd5Q

**Comment by raul1991** [comment]
Its been few days and no one has responded on the google groups. Can you look at it and answer if you know it ?
