### ISSUE TITLE
Names for gauge collectors

### ISSUE THREAD

**Issue by Lawouach** [prometheus/client_python#545]
Hello there,

I'm using the lastest master so I fully appreciate things are still under work. I just wanted to see if I'm miunderstanding something.

In https://github.com/prometheus/client_python/blob/master/prometheus_client/registry.py#L59, we have no entry for `"gauge"` types. Only `"gaugehistogram"` meaning no additional suffixes are added to gauges. Is that expected?

Thanks,
- Sylvain

**Comment by brian-brazil** [comment]
Yes, that's correct. Gauges have no suffix.

**Comment by Lawouach** [comment]
Haa. Thank you for clarifying :)
