### ISSUE TITLE
Broken metrics when updating to 0.8.0 because of appended units

### ISSUE THREAD

**Issue by Sebadst** [prometheus/client_python#553]
Hello,

I am having issues when updating the version of this library from `0.7.1` to `0.8.0` . I left a comment in [this pr](https://github.com/prometheus/client_python/pull/543#issuecomment-635332470) but I wasn't sure if you'll read closed PRs comments, therefore I decided to also open this issue.

I am not sure whether it is intended to have this behaviour with the unit appended again but, as an external developer, I find a bit weird that this is happening from version `0.7.x` to `0.8.x` given that it actually is a breaking change.
Could you please let me know your thoughts on the topic? 
Thank you

**Comment by brian-brazil** [comment]
Yes, that was the intention of the bugfix. `total` is not a sane unit, so this should not have broken anyone.

**Comment by Sebadst** [comment]
Ok, got it, thank you also for the promptness. I am closing the ticket then
