### ISSUE TITLE
Metric prefix addition during the output generation

### ISSUE THREAD

**Issue by pfreixes** [prometheus/client_python#571]
HI,

Seems that Prometheus client prescribes a pattern for declaring the metrics at module level, which has the good benefit of making it available quite straightforward by just importing that specific symbol, also allow the system to have it in memory - not deallocated by the GC - for the whole process time.

There is one downside effect by using that pattern, if we want to use the same code and metrics for many different services where the only thing that changes is the prefix of the metric and that prefix is only available at runtime - not load time - there is no way on adding this prefix to the already created metrics.

What do you recommend in this scenario?

Im wondering if we should create our own `Registry` - BTW is the class a public interface ? - and use the same instance in all of our metrics and when the data is gathered by `generate_latest` do something like this:

```python
from myregistry import REGISTRY
if REGISTRY.prefix is None
    REGISTRY.prefix = "fooservice"
generate_latest(REGISTRY)
```
Behind the scenes `REGISTRY` would override the `collect` metric or other and would mutate the metric name by adding the prefix that was configured.

WDYT?

Question? What would happen if we would have the same requirement for labels? so for example, if we would like to add some labels during the `generate_latest`? As an exmple of the lables that could be introduced for all of the metrics would be the pod name.

**Comment by brian-brazil** [comment]
See https://www.robustperception.io/target-labels-not-metric-name-prefixes

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
