### ISSUE TITLE
Scraping multiple entries of the same metric with different values

### ISSUE THREAD

**Issue by panos73** [prometheus/client_python#578]
Hello everyone ! I have the following question:
I have created a flask application that upon request in it's /metrics endpoint, retrieves specific values (strings) from Redis in the form 
**"test_service_metric{service="ui",component="graphs",env="mm"} 180"** , 

concatenates them according to prometheus exposition format (each entry separated by newline character and a line at the end), and finally returns in the Response a string like the following:

**"test_service_metric{service="ui",component="graphs",env="mm"} 160
 test_service_metric{service="ui",component="graphs",env="mm"} 170
 test_service_metric{service="ui",component="graphs",env="mm"} 180"**

So what i am actually trying to achieve, is prometheus to retrieve all these entries by scraping (which refer to the same metric but with different values) and display them in the console/graph. But what actually happens, is that only one of them actually shows in Prometheus.

Is there something i am doing wrong ? Or because the scrape time is the same for all these entries, all but one are regarded as duplicates and removed ?

Thanks in advance and please let me know for any clarifications !

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by panos73** [comment]
Correct. Thanks a lot.
