### ISSUE TITLE
When passing registry=None the metric won't work

### ISSUE THREAD

**Issue by NadavkOptimalQ** [prometheus/client_python#579]
We have a wrapping in our code that will either start serving over HTTP or use a push gateway. 
Both of the places in the code create the metrics objects using the same part of code that will pass registry=self._registry.
When we are working with with HTTP the self._registry will be None and thus cause the metric to not work.

Code to reproduce: 
```
from prometheus_client import start_http_server, Counter
import time

if __name__ == '__main__':
    c = Counter("CounterName", "CounterDoc", registry=None)
    start_http_server(8000)
    
    while True:
        time.sleep(3)
```

I understand that there is a default REGISTRY value for that param but I still think it shouldn't fail if I pass None. 
Is there a case where I would want to send a None registry? I don't see one and I think that if None is sent it should fall back to default

**Comment by brian-brazil** [comment]
This is the desired behaviour, passing a registry is only for convenience and thus optional. It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by NadavkOptimalQ** [comment]
Not to be rude or anything but do you actually maintain this or do you just refer people to the mailing list?

Is there a reason anyone would want to pass None as the registry?

**Comment by brian-brazil** [comment]
This is maintained, and if you had a bug report or feature request this would be the place to discuss those.

Usage questions however belong on the mailing list, as it's not practical to answer what is sometimes 10+ basic usage questions per day individually and in a place where the general community won't benefit from the answer.

**Comment by NadavkOptimalQ** [comment]
I think this is a bug since I don't see a case where you would want to have the registry=None but ok suit yourself
