### ISSUE TITLE
Is there a way to "extend" metric labels or add labels dinamically?

### ISSUE THREAD

**Issue by HMaker** [prometheus/client_python#580]
I have a class hierarchy of objects that do work in background, "workers". I need to track some metrics, like worker state (running, stopped, etc). I made an `Enum` metric for that with a label for the worker's name, but in the subclasses I need to add more labels to inform which kind of work that worker is doing, how can I do it?

**Comment by brian-brazil** [comment]
There's not, you'll have to manage that yourself. In general you shouldn't be passing metrics around though, they should almost always only exist inside one file.

**Comment by HMaker** [comment]
So I should create one new metric for each subclass that needs additional labels. Ok, thank you.
