### ISSUE TITLE
Registration within multiple registries

### ISSUE THREAD

**Issue by decaz** [prometheus/client_python#582]
I have several services within a single codebase and I have separate collector registry for each service. I also have common functionality (covered by metrics also) which is used by 2 or more services and there is need to register these metrics within several registries at once (for each service).

So suggestion is to make `registry` parameter of `MetricWrapperBase.__init__` to accept not only single `CollectorRegistry` instance but iterable of them:
```python
try:
    registries = iter(registry)
except TypeError:
    registries = (registry,)
for r in registries:
    if r:
        r.register(self)
```

**Comment by brian-brazil** [comment]
You can already manually register collectors to registries, given how exceedingly rare the use cases are where you need to do that I don't think it makes sense to complicate the API.

It sounds to me like you may have over-engineered your setup a bit. Generally a typical application should only have one registry, and one /metrics.

**Comment by decaz** [comment]
Yeah, it's possible and I have to call `some_service_registry.register(some_metric)` for each service, - the issue is that is very inconvenient.

Each service has only one registry, the problem is that they have common codebase so when some metric in codebase is registered it appears in some registry. I guess the single global `REGISTRY` is not the best place to have metrics because every service will expose all metrics including not related to him.

**Comment by brian-brazil** [comment]
As I said uses for this are extremely rare, and I suspect you should be using a single registry here. As this is already possible, I'm going to close this off.
