### ISSUE TITLE
How do I set the timestamp?

### ISSUE THREAD

**Issue by chen-ABC** [prometheus/client_python#588]
```
from flask import Response
import prometheus_client
import random
from prometheus_client import Gauge, Metric

registry = CollectorRegistry()
random_value = Gauge("random_value", "Random value of the request")


@talisman(force_https=False)
@app.route("/metric")
def metric():
    random_value.set(random.randint(0, 10))
    # how to set timestamp?
    return Response(prometheus_client.generate_latest(random_value),
                    mimetype="text/plain")

```
![企业微信截图_001ff61b-5be1-41b6-a75b-b008a7f5d4dd](https://user-images.githubusercontent.com/30097790/96212706-0a80c400-0faa-11eb-9069-2b40aa47662f.png)

**Comment by brian-brazil** [comment]
You don't, there's no valid use cases for having a timestamp with direct instrumentation like this.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by kmille** [comment]
Hey @brian-brazil 
> You don't, there's no valid use cases for having a timestamp with direct instrumentation like this.

I have a simple use case I could not get solved. I have a counter wich counts incoming requests. As label I specify which backend function gets called.

```python
counter.labels("page1").inc(1)
counter.labels("page2").inc(1)
```

I want to monitor whether my application is used by someone. In Grafana, I want see when the last request was (last request: 9s ago)

How can I solve this without having the timestamp of the last change? Thx!

**Comment by kmoppel-cognite** [comment]
> You don't, there's no valid use cases for having a timestamp with direct instrumentation like this.
> 
> It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

Hi @brian-brazil, I really can't see how you can say it's not a valid use case...especially if Prometheus specs it as an option. One just cannot foresee all possible use cases how this library is going to be used. I'm really missing this feature also for a use case where we collect metrics from a 3rd party cloud which has huge lag...and our infra also occasionally has collecting lag as needs to fetch around 200k metrics per second from hundreds of targets. So having an optional timestamp is an essential feature IMHO and exists for example in the official Go library. So in short any chance of re-opening / working on that? Please :)

**Comment by csmarchbanks** [comment]
Hello, your use case is supported by using a [custom collector](https://github.com/prometheus/client_python#custom-collectors) and the `add_metric` function which takes an optional `timestamp` argument.

**Comment by spaceone** [comment]
A workaround would be:
```python
class TimestampedGauge(Gauge):

    def __init__(self, *args, timestamp=None, **kwargs):
        self._timestamp = timestamp
        super().__init__(*args, **kwargs)

    def collect(self):
        metrics = super().collect()
        for metric in metrics:
            metric.samples = [ 
                type(sample)(sample.name, sample.labels, sample.value, self._timestamp, sample.exemplar)
                for sample in metric.samples
            ]
        return metrics

```

**Comment by z3rone** [comment]
@spaceone 
> A workaround would be:
> 
> ```python
> class TimestampedGauge(Gauge):
> 
>     def __init__(self, *args, timestamp=None, **kwargs):
>         self._timestamp = timestamp
>         super().__init__(*args, **kwargs)
> 
>     def collect(self):
>         metrics = super().collect()
>         for metric in metrics:
>             metric.samples = [ 
>                 type(sample)(sample.name, sample.labels, sample.value, self._timestamp, sample.exemplar)
>                 for sample in metric.samples
>             ]
>         return metrics
> ```

If I understand this correctly, I am supposed to create an instance of `TimestampedGauge` and set `._timestamp` each time I set a new value, right? If so, I see a problem because I cannot set the timestamp for individual labels. Is there a solution to this?

**Comment by darzanebor** [comment]
> @spaceone
> 
> > A workaround would be: ...
> 
> If I understand this correctly, I am supposed to create an instance of `TimestampedGauge` and set `._timestamp` each time I set a new value, right? If so, I see a problem because I cannot set the timestamp for individual labels. Is there a solution to this?

have you solved this?

**Comment by z3rone** [comment]
> have you solved this?

I tried to work myself through the source code to implement it myself (I don't think there is a workaround). However, I am no expert in python and the thread safety stuff got me confused enough I did not persue it further.

If your application is simple, the best way might be to write your own little webserver to export your metrices. It is just HTTP-based after all.

**Comment by darzanebor** [comment]
> @spaceone
> 
> > A workaround would be: ...
> 
> If I understand this correctly, I am supposed to create an instance of `TimestampedGauge` and set `._timestamp` each time I set a new value, right? If so, I see a problem because I cannot set the timestamp for individual labels. Is there a solution to this?

have you solved this? you can use metric.labels(*labelvalues)._timestamp

**Comment by z3rone** [comment]
> have you solved this? you can use metric.labels(*labelvalues)._timestamp

Does not work unfortunately. I will attach a minimal example I tried which just exports the metric without timestamp:

    lowbattery{source="s1",usage="u1"} 123.0
[minimal.py.txt](https://github.com/prometheus/client_python/files/11599847/minimal.py.txt)

**Comment by darzanebor** [comment]
```
from prometheus_client import start_http_server, Gauge, Counter
import time

class TimestampedGauge(Gauge):

    def __init__(self, *args, timestamp=None, **kwargs):
        self._timestamp = timestamp
        super().__init__(*args, **kwargs)

    def collect(self):
        metrics = super().collect()
        for metric in metrics:
            metric.samples = [ 
                type(sample)(sample.name, sample.labels, sample.value, self._timestamp, sample.exemplar)
                for sample in metric.samples
            ]
        return metrics


lowbat = TimestampedGauge("lowbattery", "lowbattery", ["usage","source"])
labels = {"usage": "u1", "source": "s1"}

if __name__ == '__main__':
    # Start the Prometheus exporter server on port 8000
    start_http_server(8000)
    while True:
        lowbat.labels(*labels).set(123)
        lowbat.labels(*labels)._timestamp = int(time.time())
        print(lowbat.labels(*labels)._timestamp)
        time.sleep(1)
```
just execute

**Comment by z3rone** [comment]
> just execute

sure that works because you are setting the timestamp for the entire gauge. However, as soon as you have metrics with different labels for the same gauge they will always have the same timestamp, even if you set it differently in `lowbat.labels(**labels)._timestamp = ...`:

    from prometheus_client import start_http_server, Gauge, Counter
    import time

    class TimestampedGauge(Gauge):

        def __init__(self, *args, timestamp=None, **kwargs):
            self._timestamp = timestamp
            super().__init__(*args, **kwargs)

        def collect(self):
            metrics = super().collect()
            for metric in metrics:
                metric.samples = [
                    type(sample)(sample.name, sample.labels, sample.value, self._timestamp, sample.exemplar)
                    for sample in metric.samples
                ]
            return metrics


    lowbat = TimestampedGauge("lowbattery", "lowbattery", ["usage","source"], multiprocess_mode = "max")
    labels = {"usage": "u1", "source": "s1"}
    labels2 = {"usage": "u2", "source": "s2"}

    if __name__ == '__main__':
        # Start the Prometheus exporter server on port 8000
        start_http_server(8000)
        while True:
            lowbat.labels(**labels).set(123)
            lowbat.labels(**labels)._timestamp = time.time()
            lowbat.labels(**labels2).set(456)
            lowbat.labels(**labels2)._timestamp = time.time() + 10
            print(lowbat.labels(**labels)._timestamp)
            lowbat._timestamp = time.time()
            time.sleep(1)

In fact, it does not matter what you set in `lowbat.labels(**labels)._timestamp = ...` because the only thing that has an effect here is `lowbat._timestamp = time.time()` which sets the timestamp for *all* metrics in the gauge.

Output:

    lowbattery{source="s1",usage="u1"} 123.0 1685476916370
    lowbattery{source="s2",usage="u2"} 456.0 1685476916370

Just fyi, I write `**labels` instead of `*labels` to have the key value pairs in my labels not just the keys.

**Comment by darzanebor** [comment]
and what do you want to achieve, I really don't understand the main goal

**Comment by z3rone** [comment]
Okay let me create a setting: imagine some sensor nodes reporting a temperature to a central master. This master runs an exporter, exporting the metric `temperature` which hast a label `nodeID`. Let's assume nodes might lose connection to the master. If I am exporting the temperature without a timestamp Prometheus wouldn't know how old a measurement actually is. As measurements will come in asynchronously and single nodes may fail independently, I also cannot set a global timestamp for all sensor nodes to the same timestamp.

Is this relatable?

**Comment by darzanebor** [comment]
And for what purpose you need to expose this metric to prometheus, just delete it from registry of exporter on the basis of labels, for exampl:
```
async def metrics_cleanup():
    global metrics_array
    while True:
      for metric in metrics_array:
        for value, name  in list(metric._metrics.items()):
            labelvalues = list(value)
            if ((int(time.time()) - 60*90) > metric.labels(*labelvalues)._timestamp):
              metric.remove(*labelvalues)
              logger.info("Removing from metrics %s", value)
      await asyncio.sleep(30)

```

**Comment by z3rone** [comment]
I could do that but then I would have to decide on a timeout after which I consider a node dead. During that timeout I would not know if the value is still actively received until the node is declared dead. This would incentivise me to choose a short timeout but then I have to be cautious that my Prometheus scraping interval is also short enough to not miss single values before the node gets removed. If you also consider a setting where the connection between exporter and Prometheus is unreliable, actively removing node metics will very likely result in lost data.

Look, I do not want to argue that there might be dirty way to hack together this behavior. I just want to make the point that individual timestamps would be handy. considering that this feature is already provided by the exporter format definition leads me to believe that it would make much sense to implement it and I think you can't really argue that there are no use cases for it

**Comment by spaceone** [comment]
FYI: setting a timestamp in textfiles for the prometheus node exporter causes the node exporter to not work anymore: 
https://github.com/prometheus/node_exporter/issues/1284

I don't know the reasons yet. At least the fetched data is not accurate anymore or does the prometheus node exporter uses the mtime of the `.prom` file and removed the `.prom` file after using it's data?

**Comment by chriskhanhtran-verisk** [comment]
> > just execute
> 
> sure that works because you are setting the timestamp for the entire gauge. However, as soon as you have metrics with different labels for the same gauge they will always have the same timestamp, even if you set it differently in `lowbat.labels(**labels)._timestamp = ...`:
> 
> ```
> from prometheus_client import start_http_server, Gauge, Counter
> import time
> 
> class TimestampedGauge(Gauge):
> 
>     def __init__(self, *args, timestamp=None, **kwargs):
>         self._timestamp = timestamp
>         super().__init__(*args, **kwargs)
> 
>     def collect(self):
>         metrics = super().collect()
>         for metric in metrics:
>             metric.samples = [
>                 type(sample)(sample.name, sample.labels, sample.value, self._timestamp, sample.exemplar)
>                 for sample in metric.samples
>             ]
>         return metrics
> 
> 
> lowbat = TimestampedGauge("lowbattery", "lowbattery", ["usage","source"], multiprocess_mode = "max")
> labels = {"usage": "u1", "source": "s1"}
> labels2 = {"usage": "u2", "source": "s2"}
> 
> if __name__ == '__main__':
>     # Start the Prometheus exporter server on port 8000
>     start_http_server(8000)
>     while True:
>         lowbat.labels(**labels).set(123)
>         lowbat.labels(**labels)._timestamp = time.time()
>         lowbat.labels(**labels2).set(456)
>         lowbat.labels(**labels2)._timestamp = time.time() + 10
>         print(lowbat.labels(**labels)._timestamp)
>         lowbat._timestamp = time.time()
>         time.sleep(1)
> ```
> 
> In fact, it does not matter what you set in `lowbat.labels(**labels)._timestamp = ...` because the only thing that has an effect here is `lowbat._timestamp = time.time()` which sets the timestamp for _all_ metrics in the gauge.
> 
> Output:
> 
> ```
> lowbattery{source="s1",usage="u1"} 123.0 1685476916370
> lowbattery{source="s2",usage="u2"} 456.0 1685476916370
> ```
> 
> Just fyi, I write `**labels` instead of `*labels` to have the key value pairs in my labels not just the keys.

I modified the code a bit to save the timestamp in the labels, and when collecting the metrics, `collect` pops the timestamp out of labels and add it to the sample. By doing this, each sample has a unique timestamp. Is that what you want?

```
from prometheus_client import start_http_server, Gauge
import time


class TimestampedGauge(Gauge):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    def collect(self):
        metrics = super().collect()
        for metric in metrics:
            samples = []
            for sample in metric.samples:
                timestamp = sample.labels.pop("timestamp", None)
                sample_with_timestamp = type(sample)(sample.name, sample.labels,
                                                     sample.value, timestamp, sample.exemplar)
                samples.append(sample_with_timestamp)
            metric.samples = samples
        return metrics


def set_value_with_timestamp(metric, labels, value, timestamp):
    labels["timestamp"] = timestamp
    metric.labels(**labels).set(value)


lowbat = TimestampedGauge("lowbattery", "lowbattery", ["usage", "source", "timestamp"], multiprocess_mode="max")
labels1 = {"usage": "u1", "source": "s1"}
labels2 = {"usage": "u2", "source": "s2"}


if __name__ == '__main__':
    # Start the Prometheus exporter server on port 8000
    start_http_server(8000)
    while True:
        set_value_with_timestamp(lowbat, labels1, 111, time.time())
        time.sleep(1)

        set_value_with_timestamp(lowbat, labels2, 222, time.time())
        time.sleep(1)
```

**Comment by chriskhanhtran** [comment]
> > just execute
> 
> sure that works because you are setting the timestamp for the entire gauge. However, as soon as you have metrics with different labels for the same gauge they will always have the same timestamp, even if you set it differently in `lowbat.labels(**labels)._timestamp = ...`:
> 
> ```
> from prometheus_client import start_http_server, Gauge, Counter
> import time
> 
> class TimestampedGauge(Gauge):
> 
>     def __init__(self, *args, timestamp=None, **kwargs):
>         self._timestamp = timestamp
>         super().__init__(*args, **kwargs)
> 
>     def collect(self):
>         metrics = super().collect()
>         for metric in metrics:
>             metric.samples = [
>                 type(sample)(sample.name, sample.labels, sample.value, self._timestamp, sample.exemplar)
>                 for sample in metric.samples
>             ]
>         return metrics
> 
> 
> lowbat = TimestampedGauge("lowbattery", "lowbattery", ["usage","source"], multiprocess_mode = "max")
> labels = {"usage": "u1", "source": "s1"}
> labels2 = {"usage": "u2", "source": "s2"}
> 
> if __name__ == '__main__':
>     # Start the Prometheus exporter server on port 8000
>     start_http_server(8000)
>     while True:
>         lowbat.labels(**labels).set(123)
>         lowbat.labels(**labels)._timestamp = time.time()
>         lowbat.labels(**labels2).set(456)
>         lowbat.labels(**labels2)._timestamp = time.time() + 10
>         print(lowbat.labels(**labels)._timestamp)
>         lowbat._timestamp = time.time()
>         time.sleep(1)
> ```
> 
> In fact, it does not matter what you set in `lowbat.labels(**labels)._timestamp = ...` because the only thing that has an effect here is `lowbat._timestamp = time.time()` which sets the timestamp for _all_ metrics in the gauge.
> 
> Output:
> 
> ```
> lowbattery{source="s1",usage="u1"} 123.0 1685476916370
> lowbattery{source="s2",usage="u2"} 456.0 1685476916370
> ```
> 
> Just fyi, I write `**labels` instead of `*labels` to have the key value pairs in my labels not just the keys.

I modified the code a bit to save the timestamp in the labels, and when collecting the metrics, `collect` pops the timestamp out of labels and add it to the sample. By doing this, each sample has a unique timestamp. Is that what you want?

```
from prometheus_client import start_http_server, Gauge
import time


class TimestampedGauge(Gauge):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    def collect(self):
        metrics = super().collect()
        for metric in metrics:
            samples = []
            for sample in metric.samples:
                timestamp = sample.labels.pop("timestamp", None)
                sample_with_timestamp = type(sample)(sample.name, sample.labels,
                                                     sample.value, timestamp, sample.exemplar)
                samples.append(sample_with_timestamp)
            metric.samples = samples
        return metrics


def set_value_with_timestamp(metric, labels, value, timestamp):
    labels["timestamp"] = timestamp
    metric.labels(**labels).set(value)


lowbat = TimestampedGauge("lowbattery", "lowbattery", ["usage", "source", "timestamp"], multiprocess_mode="max")
labels1 = {"usage": "u1", "source": "s1"}
labels2 = {"usage": "u2", "source": "s2"}


if __name__ == '__main__':
    # Start the Prometheus exporter server on port 8000
    start_http_server(8000)
    while True:
        set_value_with_timestamp(lowbat, labels1, 111, time.time())
        time.sleep(1)

        set_value_with_timestamp(lowbat, labels2, 222, time.time())
        time.sleep(1)
```

**Comment by raybellis** [comment]
> Hello, your use case is supported by using a [custom collector](https://github.com/prometheus/client_python#custom-collectors) and the `add_metric` function which takes an optional `timestamp` argument.

NB: in the current code this is the _fourth_ parameter for a custom collector's `add_metric`, following the optional `created` argument.
