### ISSUE TITLE
How can I set timestamp to metrics?

### ISSUE THREAD

**Issue by dnutiu** [prometheus/client_python#594]
Hello,

I'd like to set timestamp on my metrics but the current readme doesn't cover anything related to it. 

How may I accomplish that? 

---

I want to be able to to set the timestamp, just like in the [exposition format](https://prometheus.io/docs/instrumenting/exposition_formats/):

```
metric_name [
  "{" label_name "=" `"` label_value `"` { "," label_name "=" `"` label_value `"` } [ "," ] "}"
] value [ timestamp ]
```

* The timestamp is an int64 (milliseconds since epoch, i.e. 1970-01-01 00:00:00 UTC, excluding leap seconds), represented as required by Go's ParseInt() function.

Example: 

```
import datetime
from prometheus_client import Gauge
g = Gauge('my_inprogress_requests', 'Description of gauge')
g.set(4.2, int(datetime.datetime.utcnow().timestamp()))   # Set to a given value with timestamp
```

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by jpuskar** [comment]
This could have also been considered a request for a documentation update.

**Comment by spaceone** [comment]
An answer is here: https://github.com/prometheus/client_python/issues/588#issuecomment-1054724554

**Comment by LinTechSo** [comment]
i have an issue with this 
```
    gauge_value.labels(label).set(value, int(datetime.datetime.utcnow().timestamp()))
TypeError: Gauge.set() takes 2 positional arguments but 3 were given
```

**Comment by raybellis** [comment]
The answer given doesn't work - it results in a bunch of `_created` results being added instead of the timestamp appearing (as documented) after the value in each result.

Setting the `PROMETHEUS_DISABLE_CREATED_SERIES` environment variable doesn't appear to change this.

**Comment by dasl-** [comment]
I wanted to expand on the answer given here: https://github.com/prometheus/client_python/issues/588#issuecomment-1054724554. I eventually got timestamped metrics working, but it took a few steps. To associate a custom timestamp with a Prometheus metric:

1. Write a [custom collector](https://prometheus.github.io/client_python/collector/custom/) - you can't use the built-in [`Gauge`](https://prometheus.github.io/client_python/instrumenting/gauge/) class in the Python client.
1. Write a [custom exporter](https://prometheus.io/docs/instrumenting/writing_exporters/). This is a web server that exposes the timestamped metrics in the `*.prom` file such that Prometheus can scrape them.
1. Update your Prometheus config scrape targets with the address of the new exporter.
1. Update your Prometheus config to set [`out_of_order_time_window`](https://prometheus.io/docs/prometheus/2.53/configuration/configuration/#tsdb).

See my [write up](https://dasl.cc/2024/07/07/setting-custom-timestamps-for-prometheus-metrics/) for more details on the whole process.

**Comment by shazic** [comment]
> I wanted to expand on the answer given here: [#588 (comment)](https://github.com/prometheus/client_python/issues/588#issuecomment-1054724554). I eventually got timestamped metrics working, but it took a few steps. To associate a custom timestamp with a Prometheus metric:
> 
>     1. Write a [custom collector](https://prometheus.github.io/client_python/collector/custom/) - you can't use the built-in [`Gauge`](https://prometheus.github.io/client_python/instrumenting/gauge/) class in the Python client.
> 
>     2. Write a [custom exporter](https://prometheus.io/docs/instrumenting/writing_exporters/). This is a web server that exposes the timestamped metrics in the `*.prom` file such that Prometheus can scrape them. The built-in [textfile collector](https://github.com/prometheus/node_exporter?tab=readme-ov-file#textfile-collector) does not support timestamped metrics.
> 
>     3. Update your Prometheus config scrape targets with the address of the new exporter.
> 
>     4. Update your Prometheus config to set [`out_of_order_time_window`](https://prometheus.io/docs/prometheus/2.53/configuration/configuration/#tsdb).
> 
> 
> See my [write up](https://dasl.cc/2024/07/07/setting-custom-timestamps-for-prometheus-metrics/) for more details on the whole process.

Great article @dasl- it helped a lot. Thanks.
