### ISSUE TITLE
docker-compose 部署报错【docker-compose_aliyun-exporter_1 exited with code 1】

### ISSUE THREAD

**Issue by starsky9527** [prometheus/client_python#595]
大佬好：
　　请教个问题，就是在使用 docker-compose 部署时一直报错【docker-compose_aliyun-exporter_1 exited with code 1】，这个是什么情况？

aliyun-exporter_1   | Traceback (most recent call last):
aliyun-exporter_1   |   File "/usr/local/bin/aliyun-exporter", line 11, in <module>
aliyun-exporter_1   |     load_entry_point('aliyun-exporter', 'console_scripts', 'aliyun-exporter')()
aliyun-exporter_1   |   File "/usr/src/app/aliyun_exporter/__init__.py", line 39, in main
aliyun-exporter_1   |     REGISTRY.register(collector)
aliyun-exporter_1   |   File "/usr/local/lib/python3.7/site-packages/prometheus_client/registry.py", line 24, in register
aliyun-exporter_1   |     names = self._get_names(collector)
aliyun-exporter_1   |   File "/usr/local/lib/python3.7/site-packages/prometheus_client/registry.py", line 65, in _get_names
aliyun-exporter_1   |     for suffix in type_suffixes.get(metric.type, ['']):
aliyun-exporter_1   | AttributeError: 'NoneType' object has no attribute 'type'
docker-compose_aliyun-exporter_1 exited with code 1

环境信息：
Linux 3.10.0-1062.9.1.el7.x86_64 #1 SMP Fri Dec 6 15:49:49 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
[root@~]# docker-compose version
docker-compose version 1.25.4, build 8d51620a
docker-py version: 4.1.0
CPython version: 3.7.5
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by starsky9527** [comment]
不好意思，搞串了，不是这个项目的问题
