### ISSUE TITLE
How to query a pushgateway for metrics?

### ISSUE THREAD

**Issue by peter-toft-greve** [prometheus/client_python#601]
I have a case where I probably have to push say 200 metrics from Python to a pushgateway->prometheus->grafana system - it rocks, 
However the 200 metrics might later be reduced to 170 metrics, where at that point I need to query the pushgateway for the obtained metrics - and delete the 30 ones that we did not want any more. They day after it might be 10 that I need to remove. And add a few others.
I can manually go to the pushgateway and press "Delete Group" at http://localhost:9091/# - it works, but I really like to
* automate
* handling done from Python

Anyone who has examples for the following - preferably within Python
* Obtain a Python list or dict of metrics -> "my_metrics"
* Query the pushgateway for the known metrics -> "pg_metrics"
* Traverse the "pg_metrics" and delete the metrics that are not in "my_metrics"

There are discussions on something similar e.g. in 
https://www.metricfire.com/blog/prometheus-pushgateways-everything-you-need-to-know/
https://github.com/prometheus/pushgateway/issues/77

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by peter-toft-greve** [comment]
Thanx @brian-brazil - I will

**Comment by peter-toft-greve** [comment]
Moved to https://groups.google.com/g/prometheus-users/c/cfkCzxjXO8Q
