### ISSUE TITLE
Method to list registered collectors

### ISSUE THREAD

**Issue by andy-maier** [prometheus/client_python#603]
I am trying to unregister the pre-registered Platform and GC collectors, and found issue #414 discussing ways to do that. I would like to use the dynamic approach @luto posted in https://github.com/prometheus/client_python/issues/414#issuecomment-651290540, but it uses a private attribute for listing the registered collectors.

Looking at class `CollectorRegistry`, it can register and unregister collectors but it lacks a method to list the registered collectors, names and does not provide publicly available lookup between collectors and names.

I suggest to add:
* a method to iterate through the registered collectors
* a method to iterate through the registered names
* a method to return the collector given a name
* a method to return the list of names given a collector

I can provide a PR for the functionality, if you are generally open to add this.

**Comment by brian-brazil** [comment]
Why do you want this?

The registry should be a black box, you should only care about collectors which your code has registered - which you already know about a-priori. The only output of the registry is to collect it, you shouldn't care what's inside it.

**Comment by NightTsarina** [comment]
I have encountered this too.. I agree that for a library or plugin the registry should be a black box, but not for the main application that might have reasons to unregister a collector, and the lack of an API forces me to do ugly hacks...

**Comment by luto** [comment]
> Why do you want this?

@brian-brazil because I'd like to control what exactly is exported on the HTTP endpoint. Specifically, I'd like to only expose my own metrics there, omitting any default cpython ones.

**Comment by brian-brazil** [comment]
> the main application that might have reasons to unregister a collector, and the lack of an API forces me to do ugly hacks...

If an application doesn't want one of its own collectors registered, it should not register it in the first place. No piece of code should be touching another's metrics.

> Specifically, I'd like to only expose my own metrics there, omitting any default cpython ones.

If you're writing a multi-target exporter then you can use a custom registry for this. For practically all other cases the cpython metrics should always be present.


This is not a feature that this client library will be offering, as I said the registry is a black box.

**Comment by roidelapluie** [comment]
Hello,

This behaviour is the same as in the client_golang, and I think it is reasonable. What we are seeing in the client_golang, is that many people simply explicitly pass a registry. That way you can only have your own metrics if you really like so, and you can 'control your http endpoint'.

So, it seems more like a usage question than a feature request. If you need more help, feel free to hop on our mailing lists and we will be happy to help you!

**Comment by NightTsarina** [comment]
> This behaviour is the same as in the client_golang, and I think it is reasonable. What we are seeing in the client_golang, is that many people simply explicitly pass a registry. That way you can only have your own metrics if you really like so, and you can 'control your http endpoint'.

Except that if you are using the multiprocess module, you can't use custom registries.

**Comment by brian-brazil** [comment]
If you're using multiprocess mode, this wouldn't help you anyway as you can't unregister in multiprocess mode.

This is offtopic, locking. If you've support questions, as @roidelapluie said please the mailing list.
