### ISSUE TITLE
Incorrect example for textfile collector

### ISSUE THREAD

**Issue by DaniruKun** [prometheus/client_python#613]
In the example for the textfile collector the following example is provided:

https://github.com/prometheus/client_python/tree/a5f0e25273b9007d2ab72480779a51378a86d83a#node-exporter-textfile-collector

```python
from prometheus_client import CollectorRegistry, Gauge, write_to_textfile

registry = CollectorRegistry()
g = Gauge('raid_status', '1 if raid array is okay', registry=registry)
g.set(1)
write_to_textfile('/configured/textfile/path/raid.prom', registry)
```

However, this example will not work, because the `Gauge` collector won't be registered in the registry without calling

```python
registry.register(g)
```

If the example is run, it will simply create an empty metrics file at the given path.

**Comment by brian-brazil** [comment]
The gauge is registered here, that's what the registry parameter is for. I have tested this to confirm a bug hasn't slipped in.
