### ISSUE TITLE
Cannot initialize Gauge label values with exception

### ISSUE THREAD

**Issue by DaniruKun** [prometheus/client_python#614]
When trying to initialise label values for a `Gauge` like so (following examples in Readme):

```python
from prometheus_client import Gauge

sample_gauge = Gauge(name='example', documentation='Some doc', labelnames=['one', 'two', 'three'])

sample_gauge.labels(["1", "2", "3"])
sample_gauge.set(1)
```

Running this snippet will throw the following exception in any case:

```
Traceback (most recent call last):
  File "*/sample.py", line 5, in <module>
    sample_gauge.labels(["1", "2", "3"])
  File "*/Library/Caches/pypoetry/virtualenvs/checkm8-MuaFxrMT-py3.9/lib/python3.9/site-packages/prometheus_client/metrics.py", line 164, in labels
    raise ValueError('Incorrect label count')
ValueError: Incorrect label count
```

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by DaniruKun** [comment]
@brian-brazil then why is this not mentioned anywhere, and people are allowed to even open Github Issues in the first place? For an essential library used by thousands the documentation and the attitude of maintainers is a joke. If you don't provide a proper answer like a workaround or a patch I am forking.

**Comment by brian-brazil** [comment]
What you're asking is a usage question that is already covered by documentation, and accordingly the mailing list is the best place for that. Github issues are for bugs and feature requests, which this is not.

**Comment by DaniruKun** [comment]
What usage question? This is clearly a bug, following the documentation. I am forking.

**Comment by gurmitsa** [comment]
@DaniruKun - I understand this issue is closed by I did struggle with this a little today and then came across this issue and was able to make it work.
https://github.com/prometheus/client_python/issues/38

My code sample:
```
g = Gauge(name='my_sample_metric', documentation='Description of gauge', labelnames=["label1", "label2"])
g.labels(label1="foo", label2="bar").set(random.randint(0, 500))
```

**Comment by csmarchbanks** [comment]
You can use line continuation if you want to split them:
```
(
    g.labels(label1="foo", label2="bar")
    .set(random.randint(0, 500))
)
```

or use an intermediate variable if it would help with reuse:
```
foo_bar = g.labels(label1="foo", label2="bar")
foo_bar.set(random.randint(0, 500))
```

What you cannot do is all `g.set()` on a gauge with labels.
