### ISSUE TITLE
Duplicated timeseries in CollectorRegistry

### ISSUE THREAD

**Issue by sachaventura** [prometheus/client_python#626]
Hi there,

I know this is not the first time someone is having the `Duplicated timeseries in CollectorRegistry` error, but I have been struggling to get rid of it. I have explored all the existing solutions without success.

So our set-up is:
- `flask` 1.0.2
- `gunicorn` 20.0.4 with 2 workers, 3 threads
- `prometheus-client` 0.9.0 
- kubernetes

We define the `prometheus_multiproc_dir` in our Dockerfile :
```
ENV prometheus_multiproc_dir /tmp/.prometheus_multiproc
RUN mkdir $prometheus_multiproc_dir
```
We run the server on a separate port like this:
```python
from prometheus_client import multiprocess, start_http_server, REGISTRY
metrics_registry = REGISTRY
if os.getenv("prometheus_multiproc_dir"):
    collector = multiprocess.MultiProcessCollector(metrics_registry)
start_http_server(int(METRICS_PORT))
```

in routes.py:
```python
REQUEST_METRIC = Summary(
    name='api_request_seconds',
    documentation='The total request duration for hits to a given endpoint',
    registry=metrics_registry,
    labelnames=('type', 'granularity')
)
@app.route('/foobar', methods=['GET'])
def foobar():
    with REQUEST_METRIC.labels(type='foobar', granularity='').time():
        pass # do something
```

Any pointers welcome.
Thank you.

**Comment by csmarchbanks** [comment]
Hello,

The [docs](https://github.com/prometheus/client_python#multiprocess-mode-gunicorn) specify that a new registry must be created, but you appear to be using the default REGISTRY? Would you try creating a new registry with `CollectorRegistry()`?

You can also ask on the [Prometheus Users Mailing List](https://groups.google.com/u/1/g/prometheus-users) which will allow more people to answer and learn.

**Comment by sachaventura** [comment]
Thank you @csmarchbanks, instantiating a new CollectorRegistry did the trick!
