### ISSUE TITLE
`instance_ip_grouping_key` does not work on macOS

### ISSUE THREAD

**Issue by darkclouder** [prometheus/client_python#629]
macOS 11.1
Python 3.8.5
prometheus-client 0.9.0

To reproduce:
```python
from prometheus_client import instance_ip_grouping_key

instance_ip_grouping_key()
```

What happens?
```
metrics.py:10: in <module>
    INSTANCE = instance_ip_grouping_key()
lib/python3.8/site-packages/prometheus_client/exposition.py:379: in instance_ip_grouping_key
    s.connect(('localhost', 0))
E   OSError: [Errno 49] Can't assign requested address
```

**Comment by csmarchbanks** [comment]
Thank you for your report, it is certainly an issue, and there is even a test that is ignored on macOS: https://github.com/prometheus/client_python/blob/master/tests/test_exposition.py#L379

I don't have a macOS environment, but would be happy to review a PR to enable macOS.

**Comment by AceFire6** [comment]
@csmarchbanks Does this look like an acceptable solution?

It's adapted from this StackOverflow answer: https://stackoverflow.com/a/28950776

```python
def instance_ip_grouping_key():
    """Grouping key with instance set to the IP Address of this host."""
    with closing(socket.socket(socket.AF_INET, socket.SOCK_DGRAM)) as s:
        s.connect(('10.255.255.255', 1))
        return {'instance': s.getsockname()[0]}
```

It works on my M1 MacbookPro:

```python
>>> from contextlib import closing
>>> 
>>> def instance_ip_grouping_key():
...     """Grouping key with instance set to the IP Address of this host."""
...     with closing(socket.socket(socket.AF_INET, socket.SOCK_DGRAM)) as s:
...         s.connect(('10.255.255.255', 1))
...         return {'instance': s.getsockname()[0]}
... 
>>> instance_ip_grouping_key()
{'instance': '192.168.0.189'}

```

<img width="665" alt="Screenshot 2021-08-17 at 18 42 21" src="https://user-images.githubusercontent.com/4126778/129766448-47e28c1c-bec7-4fb7-944b-1078ba9d3a31.png">

**Comment by FMorgan-111** [comment]
RepoPilot v2 could not complete an automatic fix.

Reason: Same patch produced the same failure twice.

Relevant files:
- prometheus_client/exposition.py: seeded from gold changed files (offline eval)
- tests/test_exposition.py: seeded from gold changed files (offline eval)

Attempts:
Attempt 1: success=False
File: unknown
Result: patch_apply_failed
Error:
Patch preflight check failed:
error: No valid patches in input (allow with "--allow-empty")


Attempt 2: success=False
File: prometheus_client/exposition.py
Result: {"command": "/home/morganbest/.repopilot/repos/prometheus-client_python-work-venv/bin/python -m pytest tests/test_exposition.py", "returncode": 1, "success": false}
Error:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/morganbest/.repopilot/repos/prometheus-client_python-work-venv/lib/python3.11/site-packages/pytest/__main__.py", line 9, in <module>
    raise SystemExit(_console_main())
                     ^^^^^^^^^^^^^^^
  File "/home/morganbest/.repopilot/repos/prometheus-client_python-work-venv/lib/python3.11/site-packages/_pytest/config/__init__.py", line 253, in _console_main
    code = _main(prog=_get_prog_name(sys.argv))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/morganbest/.repopilot/repos/prometheus-client_python-work-venv/lib/python3.11/site-packages/_pytest/config/__init__.py", line 223, in _main
    config = _prepareconfig(new_args, plugins, prog=prog)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/morganbest/.repopilot/repos/prometheus-client_python-work-venv/lib/python3.11/site-packages/_pytest/config/__init__.py", line 410, in _prepareconfig
    config: Config = pluginmanager.hook.pytest_cmdline_parse(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/morganbest/.repopilot/repos/prometheus-client_python-work-venv/lib/python3.11/site-packages/pluggy/_hooks.py", line 512, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ho

Attempt 3: success=False
File: unknown
Result: patch_apply_failed
Error:
Patch preflight check failed:
error: No valid patches in input (allow with "--allow-empty")


Token usage: 18335/80000
