### ISSUE TITLE
how can show the second metrics ONLY?

### ISSUE THREAD

**Issue by cleverchou** [prometheus/client_python#630]
firstly,I get the metrics"npkt{DIP="192.168.1.243"} 1.0 ” ,when Visit "127.0.0.1:/8000", Show "npkt{DIP="192.168.31.243"} 1.0 ”  

....after 30s...
then, I get the metrics"npkt{DIP="192.168.0.100"} 1.0 ” ,when Visit "127.0.0.1:/8000", Show "npkt{DIP="192.168.31.243"} 1.0 ”(this is first metric) and  "npkt{DIP="192.168.0.100"} 1.0 ”

how can show the second metrics ONLY?

**Comment by csmarchbanks** [comment]
Hello, you will have to unregister the metric with DIP="192.168.31.243" before adding the new metric. You can do that by calling `registry.unregister(metric)`. If this is happening every 30 seconds, you will create a significant amount of series churn in your Prometheus instance, and the series that are created would be very poorly compressed with only one or two samples.

**Comment by cleverchou** [comment]
Every 30 seconds, there are new samples, but the old samples alway show on the html, I want the new samples ONLY, because the old ones were  stord in Prometheus, how to call registry.unregister(metric)

my code:

start_http_server(80)
.....
npkt = Gauge(name='npkt', documentation='count of packets',labelnames=['SIP'])
while True : 
        ## code for generate new k.saddr and v.num
        ....
       npkt.labels(SIP=decimal_to_human(str(k.saddr)) ).set(v.num)

**Comment by csmarchbanks** [comment]
That is not a model that will lead to success with Prometheus. Prometheus works with timeseries, which means a single series should exist for a period of time (at least a few minutes, preferably hours). Lots of series with just one datapoint will cause a large amount of memory usage in Prometheus and not provide much value to you.
