### ISSUE TITLE
Metrics not collected from async server route

### ISSUE THREAD

**Issue by pkaramol** [prometheus/client_python#635]
I have an `aiohttp` based app and exposing / instrumenting a simple route as follows, trying go adhere to the [Three Step Demo ](https://github.com/prometheus/client_python#three-step-demo) of `README.md`:

```
@REQUEST_TIME.time()
@routes.get('/endpoint')
async def my_service(request):
    ws = web.WebSocketResponse()
    await ws.prepare(request)

    async for msg in ws:
       do_stuff()
    return ws
```

I am (successfully) hitting the endpoint with the following client:

```
from websocket import create_connection

ws = create_connection("ws://localhost:5000/my-endpoint")
data = prepare_data()
ws.send(full_data)
ws.close()
```

However the following metrics remain unchanged:

```
# HELP request_processing_seconds Time spent processing request
# TYPE request_processing_seconds summary
request_processing_seconds_count 0.0
request_processing_seconds_sum 0.0
# HELP request_processing_seconds_created Time spent processing request
# TYPE request_processing_seconds_created gauge
request_processing_seconds_created 1.6161408098226109e+09
```

**Comment by csmarchbanks** [comment]
Hello, I have been on vacation and have not had time to take a look at this yet, but did not want to leave this with no response. https://github.com/prometheus/client_python/issues/640 does indicate they have a working setup using aiohttp, so I am not sure if this is a library issue or usage issue.

**Comment by csmarchbanks** [comment]
I think this might be an ordering issue in your decorators, would you try:
```
@routes.get('/endpoint')
@REQUEST_TIME.time()
async def my_service(request):
    ...
```
The routes decorator needs to be the first decorator specified in the file, which causes it to be the outermost decorator. I think what is happening now is the function being registered route is not including the REQUEST_TIME.time() part of your decorator change.

**Comment by csmarchbanks** [comment]
Closing as I believe this is an issue with the order of decorators, if that is not the case I am happy to reopen.
