### ISSUE TITLE
Expose a get() method on metrics?

### ISSUE THREAD

**Issue by Cobertos** [prometheus/client_python#636]
For some metrics stored in Counters, I want to log the values as well to make debugging the logs easier.

Would be nice if metrics exposed a `.get()`, [similar to what it's already doing internally](https://github.com/prometheus/client_python/blob/af6bfd3403f1b65a1eabf07dae469294d40f4ed0/prometheus_client/metrics.py#L272). It would save me from having to create redundant variables just for logging

**Comment by csmarchbanks** [comment]
Hello, thank you for raising this issue! Currently getting the value of a metric is intentionally not exposed, there is a good comment as to the reasoning in https://github.com/prometheus/client_golang/issues/486#issuecomment-433345239.

One option to avoid redundant values would be to use `set_function` such as in the example from the readme:
```
d = Gauge('data_objects', 'Number of objects')
my_dict = {}
d.set_function(lambda: len(my_dict))
```
and then use the same variable for both logging and metrics.
