### ISSUE TITLE
The performance of the write_to_textfile function is very low, and use large memory

### ISSUE THREAD

**Issue by ll348900729** [prometheus/client_python#639]
# for example
make test metrics 
```
test_metrics = Gauge('test_metrics', 'metrics', ('a', 'b', 'c', ))
```
generate 1,000,000 metrics
```
for i in range(1000000):
    test_metrics.labels(i,i,i).set(1)
```
memory usage is 2.2g
run write_to_textfile function const 30s and Maximum memory usage 2.8Gb, but file size is 41M
cpu usage:
```
CPU times: user 28.7 s, sys: 1.07 s, total: 29.7 s
Wall time: 29.7 s
```

**Comment by csmarchbanks** [comment]
Hello, thank you for raising this issue!

I am certainly happy to add performance improvements, though generating 1,000,000 metrics per scrape target is not a normal use case of this library. For anyone looking into this issue in the future, on my machine at least a fair amount of the time is spent initializing the metrics, which is also where much of the memory usage comes from:
```
Initialized metrics in 7.9776 seconds, rss: 1285558272
Wrote to file in 5.3658 seconds, rss: 1302650880
python3 test.py  14.61s user 0.46s system 99% cpu 15.105 total
```

**Comment by csmarchbanks** [comment]
I am going to close this as performance seems reasonable for generating 1,000,000 metrics in a sane scrape interval. Happy to re-open if there are specific issues that need addressing for a use case however!
