### ISSUE TITLE
Which issues I can get using it under async context ?

### ISSUE THREAD

**Issue by remort** [prometheus/client_python#640]
This library stands that it doesn't support asyncio. I've just used it in a tiny aiohttp app with ~5 handlers collecting counters and rendering it as `generate_latest(self.request.app['metrics_registry'])` in async handler and see no issues. What I miss ?

Suppose that it could be a race condition updating same metric in in different async HTTP requests at the (almost) same time. And this metric will corrupt then. Am I right ?

**Comment by csmarchbanks** [comment]
The metrics in this library are protected by locks so you should be ok using them. I do not have much experience with asyncio however. You can also take a look at https://github.com/hynek/prometheus-async which provides some wrappers for use with asyncio and aiohttp.

**Comment by remort** [comment]
Used this library without any async wrappers in my asyncio app without any issues. Everything works fine. But I didn't use decorators, which obviously should support synchronous code only, and collect metrics adding string-or-two of code in every function call/handler I need. Seems to be enough for my needs by far. Thank you.

**Comment by csmarchbanks** [comment]
:+1: I am going to close this issue for now then. If there are issues that pop up feel free to open a specific issue to address them!
