### ISSUE TITLE
Exemplar support

### ISSUE THREAD

**Issue by darox** [prometheus/client_python#648]
Does this lib already support examplars?

**Comment by csmarchbanks** [comment]
https://github.com/prometheus/client_python/pull/669 adds support for exemplars when running in single process mode, multi process will need a bit more work.

**Comment by Xopherus** [comment]
Are there any plans to get exemplars working with multi-proc?

**Comment by csmarchbanks** [comment]
I have not had time to work on exemplars in multi-process mode but would like to support it. I would certainly be happy to review a contribution.
