### ISSUE TITLE
[Feature Request] Changelog

### ISSUE THREAD

**Issue by MartinThoma** [prometheus/client_python#652]
I'm currently updating dependencies. When I do that, I typically look in the changelog for "breaking change" or "deprecation" to see if I should expect issues (and where to expect them).

It would be amazing if you could add a changelog. Here are some ways other projects do it:

* [scipy release notes](https://docs.scipy.org/doc/scipy/reference/release.1.6.0.html#backwards-incompatible-changes)
* [Flask](https://flask.palletsprojects.com/en/1.1.x/changelog/)
* [Requests](https://github.com/psf/requests/blob/master/HISTORY.md)

**Comment by csmarchbanks** [comment]
Hello,

You can currently find the changelog with the release notes on the GitHub releases page: https://github.com/prometheus/client_python/releases. Would it also be helpful to add a CHANGELOG.md file to the repo like in other Prometheus project repos, or are the release notes there enough?

**Comment by MartinThoma** [comment]
Oh, nice! I haven't seen that.

It would be helpful to have that link in the README with the text "Changelog" or "Release notes".

Do I see it correctly that there were no breaking changes so far? None at all?

**Comment by csmarchbanks** [comment]
A link in the readme or something like that certainly seems reasonable to me, thank you for the suggestion.

So far the only breaking change is switching from lowercase to uppercase for the multiproc environment variable, we currently accept both so it hasn't broken anything yet. There are also some versions of Python we no longer support in the 2.x release cycle. Generally the library is quite stable and we do our best to not have breaking changes.

**Comment by MartinThoma** [comment]
Nice! Thank you :-) if you want I could make a tiny pr with the link 😁

**Comment by csmarchbanks** [comment]
Feel free, that would be great!
