### ISSUE TITLE
push_to_gateway custom handler help

### ISSUE THREAD

**Issue by todd-davenport** [prometheus/client_python#656]
Hi, I am trying to write a custom handler to support client certificate authorization. I'm having some trouble understanding how custom handlers work and I was wondering if there are any examples I could reference.

This seems like a difficult thing to do with urllib and I can't seem to find any examples that don't use requests.

Any insight would be greatly appreciated.

**Comment by csmarchbanks** [comment]
Hello, you can see some examples for redirects and basic auth starting at https://github.com/prometheus/client_python/blob/master/prometheus_client/exposition.py#L317, if those are not enough, I recommend reaching out to the [prometheus-users](https://groups.google.com/forum/#!forum/prometheus-users) mailing list. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by todd-davenport** [comment]
Thank you @csmarchbanks. I appreciate your time.
