### ISSUE TITLE
prometheus_client with labels is not working

### ISSUE THREAD

**Issue by simplyrahul1** [prometheus/client_python#663]
Code ::

`
from prometheus_client import start_http_server, Gauge
import random
from random import randrange

##Latency_Time = Gauge('consumer_gauge_seconds', 'Time spent in consuming message')   #code works without label
Latency_Time = Gauge('consumer_gauge_seconds', 'Time spent in consuming message', labelnames=['partition'])

@Latency_Time.track_inprogress()
def latency_request(latency):
 ##Latency_Time.set(latency)                                 #code works without label
     Latency_Time.labels('partition', '1').set(latency). **# I know there is something wrong here.. I'm not able to figure out what !**

if __name__ == '__main__':
     start_http_server(17500)
     while True:
          latency_request(random.randrange(1900, 2150))
`

**Comment by csmarchbanks** [comment]
Hello,

Sorry that it took a couple of days to answer, but I provided an answer on the -users mailing list where we prefer to answer questions: https://groups.google.com/g/prometheus-users/c/6Orp-M80K2o. Thank you for reaching out to the mailing list!
