### ISSUE TITLE
Address already in use

### ISSUE THREAD

**Issue by BarryThrill** [prometheus/client_python#667]
Hello!

Im pretty new and hopefully its a newbie question. I have been trying to work with Prometheus and Python where I am trying to use multiple python instance to connect and "push" to promethetus. What I did was:

**sydsvenskan.py**
```
    import time
    
    import requests
    from prometheus_client import Counter, start_http_server
    
    REQUEST_COUNT = Counter(
        namespace="scraper",
        name="request_count",
        documentation="Count the total requests",
        labelnames=['http_status']
    )
    
    
    def monitor_feed():
        while True:
            with requests.get("https://sydsvenskan.se") as rep:
                print("Request made!")
                REQUEST_COUNT.labels(http_status=rep.status_code).inc()
    
            time.sleep(10)
    
    
    if __name__ == '__main__':
        start_http_server(8000)
        monitor_feed()
```

**BBC.py**
```
    import time
    
    import requests
    from prometheus_client import Counter
    
    REQUEST_COUNT = Counter(
        namespace="scraper",
        name="request_count",
        documentation="Count the total requests",
        labelnames=['http_status']
    )
    
    
    def monitor_feed():
        while True:
            with requests.get("https://bbc.com") as rep:
                print("Request made!")
                REQUEST_COUNT.labels(http_status=rep.status_code).inc()
    
            time.sleep(10)
    
    
    if __name__ == '__main__':
        start_http_server(8000)
        monitor_feed()
```

Whenever I run the first script it works fine but as soon as I am starting to run the second script it returns:

OSError: [Errno 98] Address already in use

What am I doing wrong?

**Comment by csmarchbanks** [comment]
Hello, it looks like both of your services are trying to start on port `8000`, you will need to change the port on one of those services if running on the same instance.

Also, note that Prometheus will pull metrics from your services, not push metrics from your application to Prometheus, unless you are using something such as the PushGateway.

**Comment by BarryThrill** [comment]
> Hello, it looks like both of your services are trying to start on port `8000`, you will need to change the port on one of those services if running on the same instance.
> 
> Also, note that Prometheus will pull metrics from your services, not push metrics from your application to Prometheus, unless you are using something such as the PushGateway.

Oh I see... so if I created each port for each file then that should be fine I guess? if I understood it correctly.

**Comment by csmarchbanks** [comment]
Yep, so use 8000 in one file and 8001 in the other (or something like that).

I am going to close this issue as I don't think there is anything wrong with this library.
