### ISSUE TITLE
Add ability to turn off _created metrics

### ISSUE THREAD

**Issue by csmarchbanks** [prometheus/client_python#672]
As per the [June 24th 2021 Prometheus Dev Summit](https://docs.google.com/document/d/11LC3wJcVk00l8w5P3oLQ-m3Y37iom6INAMEu2ZAGIIE/edit#heading=h.omrxayfajpwh) there is consensus that all first party clients should have a parameter to turn off _created metrics.

**Comment by baryluk** [comment]
Any update on this?

`_created` metrics are not very useful (I personally never used them), and add to resource consumption through the monitoring stack.

Thanks.

**Comment by csmarchbanks** [comment]
Hello, no progress has been made but I would be happy to accept a contribution to provide a flag.

**Comment by csmarchbanks** [comment]
Did you set `PROMETHEUS_DISABLE_CREATED_SERIES=True` as well? This library tries to match as many SHOULD clauses as possible in OpenMetrics so the created series are on by default.

**Comment by nidemidovich** [comment]
Yes, I did. I even tried set the variable before import `prometheus_client` as mentioned in #710

**Comment by nidemidovich** [comment]
Any updates on this? @csmarchbanks Sorry for mentioning

**Comment by csmarchbanks** [comment]
I haven't had time yet, I am hoping to try to reproduce today, but it might have to wait until next week.

**Comment by baryluk** [comment]
I was using this flag for some time, and sometimes it does not work, even if I set it in-process before importing `prometheus_client`, it does not work as expected. I could envvar set it on a process startup, but it just clutters startup scripts, or hand started stuff. I do not have anything that imports it transitively before my import.

So, I hacked and just set internal variable:


```python3
#!/usr/bin/env python3

import dataclasses
import os
import sys
import time
from typing import Optional

os.environ["PROMETHEUS_DISABLE_CREATED_SERIES"] = "True"

import prometheus_client

prometheus_client.metrics._use_created = False

...
```

**Comment by csmarchbanks** [comment]
Yeah, we need to make that variable settable in code. See https://github.com/prometheus/client_python/issues/933.

**Comment by nidemidovich** [comment]
I'll try @baryluk hack for now. But hope you figure out how to solve the issue in better way. M

ay be reopen the issue?

**Comment by csmarchbanks** [comment]
I spent a bit of time trying to reproduce this, and if I set the environment variable before running the script it seems to consistently work. My guess is that setting the environment variable isn't being propagated to child processes, similar to if you try to set PROMETHEUS_MULTIPROC_DIR inside of python. The readme calls this out in multiprocess mode, but maybe we should explicitly call it out for PROMETHEUS_DISABLE_CREATED_SERIES too?

Also, if you are using multi-process mode `_created` metrics are actually not created at all. Which made me realize you are specifying `registry=` when defining your metrics. This is not supported and can cause duplicate/wrong metrics to be exported. See the note in https://github.com/prometheus/client_python/#multiprocess-mode-eg-gunicorn about how registries cannot be used like normal.

I don't think this issue should be reopened, the work for disabling `_created` from code is already captured in the other issue.

**Comment by baryluk** [comment]
That is interesting, because I do not use child subprocesses. I do use some threading, but not subprocesses. And if I do use subprocesses, this is to run non-python auxilary programs (`subprocess.run/Popen`).

Not sure why setting env before program start, and modying it in the main thread, before starting any other sub-processes, should have any differences. Maybe `os.environ["..."]` does not C environment, but just some internal dict?
