### ISSUE TITLE
No trivial way to change namespace of builtin metric registry

### ISSUE THREAD

**Issue by pavel-lexyr** [prometheus/client_python#673]
Connecting multiple clients to a common Prometheus server may create multiple Python metrics with the same name. It would be nice if there was a trivial way to set a namespace for all exported metrics without delving into the Registry classes.

**Comment by csmarchbanks** [comment]
Hello,

If I understand your comment correctly, usually differentiation is done with labels during service discovery on the Prometheus server. For example, having different instance and job labels. That way you can easily compare and aggregate metrics across all of your python services by having the same metric name, but different label values.

Can you describe your use case a bit more if it does not fit into the above case?

**Comment by pavel-lexyr** [comment]
Our use case is running multiple different Python scripts in a single Prometheus dashboard. We would like to know which script is responsible for what. Metrics like `python_gc_objects_collected_total` and the similar we would not tell apart without any further information.

**Comment by csmarchbanks** [comment]
The best practice for determining where a metric came from is using service discovery. After being scraped the series will look like `python_gc_objects_collected_total{job="my-job", instance="xyz:1234"}` and you should be able to tell the scripts apart based on the job and instance labels. If sending to push-gateway you can specify `job="my-job"` as seen in the docs: https://github.com/prometheus/client_python#exporting-to-a-pushgateway.

I am going to close this issue as I do not want to implement a feature that does not encourage Prometheus best practices. If there are other use cases that are not possible with service discovery I am happy to reconsider.

**Comment by fandreuz** [comment]
Hi @csmarchbanks, I'm commenting here since I have a related issue. Is there a way to set a collection of labels to be used by built-in collectors?
