### ISSUE TITLE
Registering a metric after creating RestrictedRegistry with its name does not add the metric to RestrictedRegistry

### ISSUE THREAD

**Issue by pavel-lexyr** [prometheus/client_python#674]
The method `restricted_registry` works by filtering all metrics once at the time of its creation, as one can see from looking at the file `registry.py`.

If you register a metric after creating the restriction for it, it is not added to the restricted registry - while the docstring could be interpreted as claiming otherwise.

Solution 1: the class could be documented in a way that makes its behaviour explicit;
Solution 2: the class could be expanded to recollect metrics from its parent on every `collect()` call.

**Comment by csmarchbanks** [comment]
I agree, this could be confusing, though the "Intended usage" is hinting that it should be ephemeral to a scrape/output generation. Personally, I would lean slightly towards solution 2 as it is more intuitive and would not require reading the docstring.
