### ISSUE TITLE
Partial Labels

### ISSUE THREAD

**Issue by hynek** [prometheus/client_python#68]
Unless I’m missing something, it’s currently necessary to specify all labels at once.  It would be nice tho if I could do something like this:

```python
M = Counter("a counter", "counter that counts", ["id", "type"])
...
c = M.labels({"id": id})  # id is determined at runtime/initialization
...
c.labels({"type": "internal").inc()  # type is unclear until it happens
...
c.labels({"type": "external").inc()
```

Does that make sense?

**Comment by brian-brazil** [comment]
I think such an API would cause confusion as it's not clear whether a given `labels` use is complete.

I'd expect that you'd always know all the labels in play when incrementing, so this isn't going to buy you much. I'm also considering dropping the dict argument, in favour of kwargs.

**Comment by hynek** [comment]
Well, I do *know*, but if one of three labels is dynamic, it’s still pretty painful to always type them out every single time.  Copy and paste is error-prone and annoying.

And yes, `kwargs` would be great, because currently the “best” way I found to precompute labels is:

```python
    def request_time_for(self, type):
        return self._request_time.labels(*(self._labels + (type,)))
```

(can’t use mutable dicts for I’d have to copy them first…)

***

Anyhow, if you wanna keep the official client as minimal as possible I can stop opening bugs and just build my own convenience layer called “lighter” or something. :D 

I just found the current behavior highly discouraging for using labels, that’s all.

**Comment by brian-brazil** [comment]
Just thinking there the kwargs would help you as you could do
```python
c.labels(type="internal", **standard_labels).inc()
```

**Comment by hynek** [comment]
yeah, that’s what I meant by “would be great” :)

**Comment by raul1991** [comment]
I want to build dynamic variables with this client lib. I have the following code


```python
self.online_time_span = Gauge('online_time_span', 'How long someone has been online', ['value'])

self.online_time_span.labels('online_time').set(time_span)
```

In the above statement I need the labels to represent something like

> 'online_time_spent_<USERNAME_WHICH_UNIQUE_COMES_FROM_API>'
> 
> Examples:
> 
> 'online_time_spent_John'
> 'online_time_spent_Maria'
> 'online_time_spent_Foo'

Is it possible ?
