### ISSUE TITLE
Ability to unset a gauge with labels.

### ISSUE THREAD

**Issue by baryluk** [prometheus/client_python#682]
I have a process that tracks many promethues metrics (few info, some gauges initialized once at startup, some gauges updated on stat  changes, and some counters and summaries).

```python3
CPU_PROFILE = promethues_client.Gauge('xyz_cpu_profile', 'State (cpu profile) of each cpu in the system', ['cpu', 'physical_pacakge_id', 'core_id', 'profile'])
```

Basically this is a mapping from (cpu, package, core) to a string (enum really, with ~6 possible values).

I use this form, because I want to do aggregations and filtering by profile, and see exactly which cpus have that profile. (counting would be easy with other gauge).

The issue is that if CPU transitions from profile A to profile B, I need to retrive the current profile, set the gauge for it to 0, and set the gauge with the new profile to 1. While this is not a huge issue (maximal cardinality even without removing these gauges would be about 200), it is a minor issue never the less, requiring extra logic.

I would like to have two options:

1) Unset a specific metric + labels. So it doesn't register even as zero. Should save a bit of memory in both python process and in prometheus.  Maybe: `CPU_PROFILE.labels(cpu=1, physical_pacakge_id=0, core_id=1, profile="performance").unset()`

Even better would be to be able to say: `CPU_PROFILE.unset_labels(cpu=1, physical_pacakge_id=0, core_id=1)`  (with only PART of labelset, which would remove any labelsets having specified labels with specific values, but matching on any other labels no matter what is their value).

2) Ability to prepare the entire new map, and change it atomically, with all labels and values that were in the metric, but are no longer there, discarded (the existing ones should be kept so the `_created` is kept working. Maybe: `CPU_PROFILE.assign_from_dict( { .... })`

I know there is `Enum` (and I use it for other metric `CPU_PROFILE_STATE`), but it is not suited for aggregation by its value. (You can select / aggregate by labels, not by the value of timeseries, as that doesn't make sense).

I do not know if other Prometheus "client" libraries for other languages provide such functionality. I remember having similar functionality in C++ borgmon libraries at Google.

**Comment by csmarchbanks** [comment]
Hello,

I believe this is possible today using `CPU_PROFILE.remove(1, 0, 1, "performance")`, I would happily accept a contribution that allows specifying keyword arguments similarly to `.labels()`. Let me know if the remove functionality is not what this issue is asking for.

**Comment by baryluk** [comment]
@csmarchbanks Hi Chris. Yes, `.remove(*labelset)` totally works. I was looking in this code, and I don not know how I missed it. I also found `.clear()`, that allows to implement the second point too without big issues (there is minor race condition possible there, but nothing too important for me right now).
