### ISSUE TITLE
how to remove metric?

### ISSUE THREAD

**Issue by MyoungHaSong** [prometheus/client_python#690]
I am using the gauge function to create a custom metric.

I'd like to get rid of this at times when metrics aren't needed.

what should I do ?

**Comment by Tomasz-Kluczkowski** [comment]
Hi,

If you know what was the label values tuple(s) that the metric was set when you did `your_metric.labels(label_value_1, label_value_2, ....).set(value)` then you just call your_metric.remove(label_value_1, label_value_2, ....)`. Alternatively to remove every record from a metric do `your_metric.clear()`
