### ISSUE TITLE
Histogram bucket values are duplicated

### ISSUE THREAD

**Issue by vpecinka** [prometheus/client_python#697]
Hi,

for Histogram the value for given bucket is duplicated to "higher" buckets

I have a simple code that adds value to the `0.75` bucket only. But it add to all above as well.

```python3
from prometheus_client import Histogram, start_http_server
import time

h = Histogram('request_latency_seconds', 'Description of histogram')
start_http_server(9111)

while True:
    h.observe(0.07)
    time.sleep(1)
```

The result after some time (python_* metric skipped):
```
(bash) % curl http://localhost:9111

# HELP request_latency_seconds Description of histogram
# TYPE request_latency_seconds histogram
request_latency_seconds_bucket{le="0.005"} 0.0
request_latency_seconds_bucket{le="0.01"} 0.0
request_latency_seconds_bucket{le="0.025"} 0.0
request_latency_seconds_bucket{le="0.05"} 0.0
request_latency_seconds_bucket{le="0.075"} 13.0
request_latency_seconds_bucket{le="0.1"} 13.0
request_latency_seconds_bucket{le="0.25"} 13.0
request_latency_seconds_bucket{le="0.5"} 13.0
request_latency_seconds_bucket{le="0.75"} 13.0
request_latency_seconds_bucket{le="1.0"} 13.0
request_latency_seconds_bucket{le="2.5"} 13.0
request_latency_seconds_bucket{le="5.0"} 13.0
request_latency_seconds_bucket{le="7.5"} 13.0
request_latency_seconds_bucket{le="10.0"} 13.0
request_latency_seconds_bucket{le="+Inf"} 13.0
request_latency_seconds_count 13.0
request_latency_seconds_sum 0.9100000000000004
# HELP request_latency_seconds_created Description of histogram
# TYPE request_latency_seconds_created gauge
request_latency_seconds_created 1.63191530135688e+09
```

**Comment by quanuw** [comment]
Hi @vpecinka, I'm new to this project, but could this be happening because histogram buckets are cumulative? https://prometheus.io/docs/practices/histograms/#count-and-sum-of-observations

**Comment by vpecinka** [comment]
> Hi @vpecinka, I'm new to this project, but could this be happening because histogram buckets are cumulative? https://prometheus.io/docs/practices/histograms/#count-and-sum-of-observations

The problem above is that the output should be like

```
:
request_latency_seconds_bucket{le="0.005"} 0.0
request_latency_seconds_bucket{le="0.01"} 0.0
request_latency_seconds_bucket{le="0.025"} 0.0
request_latency_seconds_bucket{le="0.05"} 0.0
request_latency_seconds_bucket{le="0.075"} 13.0
request_latency_seconds_bucket{le="0.1"} 0.0
request_latency_seconds_bucket{le="0.25"} 0.0
request_latency_seconds_bucket{le="0.5"} 0.0
request_latency_seconds_bucket{le="0.75"} 0.0
request_latency_seconds_bucket{le="1.0"} 0.0
request_latency_seconds_bucket{le="2.5"} 0.0
request_latency_seconds_bucket{le="5.0"} 0.0
request_latency_seconds_bucket{le="7.5"} 0.0
request_latency_seconds_bucket{le="10.0"} 0.0
request_latency_seconds_bucket{le="+Inf"} 0.0
:
```
because my example generates metrics for the only bucket. The value is cumulative, that is ok. 

As found that the `class Historgram` has the data in the correct bucket (did some debug output during processing) and I suspect somethings goes wrong only for the output.

**Comment by sdfordham** [comment]
You need to carefully read the following (from [here](https://prometheus.io/docs/concepts/metric_types/#histogram))

> Histogram
>
> A histogram samples observations (usually things like request durations or response sizes) and counts them in configurable buckets. It also provides a sum of all observed values.
> 
> A histogram with a base metric name of <basename> exposes multiple time series during a scrape:
> 
>*  cumulative counters for the observation buckets, exposed as `<basename>_bucket{le="<upper inclusive bound>"}`
>*  the total sum of all observed values, exposed as `<basename>_sum`
>*  the count of events that have been observed, exposed as `<basename>_count` (identical to `<basename>_bucket{le="+Inf"}` above)
> 
> Use the histogram_quantile() function to calculate quantiles from histograms or even aggregations of histograms. A histogram is also suitable to calculate an Apdex score. When operating on buckets, remember that the histogram is cumulative. See histograms and summaries for details of histogram usage and differences to summaries.

The histograms you are probably used to are _ordinary histograms_, prometheus uses _cumulative histograms_.

**Comment by vpecinka** [comment]
Now I get it what you mean cumulative: https://povilasv.me/prometheus-tracking-request-duration/

Ok, thanks, no issue
