### ISSUE TITLE
Support multiprocess mode without setting an environment variable?

### ISSUE THREAD

**Issue by miroswan** [prometheus/client_python#701]
Hello folks. I have interest in using the `prometheus_client.multiprocess.MultiProcessCollector` for applications that run in a multi-process scenario. The issue is that it seems currently impossible to use this feature without setting the `PROMETHEUS_MULTIPROC_DIR` environment variable. There are situations in which I'll be developing code in this mode and will not have control over the environment variables set for the application. 

[I believe this code demonstrates why this is the case](https://github.com/prometheus/client_python/blob/master/prometheus_client/values.py#L111-L122)

I understand that this must be set before any metrics are instantiated. I think the main reason for this is the fact that some code paths are reliant on the the value [here](https://github.com/prometheus/client_python/blob/master/prometheus_client/values.py#L122) which is set as soon as the module is loaded. 

If we're interested in supporting multiprocessing mode without explicitly requiring the environment variable, I'd be open to discussing possible solutions here and implementing the needful. Please let me know.

**Comment by roidelapluie** [comment]
What would you propose? Do you have some ideas in mind? Thanks!

**Comment by miroswan** [comment]
Hmm.. 

It looks like [`prometheus_client.metrics.MetricWrapperBase._metric_init`](https://github.com/prometheus/client_python/blob/master/prometheus_client/metrics.py#L211-L216) was originally setup for delayed initialization. 

>
    """
    Initialize the metric object as a child, i.e. when it has labels (if any) set.
    This is factored as a separate function to allow for deferred initialization.
    """

Upon further inspection, each child class of [`prometheus_client.metrics.MetricWrapperBase`](https://github.com/prometheus/client_python/blob/master/prometheus_client/metrics.py#L51) actually calls this method within its constructor function if [`prometheus_client.metrics.MetricWrapperBase._is_observable`](https://github.com/prometheus/client_python/blob/master/prometheus_client/metrics.py#L55) returns `true`. My first thought is...what if we actually deferred initialization until the collector is used? If we took this approach, then instead of using [`prometheus_client.values.ValueClass`](https://github.com/prometheus/client_python/blob/master/prometheus_client/values.py#L122) which is the result of [`prometheus_client.values.get_value_class`](https://github.com/prometheus/client_python/blob/master/prometheus_client/values.py#L111), we could call [`prometheus_client.values.get_value_class`](https://github.com/prometheus/client_python/blob/master/prometheus_client/values.py#L111) directly within [`prometheus_client.metrics.MetricWrapperBase._metric_init`](https://github.com/prometheus/client_python/blob/master/prometheus_client/metrics.py#L211-L216) if `self._value` is `None`. 

* If this were the case, then I believe users would have the chance to somehow set multiprocess mode in code before each collector determines which class to use for values. 

* The [`prometheus_client.values.get_value_class`](https://github.com/prometheus/client_python/blob/master/prometheus_client/values.py#L111) could then atomically reference a global that determines if multi-processing mode is enabled. 

* Some default initialization could occur that checks for the presence of the environment variable `PROMETHEUS_MULTIPROC_DIR`. If there, then set a module scoped variable `PROMETHEUS_MULTIPROC_DIR`. The [`prometheus_client.values.get_value_class`](https://github.com/prometheus/client_python/blob/master/prometheus_client/values.py#L111) function could check for this value through the variable instead of the environment. So, the default behavior would still work as usual, but the user would have the ability to atomically set this value before any collectors are used. 

True delayed initialization of the value class upon use does carry some performance implications. We'd have to check if `self._values` is `None` and if `None`, then atomically read the value of the `PROMETHEUS_MULTIPROC_DIR` variable. However, this should only ever have to happen on the first time the collector is used. After first used, `self._value` will not be None and the method on the collector that updates its value will proceed as usual. 

This is what I was thinking so far but definitely interested in what you folks are thinking as well.

**Comment by miroswan** [comment]
Of course some adjustments to this approach could be made. @roidelapluie Please LMK what you think. I'd like to get started working on this as soon as I can if possible.

**Comment by roidelapluie** [comment]
Thanks for the explanation. I will review this ASAP. After a first read, I am wondering how we can ensure that all the metrics will use the same mode.

**Comment by roidelapluie** [comment]
The issue with your approach is that it *is* a valid use case to use a metric just after the initialization. There is no way to prevent this. You need to know before any import if you are in multi process, or single process.

So, this approach would not work for a library.

What I would suggest you is to start your program with setting the environment variable, that should work.

**Comment by miroswan** [comment]
I'm I'm understanding you correctly, that it's a valid use case to use a metric just after initialization, then the default behavior would still occur with the design I've laid out. The environment variable would still be a valid way of setting the multiprocess mode. This is because the module scooped variable would get set when the prometheus client gets loaded. As such, the behavior you're seeing today would still work. 

However, for folks that want to set this value in code, the approach I've mentioned would work as well. This is because the ValueClass is lazily instantiate on first use. This would allow something like this to work _also_. 

```Python
from prometheus_client import Counter, MULTIPROCESS_MODE, set_mode

some_counter = Counter("some_counter", "Counts things")

def some_func():
    some_counter.inc()

def main():
    set_mode(MULTIPROCESS_MODE) # this is atomic
    while True:
        some_func()

if __name__ == '__main__':
    main()
```
This should also work because on load, the module scoped mode variable would be set based on the environment. If set_mode is never called, the default behavior just happens. 

```Python
from prometheus_client import Counter
some_counter = Counter("some_counter", "counts things")
some_counter.inc()
```

Setting the environment variable in code does not work because the ValueClass is set before that can be done. Since metrics are often module scoped, their constructor methods are called, which uses ValueClass and there is no way to modify.

**Comment by miroswan** [comment]
Hmm. Let me think about this more. I wouldn't want to make the API feel inconsistent.

**Comment by roidelapluie** [comment]
`some_counter = Counter("some_counter", "Counts things") # Does not use ValueClass during construction`


This should actually set the counter to zero.

**Comment by miroswan** [comment]
I've gotten around this issue for my purposes.
