### ISSUE TITLE
End Support for Python 2.7

### ISSUE THREAD

**Issue by csmarchbanks** [prometheus/client_python#717]
Python 2.7 usage has dropped significantly over the last 6-9 months, and over the last 3 months makes up less than 2% of downloads. At this point I think it is worth dropping support and allowing new features as well as some cleanup.

Current Python 2.7 users would be able to continue to use v0.12.x and earlier, and patches could be added to the v0.12.x release series if absolutely necessary.

If you have concerns (or support), please voice them here.

### 2021-08-01 - 2021-10-31

| category | percent | downloads  |
| -------- | ------: | ---------: |
| 3        |  96.57% | 77,679,427 |
| 2        |   1.98% |  1,596,557 |
| null     |   1.45% |  1,165,008 |
| Total    |         | 80,440,992 |

### 2021-10-01 - 2021-10-31

| category | percent | downloads  |
| -------- | ------: | ---------: |
| 3        |  97.39% | 30,050,858 |
| null     |   1.30% |    402,541 |
| 2        |   1.30% |    401,660 |
| Total    |         | 30,855,059 |

Compiled from 
```
pypistats python_major prometheus_client
```

**Comment by roidelapluie** [comment]
Will we be able to mark is as not supporting 2.7, and will 2.7 users still be able to keep using the last version?

**Comment by csmarchbanks** [comment]
Yes, for example users of Python 2.6 are currently still able to use https://pypi.org/project/prometheus-client/0.9.0/, but https://pypi.org/project/prometheus-client/0.10.0/ requires Python>=2.7.

**Comment by roidelapluie** [comment]
I do not have specific concerns then, dropping 2.7 sounds good to me.
