### ISSUE TITLE
Callback function to let program know that collection is starting

### ISSUE THREAD

**Issue by DrLuke** [prometheus/client_python#75]
I would like to collect metrics from a program I can't modify. The only way is to query it with UDP packets. Querying the program can be easily implemented in python. However, it is only necessary to do this as often as prometheus queries the instance.  
As I see it, there is currently no way to let the program know when prometheus is making a http request. Such information could be used to trigger collection from the program via UDP once, saving ressources and bandwidth.

**Comment by brian-brazil** [comment]
What you want is a custom collector so that you can write an exporter. See http://www.robustperception.io/writing-a-jenkins-exporter-in-python/ for an example.

As you're writing an exporter, see also https://docs.google.com/document/d/1JapuiRbp-XoyECgl2lPdxITrhm5IyCUq9iA_h6jp3OY/edit

**Comment by DrLuke** [comment]
Thank you for the reply, this is exactly what I needed!
