### ISSUE TITLE
http_requests_total value was shared lower than the actual

### ISSUE THREAD

**Issue by kumar-rvp** [prometheus/client_python#751]
I am working on  http_requests based HPA. I notices HPA scaling down was not happening and while triaging found out that at time  http_requests_total value was lower than the actual for a one my handler. 
I see this behavior consistently. 
Can anyone please check whether this is a issue or I am missing something. 
<img width="1432" alt="Screen Shot 2022-01-19 at 12 14 23 AM" src="https://user-images.githubusercontent.com/20964610/150092690-60948b00-bf82-48b6-ada2-9c707bcfbeca.png">
#

**Comment by csmarchbanks** [comment]
Hello, do you have any additional details you could share? The drops in that graph look unexpected, and since not all go to zero could be an issue that is not just failing scrapes. Are you running in a multi-process environment for example?

**Comment by kumar-rvp** [comment]
Thanks @csmarchbanks . Yes I am running in multi-process environment. Using gunicorn web server with 4 (async) worker processors.

**Comment by kumar-rvp** [comment]
@csmarchbanks I  just read about prometheus_multiproc_dir and I am trying to implement that. Thanks

**Comment by csmarchbanks** [comment]
Great, let me know if `prometheus_multiproc_dir` does not work. My guess is that depending on which worker process handles the request the result will be different right now, and once you specify `prometheus_multiproc_dir` it will work properly.

**Comment by kumar-rvp** [comment]
Creating prometheus_multiproc_dir solved the issue. Thanks for your support.
