### ISSUE TITLE
stop_http_server()

### ISSUE THREAD

**Issue by tlc** [prometheus/client_python#76]
There is no way to stop the metrics server if you need to reconfigure (change the port).

**Comment by tlc** [comment]
Returning the thread, so the application could manage it would be sufficient.

**Comment by brian-brazil** [comment]
Hmm, I'd have to think on this a bit. We probably shouldn't expose the internals of how we're implementing this to the user.

This is intended mostly as a convenience function, there is the option of having your own variant of it if you've different needs.

**Comment by rud** [comment]
@tlc issue ready to close then?

**Comment by eddieparker** [comment]
In case it helps others - I came here looking for a similar solution.  Here's a quick working example to crib off of:

```
# A wrapper around the python http server and prometheus MetricsHander to allow us to stop the server
class CustomPrometheusHttpServer:
	def __init__(self, port):
		self.port = port
		self.httpd = None
		self.thread = None

	def start(self):
		self.httpd = http.server.HTTPServer(('0.0.0.0', self.port), prometheus_client.exposition.MetricsHandler)
		self.thread = threading.Thread(target=self.httpd.serve_forever)
		self.thread.daemon = True
		self.thread.start()

	def stop(self):
		self.httpd.shutdown()
		self.httpd.server_close()
		self.thread.join()
```

**Comment by engin-ipek** [comment]
> self.httpd.shutdown()
> 		self.httpd.server_close()

hello, since `start_http_server` returns the server and the thread, why can't we do this instead?:

````python
httpd, t = start_http_server()
time.sleep(30)
httpd.shutdown()
httpd.server_close()
t.join()
