### ISSUE TITLE
Decorators break function signatures

### ISSUE THREAD

**Issue by hynek** [prometheus/client_python#77]
The client does a common anti-pattern of doing a closure with `*args,**kwargs` but that sadly breaks introspection of wrapped methods.

This is a concrete problem e.g. if you wrap Pyramid views that get different arguments depending on how many arguments are present (either `context, request` or just `request`).

You can find more information on this in these blog posts: https://github.com/GrahamDumpleton/wrapt/tree/master/blog

Solutions to it is to either use or copy/paste from the [wrapt](http://wrapt.readthedocs.org/en/latest/) (better) or [decorator](http://pythonhosted.org/decorator/documentation.html) (OK-ish) packages.

**Comment by brian-brazil** [comment]
Would you like to send a pull request to fix this?

wrapt appears to have C dependencies, so that's not going to work out.

**Comment by hynek** [comment]
So you could live with depending on decorator?  It’s python-only without further dependencies.

I still have the problem that I can’t run the tests locally on OS X because of the `s.connect(('localhost', 0))` thing.  If you’d fix that, I’ll happily fix your decorators. :)

**Comment by brian-brazil** [comment]
> So you could live with depending on decorator? It’s python-only without further dependencies.

I'd prefer to copy it in. While it's old enough that it should be everywhere, let's play it safe.

**Comment by hynek** [comment]
As you wish.

I still need you to fix the test suite tho. :)

**Comment by brian-brazil** [comment]
If you've got an alternative way to get the machines IP that also works on Windows and Linux then I'm happy to change it.

**Comment by hynek** [comment]
I‘m fine with if you just skip the test on OS X (and mostly likely all BSDs? at least FreeBSD breaks too).

I just need a way to run tests locally.  Once that’s fixed, I can do the tox/Travis CI/codecov integration for you too if you wish.  By not being able to run the test suite on all BSDs you’re limiting the set of contributors quite a bit.
