### ISSUE TITLE
Different metrics with the same labels sent to push gateway are overwriting each other

### ISSUE THREAD

**Issue by mdebord-dlr** [prometheus/client_python#779]
It is my intention to run a scheduled script and push various metrics to push gateway as it processes by calling `push_to_gatway()` as needed depending on the logic of the application and results it finds.

### Problem:

It appears that using the same job name (grouping key) across _different_ metrics is causing them to not all publish. The below example demonstrates.

>NOTE: The following script is an extremely simplified example vs the actual application. **The real application has many different metrics and different labels, it's been stripped down for clarity of the isolated issue itself.** 

In the following script, **only `test_metric_b`** shows up prometheus:
```
from prometheus_client import CollectorRegistry, push_to_gateway, Gauge

job = 'test'
push_gw_host = "prom.local.example:9091"

def prom_notify_a(job):
    registry = CollectorRegistry()
    Gauge("test_metric_a",
          "Testing prometheus metric behavior A",
          registry=registry).set_to_current_time()
    push_to_gateway(push_gw_host, job=job, registry=registry)

def prom_notify_b(job):
    registry = CollectorRegistry()
    Gauge("test_metric_b",
          "Testing prometheus metric behavior B",
          registry=registry).set_to_current_time()
    push_to_gateway(push_gw_host, job=job, registry=registry)


prom_notify_a(job)
prom_notify_b(job)
```

```
# If the function calls are swapped, then only `test_metric_a` shows up in prometheus: 
prom_notify_b(job)
prom_notify_a(job)
```

Essentially, only the last call to `push_to_gateway()` is actually captured if the job names match, regardless of the metric names being different. 

#### Workaround: 

It works fine when a "unique" job name is used when publishing the metrics. It would be expected that, since the metrics themselves are different names (`test_metric_a` & `test_metric_b`), it wouldn't matter if the job names (or any combination of labels) are identical. 

**The below script works 100%**, and both metrics show up fine. Note the `job=key` and `key` is unique per metric.

```
from prometheus_client import CollectorRegistry, push_to_gateway, Gauge

job = 'test'
push_gw_host = "prom.local.example:9091"

def prom_notify_a(job):
    registry = CollectorRegistry()
    key=job + 'a'
    Gauge("test_metric_a",
          "Testing prometheus metric behavior A",
          registry=registry).set_to_current_time()
    push_to_gateway(push_gw_host, job=key, registry=registry)

def prom_notify_b(job):
    registry = CollectorRegistry()
    key=job + 'b'
    Gauge("test_metric_b",
          "Testing prometheus metric behavior B",
          registry=registry).set_to_current_time()
    push_to_gateway(push_gw_host, job=key, registry=registry)


prom_notify_a(job)
prom_notify_b(job)
```

**Comment by csmarchbanks** [comment]
Hello, it sounds like for your use case (adding metrics incrementally instead of all at once) you should be using `pushadd_to_gateway` instead of `push_to_gateway`. The code has some documentation, but effectively `pushadd_to_gateway` uses the push gateway POST endpoint instead of PUT and will only replace metrics with the same name, and add the rest, rather than replacing everything in the grouping key. Let me know if I did not understand your problem correctly!

**Comment by mdebord-dlr** [comment]
@csmarchbanks Thank you for the clear explanation. I believe that's probably my problem and of course I must have just missed it in the doc. `pushadd_to_gateway` seems to do exactly what I need.
