### ISSUE TITLE
start_http_server dual stack and IPv6 literals

### ISSUE THREAD

**Issue by baryluk** [prometheus/client_python#791]
Version 0.13.1

Python 3.9.11 on Debian testing.

I saw https://github.com/prometheus/client_python/issues/567 , but this is still broken.

`prometheus_client.start_http_server(port=9888, addr="localhost")`  - only listens on IPv4

`prometheus_client.start_http_server(port=9888, addr="::")` - doesn't work

`prometheus_client.start_http_server(port=9888, addr="::1")` - doesn't work

`prometheus_client.start_http_server(port=9888, addr="[::]")` - doesn't work

Optimally, it should be configurable using a single parameter, because it is easier to pass things from command line using a single parameter, than parsing it manually in every program that requires it:

`--listen=:9888` for example, to listen on `0.0.0.0` and `::`.
`--listen=localhost:9888` for example, to listen on `127.0.0.1` and `::1`.
`--listen=[::1]:9888` for example, to listen on `::1`.
`--listen=127.0.0.1:9888` for example, to listen on `127.0.0.1`.

Ability to bind to interface would also be nice. (i.e. `--listen=10.0.0.1:9888@eth1`)

**Comment by csmarchbanks** [comment]
I think this was fixed in https://github.com/prometheus/client_python/pull/657, would you verify that if you use the latest master IPv6 works? 

I am planning to do a release for 0.14 soon which would contain the above PR.

**Comment by csmarchbanks** [comment]
Closing as I believe this has been fixed in the most recent release.
