### ISSUE TITLE
Gauge - there is `livesum` and `all` but what about `sum`?

### ISSUE THREAD

**Issue by nkov** [prometheus/client_python#793]
I have a multi-process application where multiple processes are used to track a single value. For instance, lets say I have 3 processes: A, B, and C behind a load balancer.

`A` receives a request to increment the Gauge: `A = 1, B = 0, C = 0`
`B` receives a request to decrement the Gauge: `A = 1, B = -1, C = 0`

So using `livesum`, my current gauge value is 0 (as expected). However, what would happen if `B` suddenly needs to terminate (eg. due to auto-scaling) or restart (due to a crash, memory management, etc.)? How does the client handle this? Do I assume correctly that the Gauge will now show the incorrect value of `1`, because "live sum" only considers the living processes?

**Comment by csmarchbanks** [comment]
Your analysis is correct, https://github.com/prometheus/client_python/pull/794 was just opened to add the missing modes, so hopefully there will be a sum option soon!

**Comment by csmarchbanks** [comment]
Fixed in #794

**Comment by nkov** [comment]
@csmarchbanks Awesome, what a quick turnaround. When could we expect this to be released to PyPI?

**Comment by csmarchbanks** [comment]
I usually try to cut a release about once every three months but there isn't a specific cadence. I may try to review the multiprocess help text PR and cut a release after that is merged though.
