### ISSUE TITLE
Breaking change in most recent release

### ISSUE THREAD

**Issue by richardARPANET** [prometheus/client_python#795]
```
  File "/usr/local/lib/python3.8/dist-packages/prometheus_flask_exporter/__init__.py", line 15, in <module>
    from prometheus_client.exposition import choose_encoder
```

added in `0.14.0` it seems. are you following https://semver.org/?

**Comment by jmayse** [comment]
We are experiencing this issue as well importing `prometheus_client` from `prometheus_flask_exporter`. `prometheus_flask_exporter` has an unversioned import of `prometheus_client` in their requirements.txt and this latest release of `prometheus_client` seems to have broken `prometheus_flask_exporter`. However, this is likely a breaking change for `prometheus_flask_exporter`, not `prometheus_client`, no?

**Comment by csmarchbanks** [comment]
Sorry about this, the breaking change was accidental, and was renamed in https://github.com/prometheus/client_python/pull/776. I am happy to change it back and created https://github.com/prometheus/client_python/pull/796.

Note that breaking changes are allowed in 0.x releases, but if it was a purposeful change a [CHANGE] entry would be added to the changelog.
