### ISSUE TITLE
Problems with Info

### ISSUE THREAD

**Issue by bsiara** [prometheus/client_python#816]
Hi,
I try to construct Info object:
`mobi = prometheus_client.Info('metric_info', 'Monitored info')`
I get error:
`2022-06-03 06:15:33,435 - ERROR - No label names were set when constructing info:metric_info`
when I try to set labels:
`mobi = prometheus_client.Info('metric_info', 'Monitored info', ['info1', 'info2'])`
I get error:
`2022-06-03 06:19:24,879 - ERROR - 'Info' object has no attribute '_labelname_set'`
prometheus_client==0.14.1
Please fix the issue.
Regards
BS

**Comment by csmarchbanks** [comment]
Hello, thank you for the report, would you also provide how you are calling `mobi.info`? The first error message suggests that you were trying to call `mobi.labels(<something>)` when you did not have labels in your constructor.

Here is an example of using info both without and with labels:
```python
from prometheus_client import exposition
from prometheus_client import CollectorRegistry, Info

registry = CollectorRegistry()
mobi = Info('metric_info', 'Monitored info', registry=registry)
mobi.info({"hello": "world"})

mobi2 = Info('metric_info2', 'Monitored info', ['info1', 'info2'], registry=registry)
mobi2.labels('foo', 'bar').info({"hello": "world"})

print(str(exposition.generate_latest(registry), 'utf-8'))
```
This gives me the output:
```
# HELP metric_info_info Monitored info
# TYPE metric_info_info gauge
metric_info_info{hello="world"} 1.0
# HELP metric_info2_info Monitored info
# TYPE metric_info2_info gauge
metric_info2_info{hello="world",info1="foo",info2="bar"} 1.0
```
