### ISSUE TITLE
Getting error on endpoint "A server error occurred.  Please contact the administrator."

### ISSUE THREAD

**Issue by jcpoconnor** [prometheus/client_python#819]
New to the Prometheus client on Python and implementing an endpoint for an application.

Not seeing any obvious errors but don't have any debugging log available (yet) for the application but wondering if anyone else has observed this and could point to potential causes.

**Comment by csmarchbanks** [comment]
I do not believe that is an error that would come from this client, it is likely an error from your application/how you expose this client. Do you have a code sample to show what you are trying to do/reproduce this issue?

**Comment by sd2k** [comment]
It looks like this can happen if a custom collector raises an unhandled exception. The following code snippet causes the error to occur when browsing to the Prometheus client endpoint.

```
import time

from prometheus_client import start_http_server
from prometheus_client.core import GaugeMetricFamily, REGISTRY


class CustomCollector(object):
    def __init__(self):
        self._started = False
    def collect(self):
        if self._started:
            raise Exception('whoops')
        self._started = True
        yield GaugeMetricFamily('my_gauge', 'Help text', value=7)

REGISTRY.register(CustomCollector())

if __name__ == '__main__':
    # Start up the server to expose the metrics.
    start_http_server(8000)
    # Generate some requests.
    while True:
        time.sleep(1)
```

The error itself [originates in WSGI](https://github.com/python/cpython/blob/f4c03484da59049eb62a9bf7777b963e2267d187/Lib/wsgiref/handlers.py#L120). Perhaps the library should be catching exceptions when attempting to collect?

**Comment by csmarchbanks** [comment]
In that example it looks like the behavior I expect. I am seeing the "A server error occurred. Please contact the administrator." error on the page, and the exception is printed to stdout so that someone can fix it.

We could propagate the exception to the page as well, but that could also leak information so the generic message might be better.

**Comment by jcpoconnor** [comment]
Apologies for not returning to this one - This was an app error in the end.

**Comment by junneyang** [comment]
> It looks like this can happen if a custom collector raises an unhandled exception. The following code snippet causes the error to occur when browsing to the Prometheus client endpoint.
> 
> ```python
> import time
> 
> from prometheus_client import start_http_server
> from prometheus_client.core import GaugeMetricFamily, REGISTRY
> 
> 
> class CustomCollector(object):
>     def __init__(self):
>         self._started = False
>     def collect(self):
>         if self._started:
>             raise Exception('whoops')
>         self._started = True
>         yield GaugeMetricFamily('my_gauge', 'Help text', value=7)
> 
> REGISTRY.register(CustomCollector())
> 
> if __name__ == '__main__':
>     # Start up the server to expose the metrics.
>     start_http_server(8000)
>     while True:
>         time.sleep(1)
> ```
> 
> The error itself [originates in WSGI](https://github.com/python/cpython/blob/f4c03484da59049eb62a9bf7777b963e2267d187/Lib/wsgiref/handlers.py#L120). Perhaps the library should be catching exceptions when attempting to collect?

same error, any suggestion?
