### ISSUE TITLE
Not at all clear how to add labels to the Summary(...) time() decorator pattern

### ISSUE THREAD

**Issue by gjcarneiro** [prometheus/client_python#82]
In the README, in one of the samples, we have:

``` python
# Create a metric to track time spent and requests made.
REQUEST_TIME = Summary('request_processing_seconds', 'Time spent processing request')

# Decorate function with metric.
@REQUEST_TIME.time()
def process_request(t):
```

But what if I want to add labels to this?  I can't figure out how to make it work.  My current code which doesn't work is:

``` python
TRADE_REQUEST_TIME = Summary(
    'request_processing_seconds',
    'Time spent processing a request',
    labelnames=('method', 'endpoint', 'whitelabel'),
    labelvalues=('get', '/trade/', settings.WHITELABEL_NAME))


@TRADE_REQUEST_TIME.time()
def render_trade_page(request, sport):
    ...
```

But I get:

```
    @TRADE_REQUEST_TIME.time()
AttributeError: '_LabelWrapper' object has no attribute 'time'
```

Any advice?

**Comment by jayme-github** [comment]
Same for me with Counter's `count_exceptions()`

**Comment by jayme-github** [comment]
It's working for me with something like:
```py
TRADE_REQUEST_TIME = Summary(
    'request_processing_seconds',
    'Time spent processing a request',
   ('method', 'endpoint', 'whitelabel')
)

@TRADE_REQUEST_TIME.labels('GET', '/trade/', settings.WHITELABEL_NAME).time()
def render_trade_page(request, sport):
  ...
```

**Comment by kamalmarhubi** [comment]
Unfortunately that's not valid syntax. However, this works:

```py
REQUEST_TIME = Summary(
    'request_processing_seconds',
    'Time spent processing a request',
   ('method', 'endpoint', 'whitelabel')
)

TRADE_REQUEST_TIME = REQUEST_TIME.labels('GET', '/trade/', settings.WHITELABEL_NAME)

@TRADE_REQUEST_TIME.time()
def render_trade_page(request, sport):
  ...
```

It's probably worth pushing this down further into your serving code, so you don't need to have the noise of all the submetric definitions.

**Comment by brian-brazil** [comment]
What you should do there is not push it down, but in fact push it up to whatever is calling render_trade_page. Having to add metrics code every time there's a new label value is a bit of a smell.

**Comment by kamalmarhubi** [comment]
Right, by "down" I meant ideally into the wsgi layer. I think that is your "up"?

**Comment by brian-brazil** [comment]
Yes, that's my up. The top is where the calls enter the system.

**Comment by lowang-bh** [comment]
shere

> Unfortunately that's not valid syntax. However, this works:
> 
> ```python
> REQUEST_TIME = Summary(
>     'request_processing_seconds',
>     'Time spent processing a request',
>    ('method', 'endpoint', 'whitelabel')
> )
> 
> TRADE_REQUEST_TIME = REQUEST_TIME.labels('GET', '/trade/', settings.WHITELABEL_NAME)
> 
> @TRADE_REQUEST_TIME.time()
> def render_trade_page(request, sport):
>   ...
> ```
> 
> It's probably worth pushing this down further into your serving code, so you don't need to have the noise of all the submetric definitions.

hi, where does the settings comes from?
