### ISSUE TITLE
With multiprocess setup any metric is documented as "Multiprocess metric"

### ISSUE THREAD

**Issue by slowpokefarm** [prometheus/client_python#831]
While description is mandatory for Gauge and other metric objects the server endpoint only shows "Multiprocess metric" for each metric. Am I doing it wrong?

**Comment by csmarchbanks** [comment]
You are not doing anything wrong, that is how it works today. https://github.com/prometheus/client_python/issues/211 is the open issue for this, and it would be nice if the metric descriptions would come through, but it has not been implemented yet.

Closing as a duplicate.
