### ISSUE TITLE
Option to pass a custom count to `Summary.observe`

### ISSUE THREAD

**Issue by 0x26res** [prometheus/client_python#854]
At the moment Summary.observer looks like this:

```
    def observe(self, amount: float) -> None:
        self._count.inc(1)
        self._sum.inc(amount)
```

I'd like to be able to pass a custom value to increment `_count` (not just 1). I have a use case where I'm receiving messages in bulk, and all I know it the total size and total count of these messages. 

```
    def observe(self, amount: float, count: int = 1) -> None:
        self._count.inc(count)
        self._sum.inc(amount)
```

**Comment by csmarchbanks** [comment]
Thanks for the idea!

I hesitate a bit to add a configurable count as I do not know how we would support quantiles in the future which would depend on knowing the value of each observation, not a bulk of operations. I am willing to reconsider this though.

I wonder if instead of using a Summary here if you could just use two counters instead? Something like `messages_total` and `messages_bytes_total`.

**Comment by 0x26res** [comment]
> I hesitate a bit to add a configurable count as I do not know how we would support quantiles in the future which would depend on knowing the value of each observation, not a bulk of operations. I am willing to reconsider this though.

That makes sense

> I wonder if instead of using a Summary here if you could just use two counters instead? Something like messages_total and messages_bytes_total.

There are many way to go around that problem with the current API actually. At the moment I just increment the two counters manually (`_sum` and `_count`). Having two counters, as you suggest, would work as well. But I'd have to be careful to name them correctly so prometheus understands it was a summary and can the `rate` function works correctly.

**Comment by csmarchbanks** [comment]
👍 Just as a note, `rate` in Prometheus doesn't actually look at the underlying type, it just assumes it is a counter. Usage of `total` and other suffixes for counters is entirely a convention to make it easier for the user to know the type of a metric.

**Comment by csmarchbanks** [comment]
I am also going to close this for now as I don't think we want this feature today.
