### ISSUE TITLE
Old samples of a gauge metric with labels are returned from `/metrics` 

### ISSUE THREAD

**Issue by iNishant** [prometheus/client_python#875]
My understanding is that `/metrics` endpoint should give the **current state of metrics** of a target and the Prometheus server (not the client) keeps storing these metrics with the time it scraped those metrics (forming the time-series). The retention policy decides how long these historical metrics stay in the Prometheus server (or the storage layer). But I am seeing the python client also storing old samples and retaining them (in memory) and returning those old samples whenever `/metrics` is scraped. What I am getting wrong?

seeing this [code](https://github.com/prometheus/client_python/blob/4ab083e4dbf82e3bbb2898fc48db18998fda4d45/prometheus_client/metrics.py#L190) used for setting metric:
```py
if labelvalues not in self._metrics:
    self._metrics[labelvalues] = self.__class__(
        self._name,
        documentation=self._documentation,
        labelnames=self._labelnames,
        unit=self._unit,
        _labelvalues=labelvalues,
        **self._kwargs
    )
return self._metrics[labelvalues]
```

this means samples are overwritten if they have same `labelvalues` otherwise they constantly keep getting added.

Currently as a work around I'm calling [`clear`](https://github.com/prometheus/client_python/blob/4ab083e4dbf82e3bbb2898fc48db18998fda4d45/prometheus_client/metrics.py#L211) right before calling `set` but feels like I'm doing something wrong..

**Comment by csmarchbanks** [comment]
This behavior is by design, for gauges the assumption is to update to the most recent value, e.g. number of items in a queue, then if there are no more updates it is assumed there are still that many items in the queue.

If you are not running in multi-process mode you could use a custom collector to control which gauges are exported at any time, otherwise you will need to delete the entry when you no longer want the value for that label value to be exposed.

**Comment by iNishant** [comment]
Understood, makes sense. So I'm incorrectly using labels I think because each label set is gonna create a new time series so per time series I have to ensure that I "update to the most recent value"... and with the data I have my labelset is extremely dynamic which violates *Do not use labels to store dimensions with high cardinality (many different label values), such as user IDs, email addresses, or other unbounded sets of values.* from [docs](https://prometheus.io/docs/practices/naming/#labels)..

actual gauge I have is this:
```py
payments_success_percentage_gauge = Gauge(
    name="success_percentage",
    documentation="Percentage of payments completed over a standard period of time",
    namespace="payments",
    labelnames=["number_of_payments", "total_amount"],
)
```

I was adding labels to improve my alerts.. for eg trigger alert if `metric < 5% and number_of_payments > 5` but I'm guessing I either need to store this meta info somewhere else (maybe exemplars) or better I can refactor my metric so that it is a simple gauge with no labels.. 

thanks @csmarchbanks, closing the issue

**Comment by csmarchbanks** [comment]
Note that a common way to accomplish what you are describing is to have two counters:
```
payments_total
payments_failed_total
```

Then in your alert you could look at the rate of each to determine when to alert. E.g.
```
sum(rate(payments_failed_total[5m])) / sum(rate(payments_total[5m])) < 0.05 and sum(increase(payments_total[5m])) > 5
```

That would alert if more than 5% of payments failed in the last 5 minutes and there were more than 5 payments processed. You could change the time ranges and thresholds around but hopefully that helps with your problem.
