### ISSUE TITLE
Please return thread from start_http_server

### ISSUE THREAD

**Issue by lukeyeager** [prometheus/client_python#883]
Similar to https://github.com/prometheus/client_python/issues/314, but less invasive, IMHO.

I often wrap APIs with a small layer of Python to turn metrics into something that Prometheus can ingest. Rather than adding `while True: sleep(1)` or similar at the end of my scripts I would like to do this:
```python
prometheus_client.REGISTRY.register(MyCollector())
thread = prometheus_client.start_http_server(80)
thread.join()
```

**Comment by csmarchbanks** [comment]
I think I would be ok with this but will give a bit of time for others to chime in as well. My only concern would be that it would make it a bit harder to change an internal implementation, but that is fairly minor.

**Comment by hholst80** [comment]
I was thinking about this. How do I shut down the serving component?  I guess I don't and just shutdown the application.

**Comment by csmarchbanks** [comment]
Correct, `start_http_server` is designed to be as simple as possible for use cases such as a lightweight exporter. If additional functionality is required it is encouraged to use a different server.

**Comment by hholst80** [comment]
I am in favor of a way to control with the thing created. Having a start_http_server not returning a handle is like a copy command that copies files but doesn't tell you where it put the file copy and now it's a game of hide and seek. ;-)

**Comment by andy-maier** [comment]
We would also like to have that, see issue #983.

**Comment by csmarchbanks** [comment]
#999 will implement this. It returns the server as well as the thread to allow shutdowns, happy to hear any comments about that and will otherwise merge it soon.
