### ISSUE TITLE
use in multiprocess mode  i got a error codec can't decode byte 0xe0 in position 120

### ISSUE THREAD

**Issue by goofy-z** [prometheus/client_python#898]
I was using two containers on the same k8s pod, one running flask for the gunicorn deployment and one running celery, they share a metrics directory use to store *.db files, and when i requests the metrics API error. This problem comes up occasionally

`Traceback (most recent call last):
  File "/Users/goofy/venv/iwork/lib/python3.8/site-packages/prometheus_client/mmap_dict.py", line 45, in _read_all_values
    key = encoded_key.decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe0 in position 120: invalid continuation byte`

I noticed a problem with the data format of one of the files being generated
When I`cat xxx.db`, it looks like normal:
`aqqtta_ai_iwork_abcd_duration`
But when I debug the code, I find that the file shows something like
`b"aqqt\x00\x00\x00\x00\x00\x10@ork_abcd_duration"`

my question is that: why i get a wrong db file

**Comment by csmarchbanks** [comment]
Hello, I don't think multiprocess mode would work with two different containers writing to the same directory. The `.db` files are identified by process id, and each container could have the same process id meaning there will be races updating the files. I recommend writing to separate directories for each of the containers to see if that fixes the issue.

**Comment by goofy-z** [comment]
ths it't works, it's didn't output error log again
