### ISSUE TITLE
Make multiple observations of a value in Histogram

### ISSUE THREAD

**Issue by azro352** [prometheus/client_python#911]
Hi
Just got a usecase for having multiple observations of the same value, but too much for being nice to use a loop, the same as https://github.com/prometheus/client_python/issues/733

My usecase is the following : a million values in a SQL database that I want to observe in a histogram, in 10 buckets

It's faster to execute a sql query that groups the values in buckets than retrieving a million rows 

```sql
select floor(value/5.0)*5, count(1) from table group by floor(value/5.0)*5
```

So I got from my sql query 

| Value | Count  |
|-------|--------|
| 0     | 63821  |
| 5     | 183741 |
| 10    | 102936 |
| …     |        |

So it would be so much easier to use the feature mentioned and written in the following PR rather than a range that takes time to execute 

https://github.com/prometheus/client_python/pull/734

Thanks

**Comment by csmarchbanks** [comment]
I think your example would also best be served by using a custom collector. You already have the buckets from your query so you could just make the final output with something like:
```python
HistogramMetricFamily('your_histogram', 'A histogram of values from SQL', buckets=[('5', 63821), ('10', 102936), ... , ('+Inf', <total number of events>)])
```

**Comment by azro352** [comment]
Thanks for your reply 
I really don't know how to use a custom collector , can you show me a bit more code to use that ? 
Do I instanciate the histogrammetricfamily each 2min (my query rate) ?

**Comment by csmarchbanks** [comment]
You would pull the data from your database and instantiate a new `HistogramMetricFamily` each time Prometheus scrapes your service. You can see an example of using a custom collector in the docs: https://github.com/prometheus/client_python/#custom-collectors.

**Comment by csmarchbanks** [comment]
That's reasonable, more of the idea behind a custom collector should probably be added to the documentation.

```python
REGISTRY.register(CustomCollector())
```

is what causes the custom collector to be used. Once registered every single time the `/metrics` endpoint is called (or `generate_latest`) the `collect()` function will be called and any metrics yielded will be exposed in the scrape results.

**Comment by azro352** [comment]
Oh I see thanks, that's very clear !
