### ISSUE TITLE
Python Wheel includes PYC files and should not

### ISSUE THREAD

**Issue by jkugler** [prometheus/client_python#913]
We are trying to use the tool virtualenv-tools to build a deployable packages.

We are creating our virtualenv with Python 3.11 and when virtualenv-tools tries to unmarshal the PYC files, it of course fails, because the bytecode does not match.

According to the wheel spec (https://packaging.python.org/en/latest/specifications/binary-distribution-format/)

>Wheel, being an installation format that is intended to work across multiple versions of Python, does not generally include .pyc files.

and

> Wheel archives do not need to include .pyc and are less tied to a specific Python version or implementation.

So, while including PYCs is not explicitly prohibited, it is apparently not best practice nor recommended. According to the maintainer of virtualenv-tools, apparently it is wrong. :) See: https://github.com/Yelp/virtualenv-tools/issues/29

Could we get another wheel without the PYC files? I would be happy to submit a  PR, but this appears to be a build issue, and the repo doesn't contain that information.

Thanks!

**Comment by csmarchbanks** [comment]
I think this was fixed in https://github.com/prometheus/client_python/pull/906, but I haven't done another release yet. I will work on that soon, but I think in the meantime you could pin the version to 0.15.0 which doesn't have the .pyc files.

**Comment by csmarchbanks** [comment]
I just released 0.17.0, would you give that version a try and make sure the new build/release process looks good? Thanks!

**Comment by jkugler** [comment]
I pulled down https://files.pythonhosted.org/packages/5b/62/75fc6f255e214ff0a8bd3267a0bd337521dd24f76cd593c10795e488f41b/prometheus_client-0.17.0-py3-none-any.whl and there are no `__pycache__` directories in the wheel. Looks good.

Thanks you so much for the quick turn around on this.
