### ISSUE TITLE
RFE: Summary doesn't provide quantiles

### ISSUE THREAD

**Issue by enkore** [prometheus/client_python#92]

**Comment by brian-brazil** [comment]
If someone sends a PR, it can be added.

**Comment by costela** [comment]
@brian-brazil sorry to butt in, but wouldn't it make more sense for this issue to remain open? AFAICT quantiles support still doesn't exist, right?
Tagging it "help wanted" (and probably "enhancement") would make the situation clear for anyone thinking about contributing a PR.
