### ISSUE TITLE
Gauge value not correct from time to time

### ISSUE THREAD

**Issue by GeluConstantin** [prometheus/client_python#929]
Hi,

I instrumented a python micro service which monitors a file share for the number of files and directories recursively. The micro service is deployed as windows service using the pywin32 library (https://metallapan.se/post/windows-service-pywin32-pyinstaller/)

The service works fine but from time to time (every 3-4 hours) delivers some strange gauge value which are near the time.sleep(60) value. I logged the values on the filesystem and they are fine.

The scrape time of prometheus is set to 73s with a timeout of 15s. I tried also with 60s and 15s timeout.

When setting the time.sleep(60) to 10 s the errors occur more often.

Can you proved a feedback on the issue?

Thank you

Constantin

**Comment by csmarchbanks** [comment]
What do you mean by "strange gauge value"? A bit more details would be helpful such as how are you setting the gauge? Is that where the 60 second sleep comes in?

Ideally you would use a [custom collector](https://github.com/prometheus/client_python/#custom-collectors) to find the most up to date value at the time Prometheus does the scrape, are you following this pattern?

**Comment by GeluConstantin** [comment]
Hi Chris,

the gauge values are most of the time set correctly, but from time to time they are set to value near the timer sleep value. When using a callback to set the value and raise the timer to 5 minutes the problem no longer exists.

Example Gauge without callback: `fileshareSize = folder_size(FILESHAREPATH)`

Example Gauge with callback: `FILESHARE_SIZE_SNR70.set_function(lambda:folder_size(FILESHAREPATH))`

The function reads the size of a folder and subfolders

```
def folder_size(fileSharePath):
    """ a python function to collect the metrics for file share path in Bytes
    """

    fileshare_size = 0

    # calculate the file share size in MBytes

    try:
        for path, dirs, files in os.walk(fileSharePath):
            for f in files:
                fp = os.path.join(path, f)
                fileshare_size += os.stat(fp).st_size
        fileshare_size_MB = round(fileshare_size / 1048576, 2)
    except Exception as e: raise e

    # logging.info(str(datetime.now()) + fileSharePath + " : fileshare_Size_MB: " + str(fileshare_size_MB))
    return fileshare_size_MB

```

**Comment by csmarchbanks** [comment]
I assume in your "Example Gauge without callback" case you are just doing `FILESHARE_SIZE_SNR70.set(fileshareSize)` after that?

Not really sure what is happening, the `set_function` approach should work very well though as it would calculate the proper size at scrape time.

**Comment by GeluConstantin** [comment]
Hi, the problem is solved, set_function was the correct approach.

Thx.

Constantin
