### ISSUE TITLE
Add support for exporters with direct HTTPS/TLS support

### ISSUE THREAD

**Issue by andy-maier** [prometheus/client_python#930]
The node exporter supports HTTPS between the exporter and Prometheus directly since 2020 (https://o11y.eu/blog/prometheus-tls/).

I did not find anything in this package related to the support of HTTPS/TLS between the exporter and Prometheus.

Is it supported? If so, please point me to the documentation or an example.
If not, please consider this a feature request.

**Comment by csmarchbanks** [comment]
We do not have a built in way to create an HTTPS server directly. In the Go libraries the client library also does not have a way to stand up an HTTPS server, but there is https://github.com/prometheus/exporter-toolkit/ which provides some helpers for things like TLS. I am not sure if we would want to add TLS directly to this client or create a similar helper package for users creating exporters.

**Comment by karezachen** [comment]
I'm not sure if I can directly modify def start_wsgi_server() .
This is what I did in my own program.

#946

**Comment by andy-maier** [comment]
This was addressed by PR #946, which meanwhile got merged. I am closing this issue.
