### ISSUE TITLE
Invalid le label in histogram metric

### ISSUE THREAD

**Issue by adamsolomou** [prometheus/client_python#938]
I get a `ValueError: Invalid le label ` when parsing a histogram metric with open metrics integration in Datadog. 

![Screenshot 2023-07-12 at 4 48 41 PM](https://github.com/prometheus/client_python/assets/28399827/30cd70a5-fb89-4e29-aa86-cd7060a5ca82)

**Comment by csmarchbanks** [comment]
I don't think this is a bug in our parser, but instead it is a bug in whatever is creating those metrics. OpenMetrics specifies using a "+Inf" bucket, not "+inf", as far as I know those values are supposed to be case sensitive.

**Comment by adamsolomou** [comment]
Thanks for the insight @csmarchbanks. These metrics are generated by Databricks model serving infrastructure. So neither myself can modify them. I'll get in touch with Databricks to sort that out on their end. I'm closing the issue.
