### ISSUE TITLE
Feature: support z-pages /healthz check with new Counter types

### ISSUE THREAD

**Issue by elasticdotventures** [prometheus/client_python#953]
I'm posting this to propose & discuss an upcoming PR I will be submitted, that is part of my ongoing efforts in defensive programming.   My org presently uses prometheus/client_python to instrument our applications with east/west application telemetry.

I am developing this for my org, but our intention is to submit/upstream the capability back to prometheus/client_python.    
The feature is support google "z-pages" specifically:

/healthz returns HTTP 200 or HTTP 500 based on internal state of the application

z-pages is a defacto standard and the approach has been adopted by many cluster based load balancers including K8s and AWS ECS healthChecks, and /health is supported by virtually all application load balancers.   The current implementation of `prometheus/client_python` doesn't natively have hooks for other third party URL handlers.   

While still in the initial stages of the implementation, I'm seeking any community feedback for an upcoming PR that will reference this issue.  

My plan is:

## Part 1: HealthzCounter
Introduce a healthz counter that operates as a deadman switch, similar in principal to the "up" metric in prometheus.   
In my current plan this would a new metric type using Counter as  base class, something like: 
```
myhealthz = HealthzCounter( ...,  healthz_timeout=30)`
```
The `myhealthz` HealthzCounter works just like a regular Counter, EXCEPT it must be incremented periodically at least every `healthz_timer` [30] seconds by the happy path of an application. 

If an application uses asyncio, and thus has many concurrent happy paths then multiple HealthzUpCounters could be registered, each with their own counter(s) `my_other_healthz = HealthzCounter('myOtherCounter', healthz_timeout=60)`

## Part2: HealthzErrorCounter
Sometimes, it's better to track errors rather than only HappyPath, this is a conceptual "HealthzErrorCounter": 

```
some_error_counter = HealthzErrorCounter("my_handled_error", "suppresses a health check", healthz_lockout=30) 
```
The HealthzErrorCounter would be incremented into a try/except block, either in a standard or async function.  The difference between timeout and lockout is that a lockout suppresses the happy (HTTP 200) /healthz response for the lockout duration when the unhappy/error path is incremented. 

The advantage to using an some_error_counter is that the number of errors can/will only be reset to zero when the application is restarted.    This is very idiomatic when looking at graphs of the data. 

My rationale:  Sometimes having errors accumulate over the running lifespan of the application is perhaps easier for operations neophytes to both graph & alarm on the rate OR sum() of many (using a regex) with alert manager.  This makes tracking applications such as microservices in the same domain easier.    It also means things like db errors if an org follows good naming conventions across it's apps can be easily tracked across in software & would allow applications to be restarted by the overwatching cluster orchestration system.   

While this behavior is possible only using the happy path counters, it's far less idiomatic & intuitive, so the HealthzErrorCounters suppress the health check for a lockout period after they are incremented.  The assumption is the clients will internally attempt to reconnect etc. but after a certain period of time it's best to restart them simply for good measure.   

## Part 3:  the /healthz response
The responses from all HealthzCounters & HealthzErrorCounters will be used to control the `HTTP 200` or `HTTP 500 Reason(s)` response when the prometheus client is accessed as the /healthz url

## Background:
Z-Pages and it's here:  https://stackoverflow.com/questions/43380939/where-does-the-convention-of-using-healthz-for-application-health-checks-come-from

**Comment by roidelapluie** [comment]
Currently none of the Prometheus libraries support this. Would you mind opening a thread on the [prometheus-developer](https://groups.google.com/g/prometheus-developers) mailing list to discuss thuis?

**Comment by csmarchbanks** [comment]
Since you said you will see github before email I did respond on the email list. Going to try to keep discussion there though!

**Comment by csmarchbanks** [comment]
Thank you again for the proposal! However, I'm going to close this as the discussion on the mailing list did not get far and I do not think the scope of Prometheus client libraries should include z pages.
