### ISSUE TITLE
Mounting in FastAPI's APIRouter doesn't expose anything

### ISSUE THREAD

**Issue by mdczaplicki** [prometheus/client_python#962]
I've tried to use FastAPI's `APIRouter` & mount the ASGI app in the router, however the endpoint is not being exposed. It simply returns 404.

**Comment by RedKinda** [comment]
Assuming you mapped it to `/metrics/` try doing `curl yourapp/metrics/` instead of `curl yourapp/metrics`, the trailing slash matters

**Comment by mdczaplicki** [comment]
I actually mount it on `/metrics` and it's not available either with or without a trailing slash.
