### ISSUE TITLE
can generate malformed data by creating a duplicate Counter

### ISSUE THREAD

**Issue by bubaflub** [prometheus/client_python#97]
I accidentally generated malformed data by creating two Counters on the same Registry that had the same name, help text.

Example code:

```
import prometheus_client

reg = prometheus_client.CollectorRegistry()
c1 = prometheus_client.Counter("foo", "bar", labelnames=["baz", "stuff"], registry=reg)
c1.labels({"baz": 1, "stuff": 2}).inc(1)
c2 = prometheus_client.Counter("foo", "bar", labelnames=["baz", "stuff"], registry=reg)
c2.labels({"baz": 3, "stuff": 4}).inc(2)
prometheus_client.push_to_gateway('localhost:8000', job='example', registry=reg)
```

Data sent in request to push gateway:

```
# HELP foo bar
# TYPE foo counter
foo{baz="1",stuff="2"} 1.0
# HELP foo bar
# TYPE foo counter
foo{baz="3",stuff="4"} 2.0
```

Response sent from the push gateway:

```
text format parsing error in line 4: second HELP line for metric name "foo"
```

I'd prefer either getting an error from prometheus_client telling me that I can't add two identical metrics.  Alternatively, I'd like for prometheus_client to merge the two metrics and not send two identical HELP lines.

**Comment by grobie** [comment]
At least client_golang and client_ruby do check for metric uniqueness during registration.

**Comment by rud** [comment]
I think a small merge-request would be appreciated here - any takers?

**Comment by brian-brazil** [comment]
This is more complicated than it might seem at a first glance.

**Comment by rud** [comment]
It wasn't an attempt to sound glib, I do not know the architecture, and am unable to guess at the complexity involved. This was more of an attempt to encourage the reporter to maybe contribute a patch for the specific issue experienced.

**Comment by mad01** [comment]
can you do something to merge it in the generate_latest function maybe?

**Comment by brian-brazil** [comment]
It is an error state, it should be handled at registration time.
