### ISSUE TITLE
0.18.0 change the db format cause incompatibility

### ISSUE THREAD

**Issue by SachiaLanlus** [prometheus/client_python#976]
The .db file generated by 0.17.1 can not read from 0.18.0 vice versa.
This indicate the 0.18.0 is a release with breaking change which is not mentioned in the release note.

**Comment by csmarchbanks** [comment]
As stated under https://github.com/prometheus/client_python#multiprocess-mode-eg-gunicorn "This directory must be wiped between process/Gunicorn runs", we have never promised nor should it be assumed that the .db files are compatible across versions.

I would be ok calling this out in release notes as a change, but I wonder if we could also be more clear that the .db files should never be used across versions?

**Comment by SachiaLanlus** [comment]
I did not notice this warning before.
Thank you for the information.
