### ISSUE TITLE
Release a new version of the prometheus-client package to use the HTTPS support

### ISSUE THREAD

**Issue by andy-maier** [prometheus/client_python#981]
The HTTPS support in PR #946 has been merged, and we have successfully tested it with a beta version of our [zhmc exporter](https://github.com/zhmcclient/zhmc-prometheus-exporter) that uses the "prometheus-client" package from the master branch of the repo.

I would like to release a new version of the zhmc exporter to Pypi, but that cannot be done with package dependencies to git repos.

Could you please release a new version of the "prometheus-client" package to Pypi?

**Comment by csmarchbanks** [comment]
Yep, I am planning to do this soon, probably on Monday.

**Comment by csmarchbanks** [comment]
https://github.com/prometheus/client_python/releases/tag/v0.19.0 is out!

**Comment by andy-maier** [comment]
Thanks much !!
