### ISSUE TITLE
GAUGE multiprocess_mode use 'livemostrecent'，the metrics will not be removed

### ISSUE THREAD

**Issue by ELvisZxc** [prometheus/client_python#985]
I define a Gauge with "livemostrecent" mode, I can find the metrics in prometheus even the exporter no longer provides this metric (gauge.clear()). I expect it will auto-removed after call gauge.clear().

Version:
```
python : 3.10
prometheus-client==0.19.0
```

any suggestions?

**Comment by csmarchbanks** [comment]
Hello, this is a subset of https://github.com/prometheus/client_python/issues/916, so I am going to close it as a duplicate. I would love a contribution to fix this, or else will try to get to it when I have time.

**Comment by ELvisZxc** [comment]
> Hello, this is a subset of #916, so I am going to close it as a duplicate. I would love a contribution to fix this, or else will try to get to it when I have time.

ok，thanks
