### ISSUE TITLE
feat: remote_write support

### ISSUE THREAD

**Issue by venkatamutyala** [prometheus/client_python#991]
It would be great if we could send metrics to prometheus using remote_write

**Comment by seowjin1060** [comment]
Does this feature added now? 
I'm looking sending metrics to AWS managed prometheus, 
Cause It's not supporting pull-metrics to client metric server.

**Comment by venkatamutyala** [comment]
@seowjin1060 no i closed it out shortly after opening it. I felt it didn't belong in this project. The optimal solution is to use the remote_write feature of prometheus itself. You don't need to use this python client for AWS. They have an example in their docs here: https://docs.aws.amazon.com/prometheus/latest/userguide/AMP-onboard-ingest-metrics-remote-write-EC2.html#AMP-onboard-ingest-metrics-remote-write-EC2-server

**Comment by junneyang** [comment]
> It would be great if we could send metrics to prometheus using remote_write

same question
