### ISSUE TITLE
Provide a way to reset a Counter metric

### ISSUE THREAD

**Issue by positron96** [prometheus/client_python#995]
Hi. My program performs some lengthy process of many iterations, and I use a Counter to track current iteration. However, it is normal for the process to finish at some point, and then the user can start it again, without restarting the app. 

> A counter is a cumulative metric that represents a single monotonically increasing counter whose value can only increase or be reset to zero on restart.
(https://prometheus.io/docs/concepts/metric_types/)

In my case it's not the whole app that restarts, but only the calculation procedure, but I think in spirit it's still a Counter's job, not a Gauge (a value that only increments and resets to zero), but there is currently no way in the library to set the Counter to zero.

Would it be possible to add "reset" method to a Counter class?

**Comment by csmarchbanks** [comment]
This is an interesting one. The docs do specifically say that the reset to zero is on restart, but I can also understand the use case. Since https://github.com/OpenObservability/OpenMetrics/blob/main/specification/OpenMetrics.md#counter also specifies that a counter's total may reset I am ok accepting this feature. Are you interested in opening a PR?

For when this is implemented: it will require updating `_created` at the same time.

**Comment by positron96** [comment]
hi! Yes, I can provide a PR soon, but can you elaborate on what needs to change in behavior of `_created` metric? Should it be set to time of reset?

**Comment by JustinJohnsonK** [comment]
is it possible to add `_updated` instead of updating `_created` every time we do reset.

**Comment by csmarchbanks** [comment]
Yep, `_created` just needs to be set to the time of reset. 

From https://github.com/OpenObservability/OpenMetrics/blob/main/specification/OpenMetrics.md#counter, which this library needs to implement:
> A MetricPoint in a Metric's Counter's Total MAY reset to 0. If present, the corresponding Created time MUST also be set to the timestamp of the reset.

So the correct thing to do is update `_created`, not create a new metric or anything like that. Prometheus will soon start using the `_created` data as well, and having a non-standard field would not be supported.
